// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockApplication creates a new instance of MockApplication. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplication(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplication {
	mock := &MockApplication{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApplication is an autogenerated mock type for the Application type
type MockApplication struct {
	mock.Mock
}

type MockApplication_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplication) EXPECT() *MockApplication_Expecter {
	return &MockApplication_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockApplication
func (_mock *MockApplication) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockApplication_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockApplication_Expecter) Close() *MockApplication_Close_Call {
	return &MockApplication_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockApplication_Close_Call) Run(run func()) *MockApplication_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplication_Close_Call) Return(err error) *MockApplication_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_Close_Call) RunAndReturn(run func() error) *MockApplication_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockApplication
func (_mock *MockApplication) Init() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockApplication_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *MockApplication_Expecter) Init() *MockApplication_Init_Call {
	return &MockApplication_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *MockApplication_Init_Call) Run(run func()) *MockApplication_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplication_Init_Call) Return(err error) *MockApplication_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_Init_Call) RunAndReturn(run func() error) *MockApplication_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockApplication
func (_mock *MockApplication) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockApplication_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockApplication_Expecter) Run() *MockApplication_Run_Call {
	return &MockApplication_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockApplication_Run_Call) Run(run func()) *MockApplication_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplication_Run_Call) Return(err error) *MockApplication_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_Run_Call) RunAndReturn(run func() error) *MockApplication_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockApplication
func (_mock *MockApplication) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApplication_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockApplication_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockApplication_Expecter) Stop() *MockApplication_Stop_Call {
	return &MockApplication_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockApplication_Stop_Call) Run(run func()) *MockApplication_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplication_Stop_Call) Return(err error) *MockApplication_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApplication_Stop_Call) RunAndReturn(run func() error) *MockApplication_Stop_Call {
	_c.Call.Return(run)
	return _c
}
