// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: example-service.proto

package example_service

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleServiceFindRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleServiceFindRequest) Reset() {
	*x = ExampleServiceFindRequest{}
	mi := &file_example_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleServiceFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleServiceFindRequest) ProtoMessage() {}

func (x *ExampleServiceFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExampleServiceFindRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *ExampleServiceFindRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type ExampleServiceFindRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 ExampleServiceFindRequest_builder) Build() *ExampleServiceFindRequest {
	m0 := &ExampleServiceFindRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type ExampleServiceFindByCodeRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Code string                 `protobuf:"bytes,1,opt,name=code,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExampleServiceFindByCodeRequest) Reset() {
	*x = ExampleServiceFindByCodeRequest{}
	mi := &file_example_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleServiceFindByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleServiceFindByCodeRequest) ProtoMessage() {}

func (x *ExampleServiceFindByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExampleServiceFindByCodeRequest) GetCode() string {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return ""
}

func (x *ExampleServiceFindByCodeRequest) SetCode(v string) {
	x.xxx_hidden_Code = v
}

type ExampleServiceFindByCodeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Code string
}

func (b0 ExampleServiceFindByCodeRequest_builder) Build() *ExampleServiceFindByCodeRequest {
	m0 := &ExampleServiceFindByCodeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Code = b.Code
	return m0
}

type ExampleServiceSaveRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance *Test                  `protobuf:"bytes,2,opt,name=instance,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExampleServiceSaveRequest) Reset() {
	*x = ExampleServiceSaveRequest{}
	mi := &file_example_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleServiceSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleServiceSaveRequest) ProtoMessage() {}

func (x *ExampleServiceSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExampleServiceSaveRequest) GetInstance() *Test {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *ExampleServiceSaveRequest) SetInstance(v *Test) {
	x.xxx_hidden_Instance = v
}

func (x *ExampleServiceSaveRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *ExampleServiceSaveRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type ExampleServiceSaveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instance *Test
}

func (b0 ExampleServiceSaveRequest_builder) Build() *ExampleServiceSaveRequest {
	m0 := &ExampleServiceSaveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type ExampleServiceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleServiceDeleteRequest) Reset() {
	*x = ExampleServiceDeleteRequest{}
	mi := &file_example_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleServiceDeleteRequest) ProtoMessage() {}

func (x *ExampleServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExampleServiceDeleteRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *ExampleServiceDeleteRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

type ExampleServiceDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 ExampleServiceDeleteRequest_builder) Build() *ExampleServiceDeleteRequest {
	m0 := &ExampleServiceDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type ExampleServiceInstanceResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance *Test                  `protobuf:"bytes,1,opt,name=instance,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExampleServiceInstanceResponse) Reset() {
	*x = ExampleServiceInstanceResponse{}
	mi := &file_example_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleServiceInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleServiceInstanceResponse) ProtoMessage() {}

func (x *ExampleServiceInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExampleServiceInstanceResponse) GetInstance() *Test {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *ExampleServiceInstanceResponse) SetInstance(v *Test) {
	x.xxx_hidden_Instance = v
}

func (x *ExampleServiceInstanceResponse) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *ExampleServiceInstanceResponse) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type ExampleServiceInstanceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instance *Test
}

func (b0 ExampleServiceInstanceResponse_builder) Build() *ExampleServiceInstanceResponse {
	m0 := &ExampleServiceInstanceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type Test struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Code        string                 `protobuf:"bytes,2,opt,name=code,proto3"`
	xxx_hidden_Name        string                 `protobuf:"bytes,3,opt,name=name,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,4,opt,name=description,proto3"`
	xxx_hidden_CreatedAt   *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_ModifiedAt  *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Test) Reset() {
	*x = Test{}
	mi := &file_example_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_example_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Test) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Test) GetCode() string {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return ""
}

func (x *Test) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Test) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *Test) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Test) GetModifiedAt() *timestamp.Timestamp {
	if x != nil {
		return x.xxx_hidden_ModifiedAt
	}
	return nil
}

func (x *Test) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Test) SetCode(v string) {
	x.xxx_hidden_Code = v
}

func (x *Test) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Test) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *Test) SetCreatedAt(v *timestamp.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Test) SetModifiedAt(v *timestamp.Timestamp) {
	x.xxx_hidden_ModifiedAt = v
}

func (x *Test) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Test) HasModifiedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ModifiedAt != nil
}

func (x *Test) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Test) ClearModifiedAt() {
	x.xxx_hidden_ModifiedAt = nil
}

type Test_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          string
	Code        string
	Name        string
	Description string
	CreatedAt   *timestamp.Timestamp
	ModifiedAt  *timestamp.Timestamp
}

func (b0 Test_builder) Build() *Test {
	m0 := &Test{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Code = b.Code
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_ModifiedAt = b.ModifiedAt
	return m0
}

type ExampleServiceListRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offset uint32                 `protobuf:"varint,1,opt,name=offset,proto3"`
	xxx_hidden_Limit  uint32                 `protobuf:"varint,2,opt,name=limit,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExampleServiceListRequest) Reset() {
	*x = ExampleServiceListRequest{}
	mi := &file_example_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleServiceListRequest) ProtoMessage() {}

func (x *ExampleServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExampleServiceListRequest) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ExampleServiceListRequest) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ExampleServiceListRequest) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
}

func (x *ExampleServiceListRequest) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
}

type ExampleServiceListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Offset uint32
	Limit  uint32
}

func (b0 ExampleServiceListRequest_builder) Build() *ExampleServiceListRequest {
	m0 := &ExampleServiceListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_Limit = b.Limit
	return m0
}

type ExampleServiceInstancesResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offset uint32                 `protobuf:"varint,1,opt,name=offset,proto3"`
	xxx_hidden_Limit  uint32                 `protobuf:"varint,2,opt,name=limit,proto3"`
	xxx_hidden_Data   *[]*Test               `protobuf:"bytes,3,rep,name=data,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExampleServiceInstancesResponse) Reset() {
	*x = ExampleServiceInstancesResponse{}
	mi := &file_example_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleServiceInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleServiceInstancesResponse) ProtoMessage() {}

func (x *ExampleServiceInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExampleServiceInstancesResponse) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ExampleServiceInstancesResponse) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ExampleServiceInstancesResponse) GetData() []*Test {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
	}
	return nil
}

func (x *ExampleServiceInstancesResponse) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
}

func (x *ExampleServiceInstancesResponse) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
}

func (x *ExampleServiceInstancesResponse) SetData(v []*Test) {
	x.xxx_hidden_Data = &v
}

type ExampleServiceInstancesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Offset uint32
	Limit  uint32
	Data   []*Test
}

func (b0 ExampleServiceInstancesResponse_builder) Build() *ExampleServiceInstancesResponse {
	m0 := &ExampleServiceInstancesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Offset = b.Offset
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Data = &b.Data
	return m0
}

var File_example_service_proto protoreflect.FileDescriptor

const file_example_service_proto_rawDesc = "" +
	"\n" +
	"\x15example-service.proto\x12\x0fexample.service\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n" +
	"\x19ExampleServiceFindRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x1fExampleServiceFindByCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"N\n" +
	"\x19ExampleServiceSaveRequest\x121\n" +
	"\binstance\x18\x02 \x01(\v2\x15.example.service.TestR\binstance\"-\n" +
	"\x1bExampleServiceDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x1eExampleServiceInstanceResponse\x121\n" +
	"\binstance\x18\x01 \x01(\v2\x15.example.service.TestR\binstance\"\xd8\x01\n" +
	"\x04Test\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\"I\n" +
	"\x19ExampleServiceListRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"z\n" +
	"\x1fExampleServiceInstancesResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.example.service.TestR\x04data2\x81\x04\n" +
	"\x0eExampleService\x12c\n" +
	"\x04Find\x12*.example.service.ExampleServiceFindRequest\x1a/.example.service.ExampleServiceInstanceResponse\x12o\n" +
	"\n" +
	"FindByCode\x120.example.service.ExampleServiceFindByCodeRequest\x1a/.example.service.ExampleServiceInstanceResponse\x12d\n" +
	"\x04List\x12*.example.service.ExampleServiceListRequest\x1a0.example.service.ExampleServiceInstancesResponse\x12c\n" +
	"\x04Save\x12*.example.service.ExampleServiceSaveRequest\x1a/.example.service.ExampleServiceInstanceResponse\x12N\n" +
	"\x06Delete\x12,.example.service.ExampleServiceDeleteRequest\x1a\x16.google.protobuf.EmptyB*Z(go-service-template/grpc/example-serviceb\x06proto3"

var file_example_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_example_service_proto_goTypes = []any{
	(*ExampleServiceFindRequest)(nil),       // 0: example.service.ExampleServiceFindRequest
	(*ExampleServiceFindByCodeRequest)(nil), // 1: example.service.ExampleServiceFindByCodeRequest
	(*ExampleServiceSaveRequest)(nil),       // 2: example.service.ExampleServiceSaveRequest
	(*ExampleServiceDeleteRequest)(nil),     // 3: example.service.ExampleServiceDeleteRequest
	(*ExampleServiceInstanceResponse)(nil),  // 4: example.service.ExampleServiceInstanceResponse
	(*Test)(nil),                            // 5: example.service.Test
	(*ExampleServiceListRequest)(nil),       // 6: example.service.ExampleServiceListRequest
	(*ExampleServiceInstancesResponse)(nil), // 7: example.service.ExampleServiceInstancesResponse
	(*timestamp.Timestamp)(nil),             // 8: google.protobuf.Timestamp
	(*empty.Empty)(nil),                     // 9: google.protobuf.Empty
}
var file_example_service_proto_depIdxs = []int32{
	5,  // 0: example.service.ExampleServiceSaveRequest.instance:type_name -> example.service.Test
	5,  // 1: example.service.ExampleServiceInstanceResponse.instance:type_name -> example.service.Test
	8,  // 2: example.service.Test.created_at:type_name -> google.protobuf.Timestamp
	8,  // 3: example.service.Test.modified_at:type_name -> google.protobuf.Timestamp
	5,  // 4: example.service.ExampleServiceInstancesResponse.data:type_name -> example.service.Test
	0,  // 5: example.service.ExampleService.Find:input_type -> example.service.ExampleServiceFindRequest
	1,  // 6: example.service.ExampleService.FindByCode:input_type -> example.service.ExampleServiceFindByCodeRequest
	6,  // 7: example.service.ExampleService.List:input_type -> example.service.ExampleServiceListRequest
	2,  // 8: example.service.ExampleService.Save:input_type -> example.service.ExampleServiceSaveRequest
	3,  // 9: example.service.ExampleService.Delete:input_type -> example.service.ExampleServiceDeleteRequest
	4,  // 10: example.service.ExampleService.Find:output_type -> example.service.ExampleServiceInstanceResponse
	4,  // 11: example.service.ExampleService.FindByCode:output_type -> example.service.ExampleServiceInstanceResponse
	7,  // 12: example.service.ExampleService.List:output_type -> example.service.ExampleServiceInstancesResponse
	4,  // 13: example.service.ExampleService.Save:output_type -> example.service.ExampleServiceInstanceResponse
	9,  // 14: example.service.ExampleService.Delete:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_example_service_proto_init() }
func file_example_service_proto_init() {
	if File_example_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_service_proto_rawDesc), len(file_example_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_service_proto_goTypes,
		DependencyIndexes: file_example_service_proto_depIdxs,
		MessageInfos:      file_example_service_proto_msgTypes,
	}.Build()
	File_example_service_proto = out.File
	file_example_service_proto_goTypes = nil
	file_example_service_proto_depIdxs = nil
}
