// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"sync"

	"github.com/ElfAstAhe/go-service-template/pkg/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommonWorker creates a new instance of MockCommonWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommonWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommonWorker {
	mock := &MockCommonWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommonWorker is an autogenerated mock type for the CommonWorker type
type MockCommonWorker struct {
	mock.Mock
}

type MockCommonWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommonWorker) EXPECT() *MockCommonWorker_Expecter {
	return &MockCommonWorker_Expecter{mock: &_m.Mock}
}

// GetContext provides a mock function for the type MockCommonWorker
func (_mock *MockCommonWorker) GetContext() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockCommonWorker_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockCommonWorker_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *MockCommonWorker_Expecter) GetContext() *MockCommonWorker_GetContext_Call {
	return &MockCommonWorker_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *MockCommonWorker_GetContext_Call) Run(run func()) *MockCommonWorker_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommonWorker_GetContext_Call) Return(context1 context.Context) *MockCommonWorker_GetContext_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockCommonWorker_GetContext_Call) RunAndReturn(run func() context.Context) *MockCommonWorker_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetContextCancel provides a mock function for the type MockCommonWorker
func (_mock *MockCommonWorker) GetContextCancel() context.CancelFunc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContextCancel")
	}

	var r0 context.CancelFunc
	if returnFunc, ok := ret.Get(0).(func() context.CancelFunc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.CancelFunc)
		}
	}
	return r0
}

// MockCommonWorker_GetContextCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContextCancel'
type MockCommonWorker_GetContextCancel_Call struct {
	*mock.Call
}

// GetContextCancel is a helper method to define mock.On call
func (_e *MockCommonWorker_Expecter) GetContextCancel() *MockCommonWorker_GetContextCancel_Call {
	return &MockCommonWorker_GetContextCancel_Call{Call: _e.mock.On("GetContextCancel")}
}

func (_c *MockCommonWorker_GetContextCancel_Call) Run(run func()) *MockCommonWorker_GetContextCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommonWorker_GetContextCancel_Call) Return(cancelFunc context.CancelFunc) *MockCommonWorker_GetContextCancel_Call {
	_c.Call.Return(cancelFunc)
	return _c
}

func (_c *MockCommonWorker_GetContextCancel_Call) RunAndReturn(run func() context.CancelFunc) *MockCommonWorker_GetContextCancel_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogger provides a mock function for the type MockCommonWorker
func (_mock *MockCommonWorker) GetLogger() logger.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func() logger.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// MockCommonWorker_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type MockCommonWorker_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *MockCommonWorker_Expecter) GetLogger() *MockCommonWorker_GetLogger_Call {
	return &MockCommonWorker_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *MockCommonWorker_GetLogger_Call) Run(run func()) *MockCommonWorker_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommonWorker_GetLogger_Call) Return(logger1 logger.Logger) *MockCommonWorker_GetLogger_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockCommonWorker_GetLogger_Call) RunAndReturn(run func() logger.Logger) *MockCommonWorker_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockCommonWorker
func (_mock *MockCommonWorker) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommonWorker_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockCommonWorker_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockCommonWorker_Expecter) GetName() *MockCommonWorker_GetName_Call {
	return &MockCommonWorker_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockCommonWorker_GetName_Call) Run(run func()) *MockCommonWorker_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommonWorker_GetName_Call) Return(s string) *MockCommonWorker_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommonWorker_GetName_Call) RunAndReturn(run func() string) *MockCommonWorker_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetWaitGroup provides a mock function for the type MockCommonWorker
func (_mock *MockCommonWorker) GetWaitGroup() *sync.WaitGroup {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWaitGroup")
	}

	var r0 *sync.WaitGroup
	if returnFunc, ok := ret.Get(0).(func() *sync.WaitGroup); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sync.WaitGroup)
		}
	}
	return r0
}

// MockCommonWorker_GetWaitGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWaitGroup'
type MockCommonWorker_GetWaitGroup_Call struct {
	*mock.Call
}

// GetWaitGroup is a helper method to define mock.On call
func (_e *MockCommonWorker_Expecter) GetWaitGroup() *MockCommonWorker_GetWaitGroup_Call {
	return &MockCommonWorker_GetWaitGroup_Call{Call: _e.mock.On("GetWaitGroup")}
}

func (_c *MockCommonWorker_GetWaitGroup_Call) Run(run func()) *MockCommonWorker_GetWaitGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommonWorker_GetWaitGroup_Call) Return(waitGroup *sync.WaitGroup) *MockCommonWorker_GetWaitGroup_Call {
	_c.Call.Return(waitGroup)
	return _c
}

func (_c *MockCommonWorker_GetWaitGroup_Call) RunAndReturn(run func() *sync.WaitGroup) *MockCommonWorker_GetWaitGroup_Call {
	_c.Call.Return(run)
	return _c
}

// IsRunning provides a mock function for the type MockCommonWorker
func (_mock *MockCommonWorker) IsRunning() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCommonWorker_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type MockCommonWorker_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
func (_e *MockCommonWorker_Expecter) IsRunning() *MockCommonWorker_IsRunning_Call {
	return &MockCommonWorker_IsRunning_Call{Call: _e.mock.On("IsRunning")}
}

func (_c *MockCommonWorker_IsRunning_Call) Run(run func()) *MockCommonWorker_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommonWorker_IsRunning_Call) Return(b bool) *MockCommonWorker_IsRunning_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCommonWorker_IsRunning_Call) RunAndReturn(run func() bool) *MockCommonWorker_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockCommonWorker
func (_mock *MockCommonWorker) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommonWorker_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCommonWorker_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCommonWorker_Expecter) Start(ctx interface{}) *MockCommonWorker_Start_Call {
	return &MockCommonWorker_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockCommonWorker_Start_Call) Run(run func(ctx context.Context)) *MockCommonWorker_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommonWorker_Start_Call) Return(err error) *MockCommonWorker_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommonWorker_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockCommonWorker_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockCommonWorker
func (_mock *MockCommonWorker) Stop(stopCtx context.Context) error {
	ret := _mock.Called(stopCtx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(stopCtx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommonWorker_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockCommonWorker_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - stopCtx context.Context
func (_e *MockCommonWorker_Expecter) Stop(stopCtx interface{}) *MockCommonWorker_Stop_Call {
	return &MockCommonWorker_Stop_Call{Call: _e.mock.On("Stop", stopCtx)}
}

func (_c *MockCommonWorker_Stop_Call) Run(run func(stopCtx context.Context)) *MockCommonWorker_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommonWorker_Stop_Call) Return(err error) *MockCommonWorker_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommonWorker_Stop_Call) RunAndReturn(run func(stopCtx context.Context) error) *MockCommonWorker_Stop_Call {
	_c.Call.Return(run)
	return _c
}
