// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeys creates a new instance of MockKeys. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeys[Priv any, Pub any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeys[Priv, Pub] {
	mock := &MockKeys[Priv, Pub]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeys is an autogenerated mock type for the Keys type
type MockKeys[Priv any, Pub any] struct {
	mock.Mock
}

type MockKeys_Expecter[Priv any, Pub any] struct {
	mock *mock.Mock
}

func (_m *MockKeys[Priv, Pub]) EXPECT() *MockKeys_Expecter[Priv, Pub] {
	return &MockKeys_Expecter[Priv, Pub]{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockKeys
func (_mock *MockKeys[Priv, Pub]) Decrypt(data []byte, privateKey Priv) ([]byte, error) {
	ret := _mock.Called(data, privateKey)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, Priv) ([]byte, error)); ok {
		return returnFunc(data, privateKey)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, Priv) []byte); ok {
		r0 = returnFunc(data, privateKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, Priv) error); ok {
		r1 = returnFunc(data, privateKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeys_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockKeys_Decrypt_Call[Priv any, Pub any] struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - data []byte
//   - privateKey Priv
func (_e *MockKeys_Expecter[Priv, Pub]) Decrypt(data interface{}, privateKey interface{}) *MockKeys_Decrypt_Call[Priv, Pub] {
	return &MockKeys_Decrypt_Call[Priv, Pub]{Call: _e.mock.On("Decrypt", data, privateKey)}
}

func (_c *MockKeys_Decrypt_Call[Priv, Pub]) Run(run func(data []byte, privateKey Priv)) *MockKeys_Decrypt_Call[Priv, Pub] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 Priv
		if args[1] != nil {
			arg1 = args[1].(Priv)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeys_Decrypt_Call[Priv, Pub]) Return(bytes []byte, err error) *MockKeys_Decrypt_Call[Priv, Pub] {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKeys_Decrypt_Call[Priv, Pub]) RunAndReturn(run func(data []byte, privateKey Priv) ([]byte, error)) *MockKeys_Decrypt_Call[Priv, Pub] {
	_c.Call.Return(run)
	return _c
}

// DecryptString provides a mock function for the type MockKeys
func (_mock *MockKeys[Priv, Pub]) DecryptString(data string, privateKey Priv) (string, error) {
	ret := _mock.Called(data, privateKey)

	if len(ret) == 0 {
		panic("no return value specified for DecryptString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, Priv) (string, error)); ok {
		return returnFunc(data, privateKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string, Priv) string); ok {
		r0 = returnFunc(data, privateKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, Priv) error); ok {
		r1 = returnFunc(data, privateKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeys_DecryptString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptString'
type MockKeys_DecryptString_Call[Priv any, Pub any] struct {
	*mock.Call
}

// DecryptString is a helper method to define mock.On call
//   - data string
//   - privateKey Priv
func (_e *MockKeys_Expecter[Priv, Pub]) DecryptString(data interface{}, privateKey interface{}) *MockKeys_DecryptString_Call[Priv, Pub] {
	return &MockKeys_DecryptString_Call[Priv, Pub]{Call: _e.mock.On("DecryptString", data, privateKey)}
}

func (_c *MockKeys_DecryptString_Call[Priv, Pub]) Run(run func(data string, privateKey Priv)) *MockKeys_DecryptString_Call[Priv, Pub] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 Priv
		if args[1] != nil {
			arg1 = args[1].(Priv)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeys_DecryptString_Call[Priv, Pub]) Return(s string, err error) *MockKeys_DecryptString_Call[Priv, Pub] {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockKeys_DecryptString_Call[Priv, Pub]) RunAndReturn(run func(data string, privateKey Priv) (string, error)) *MockKeys_DecryptString_Call[Priv, Pub] {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockKeys
func (_mock *MockKeys[Priv, Pub]) Encrypt(data []byte, publicKey Pub) ([]byte, error) {
	ret := _mock.Called(data, publicKey)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, Pub) ([]byte, error)); ok {
		return returnFunc(data, publicKey)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, Pub) []byte); ok {
		r0 = returnFunc(data, publicKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, Pub) error); ok {
		r1 = returnFunc(data, publicKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeys_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockKeys_Encrypt_Call[Priv any, Pub any] struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - data []byte
//   - publicKey Pub
func (_e *MockKeys_Expecter[Priv, Pub]) Encrypt(data interface{}, publicKey interface{}) *MockKeys_Encrypt_Call[Priv, Pub] {
	return &MockKeys_Encrypt_Call[Priv, Pub]{Call: _e.mock.On("Encrypt", data, publicKey)}
}

func (_c *MockKeys_Encrypt_Call[Priv, Pub]) Run(run func(data []byte, publicKey Pub)) *MockKeys_Encrypt_Call[Priv, Pub] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 Pub
		if args[1] != nil {
			arg1 = args[1].(Pub)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeys_Encrypt_Call[Priv, Pub]) Return(bytes []byte, err error) *MockKeys_Encrypt_Call[Priv, Pub] {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKeys_Encrypt_Call[Priv, Pub]) RunAndReturn(run func(data []byte, publicKey Pub) ([]byte, error)) *MockKeys_Encrypt_Call[Priv, Pub] {
	_c.Call.Return(run)
	return _c
}

// EncryptString provides a mock function for the type MockKeys
func (_mock *MockKeys[Priv, Pub]) EncryptString(data string, publicKey Pub) (string, error) {
	ret := _mock.Called(data, publicKey)

	if len(ret) == 0 {
		panic("no return value specified for EncryptString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, Pub) (string, error)); ok {
		return returnFunc(data, publicKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string, Pub) string); ok {
		r0 = returnFunc(data, publicKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, Pub) error); ok {
		r1 = returnFunc(data, publicKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeys_EncryptString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptString'
type MockKeys_EncryptString_Call[Priv any, Pub any] struct {
	*mock.Call
}

// EncryptString is a helper method to define mock.On call
//   - data string
//   - publicKey Pub
func (_e *MockKeys_Expecter[Priv, Pub]) EncryptString(data interface{}, publicKey interface{}) *MockKeys_EncryptString_Call[Priv, Pub] {
	return &MockKeys_EncryptString_Call[Priv, Pub]{Call: _e.mock.On("EncryptString", data, publicKey)}
}

func (_c *MockKeys_EncryptString_Call[Priv, Pub]) Run(run func(data string, publicKey Pub)) *MockKeys_EncryptString_Call[Priv, Pub] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 Pub
		if args[1] != nil {
			arg1 = args[1].(Pub)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeys_EncryptString_Call[Priv, Pub]) Return(s string, err error) *MockKeys_EncryptString_Call[Priv, Pub] {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockKeys_EncryptString_Call[Priv, Pub]) RunAndReturn(run func(data string, publicKey Pub) (string, error)) *MockKeys_EncryptString_Call[Priv, Pub] {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function for the type MockKeys
func (_mock *MockKeys[Priv, Pub]) Generate() (string, string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockKeys_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockKeys_Generate_Call[Priv any, Pub any] struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockKeys_Expecter[Priv, Pub]) Generate() *MockKeys_Generate_Call[Priv, Pub] {
	return &MockKeys_Generate_Call[Priv, Pub]{Call: _e.mock.On("Generate")}
}

func (_c *MockKeys_Generate_Call[Priv, Pub]) Run(run func()) *MockKeys_Generate_Call[Priv, Pub] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeys_Generate_Call[Priv, Pub]) Return(s string, s1 string, err error) *MockKeys_Generate_Call[Priv, Pub] {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockKeys_Generate_Call[Priv, Pub]) RunAndReturn(run func() (string, string, error)) *MockKeys_Generate_Call[Priv, Pub] {
	_c.Call.Return(run)
	return _c
}

// ParsePrivateKey provides a mock function for the type MockKeys
func (_mock *MockKeys[Priv, Pub]) ParsePrivateKey(s string) (Priv, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ParsePrivateKey")
	}

	var r0 Priv
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Priv, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Priv); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Priv)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeys_ParsePrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParsePrivateKey'
type MockKeys_ParsePrivateKey_Call[Priv any, Pub any] struct {
	*mock.Call
}

// ParsePrivateKey is a helper method to define mock.On call
//   - s string
func (_e *MockKeys_Expecter[Priv, Pub]) ParsePrivateKey(s interface{}) *MockKeys_ParsePrivateKey_Call[Priv, Pub] {
	return &MockKeys_ParsePrivateKey_Call[Priv, Pub]{Call: _e.mock.On("ParsePrivateKey", s)}
}

func (_c *MockKeys_ParsePrivateKey_Call[Priv, Pub]) Run(run func(s string)) *MockKeys_ParsePrivateKey_Call[Priv, Pub] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeys_ParsePrivateKey_Call[Priv, Pub]) Return(v Priv, err error) *MockKeys_ParsePrivateKey_Call[Priv, Pub] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockKeys_ParsePrivateKey_Call[Priv, Pub]) RunAndReturn(run func(s string) (Priv, error)) *MockKeys_ParsePrivateKey_Call[Priv, Pub] {
	_c.Call.Return(run)
	return _c
}

// ParsePublicKey provides a mock function for the type MockKeys
func (_mock *MockKeys[Priv, Pub]) ParsePublicKey(s string) (Pub, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ParsePublicKey")
	}

	var r0 Pub
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Pub, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Pub); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Pub)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeys_ParsePublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParsePublicKey'
type MockKeys_ParsePublicKey_Call[Priv any, Pub any] struct {
	*mock.Call
}

// ParsePublicKey is a helper method to define mock.On call
//   - s string
func (_e *MockKeys_Expecter[Priv, Pub]) ParsePublicKey(s interface{}) *MockKeys_ParsePublicKey_Call[Priv, Pub] {
	return &MockKeys_ParsePublicKey_Call[Priv, Pub]{Call: _e.mock.On("ParsePublicKey", s)}
}

func (_c *MockKeys_ParsePublicKey_Call[Priv, Pub]) Run(run func(s string)) *MockKeys_ParsePublicKey_Call[Priv, Pub] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeys_ParsePublicKey_Call[Priv, Pub]) Return(v Pub, err error) *MockKeys_ParsePublicKey_Call[Priv, Pub] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockKeys_ParsePublicKey_Call[Priv, Pub]) RunAndReturn(run func(s string) (Pub, error)) *MockKeys_ParsePublicKey_Call[Priv, Pub] {
	_c.Call.Return(run)
	return _c
}
