// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"crypto/rsa"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRSAKeys creates a new instance of MockRSAKeys. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRSAKeys(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRSAKeys {
	mock := &MockRSAKeys{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRSAKeys is an autogenerated mock type for the RSAKeys type
type MockRSAKeys struct {
	mock.Mock
}

type MockRSAKeys_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRSAKeys) EXPECT() *MockRSAKeys_Expecter {
	return &MockRSAKeys_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockRSAKeys
func (_mock *MockRSAKeys) Decrypt(data []byte, privateKey *rsa.PrivateKey) ([]byte, error) {
	ret := _mock.Called(data, privateKey)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, *rsa.PrivateKey) ([]byte, error)); ok {
		return returnFunc(data, privateKey)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, *rsa.PrivateKey) []byte); ok {
		r0 = returnFunc(data, privateKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, *rsa.PrivateKey) error); ok {
		r1 = returnFunc(data, privateKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRSAKeys_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockRSAKeys_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - data []byte
//   - privateKey *rsa.PrivateKey
func (_e *MockRSAKeys_Expecter) Decrypt(data interface{}, privateKey interface{}) *MockRSAKeys_Decrypt_Call {
	return &MockRSAKeys_Decrypt_Call{Call: _e.mock.On("Decrypt", data, privateKey)}
}

func (_c *MockRSAKeys_Decrypt_Call) Run(run func(data []byte, privateKey *rsa.PrivateKey)) *MockRSAKeys_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 *rsa.PrivateKey
		if args[1] != nil {
			arg1 = args[1].(*rsa.PrivateKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRSAKeys_Decrypt_Call) Return(bytes []byte, err error) *MockRSAKeys_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRSAKeys_Decrypt_Call) RunAndReturn(run func(data []byte, privateKey *rsa.PrivateKey) ([]byte, error)) *MockRSAKeys_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptString provides a mock function for the type MockRSAKeys
func (_mock *MockRSAKeys) DecryptString(data string, privateKey *rsa.PrivateKey) (string, error) {
	ret := _mock.Called(data, privateKey)

	if len(ret) == 0 {
		panic("no return value specified for DecryptString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *rsa.PrivateKey) (string, error)); ok {
		return returnFunc(data, privateKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *rsa.PrivateKey) string); ok {
		r0 = returnFunc(data, privateKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *rsa.PrivateKey) error); ok {
		r1 = returnFunc(data, privateKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRSAKeys_DecryptString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptString'
type MockRSAKeys_DecryptString_Call struct {
	*mock.Call
}

// DecryptString is a helper method to define mock.On call
//   - data string
//   - privateKey *rsa.PrivateKey
func (_e *MockRSAKeys_Expecter) DecryptString(data interface{}, privateKey interface{}) *MockRSAKeys_DecryptString_Call {
	return &MockRSAKeys_DecryptString_Call{Call: _e.mock.On("DecryptString", data, privateKey)}
}

func (_c *MockRSAKeys_DecryptString_Call) Run(run func(data string, privateKey *rsa.PrivateKey)) *MockRSAKeys_DecryptString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *rsa.PrivateKey
		if args[1] != nil {
			arg1 = args[1].(*rsa.PrivateKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRSAKeys_DecryptString_Call) Return(s string, err error) *MockRSAKeys_DecryptString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRSAKeys_DecryptString_Call) RunAndReturn(run func(data string, privateKey *rsa.PrivateKey) (string, error)) *MockRSAKeys_DecryptString_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockRSAKeys
func (_mock *MockRSAKeys) Encrypt(data []byte, publicKey *rsa.PublicKey) ([]byte, error) {
	ret := _mock.Called(data, publicKey)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, *rsa.PublicKey) ([]byte, error)); ok {
		return returnFunc(data, publicKey)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, *rsa.PublicKey) []byte); ok {
		r0 = returnFunc(data, publicKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, *rsa.PublicKey) error); ok {
		r1 = returnFunc(data, publicKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRSAKeys_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockRSAKeys_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - data []byte
//   - publicKey *rsa.PublicKey
func (_e *MockRSAKeys_Expecter) Encrypt(data interface{}, publicKey interface{}) *MockRSAKeys_Encrypt_Call {
	return &MockRSAKeys_Encrypt_Call{Call: _e.mock.On("Encrypt", data, publicKey)}
}

func (_c *MockRSAKeys_Encrypt_Call) Run(run func(data []byte, publicKey *rsa.PublicKey)) *MockRSAKeys_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 *rsa.PublicKey
		if args[1] != nil {
			arg1 = args[1].(*rsa.PublicKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRSAKeys_Encrypt_Call) Return(bytes []byte, err error) *MockRSAKeys_Encrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRSAKeys_Encrypt_Call) RunAndReturn(run func(data []byte, publicKey *rsa.PublicKey) ([]byte, error)) *MockRSAKeys_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptString provides a mock function for the type MockRSAKeys
func (_mock *MockRSAKeys) EncryptString(data string, publicKey *rsa.PublicKey) (string, error) {
	ret := _mock.Called(data, publicKey)

	if len(ret) == 0 {
		panic("no return value specified for EncryptString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *rsa.PublicKey) (string, error)); ok {
		return returnFunc(data, publicKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *rsa.PublicKey) string); ok {
		r0 = returnFunc(data, publicKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *rsa.PublicKey) error); ok {
		r1 = returnFunc(data, publicKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRSAKeys_EncryptString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptString'
type MockRSAKeys_EncryptString_Call struct {
	*mock.Call
}

// EncryptString is a helper method to define mock.On call
//   - data string
//   - publicKey *rsa.PublicKey
func (_e *MockRSAKeys_Expecter) EncryptString(data interface{}, publicKey interface{}) *MockRSAKeys_EncryptString_Call {
	return &MockRSAKeys_EncryptString_Call{Call: _e.mock.On("EncryptString", data, publicKey)}
}

func (_c *MockRSAKeys_EncryptString_Call) Run(run func(data string, publicKey *rsa.PublicKey)) *MockRSAKeys_EncryptString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *rsa.PublicKey
		if args[1] != nil {
			arg1 = args[1].(*rsa.PublicKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRSAKeys_EncryptString_Call) Return(s string, err error) *MockRSAKeys_EncryptString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRSAKeys_EncryptString_Call) RunAndReturn(run func(data string, publicKey *rsa.PublicKey) (string, error)) *MockRSAKeys_EncryptString_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function for the type MockRSAKeys
func (_mock *MockRSAKeys) Generate() (string, string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRSAKeys_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockRSAKeys_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockRSAKeys_Expecter) Generate() *MockRSAKeys_Generate_Call {
	return &MockRSAKeys_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockRSAKeys_Generate_Call) Run(run func()) *MockRSAKeys_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRSAKeys_Generate_Call) Return(s string, s1 string, err error) *MockRSAKeys_Generate_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockRSAKeys_Generate_Call) RunAndReturn(run func() (string, string, error)) *MockRSAKeys_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// ParsePrivateKey provides a mock function for the type MockRSAKeys
func (_mock *MockRSAKeys) ParsePrivateKey(s string) (*rsa.PrivateKey, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ParsePrivateKey")
	}

	var r0 *rsa.PrivateKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*rsa.PrivateKey, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *rsa.PrivateKey); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PrivateKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRSAKeys_ParsePrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParsePrivateKey'
type MockRSAKeys_ParsePrivateKey_Call struct {
	*mock.Call
}

// ParsePrivateKey is a helper method to define mock.On call
//   - s string
func (_e *MockRSAKeys_Expecter) ParsePrivateKey(s interface{}) *MockRSAKeys_ParsePrivateKey_Call {
	return &MockRSAKeys_ParsePrivateKey_Call{Call: _e.mock.On("ParsePrivateKey", s)}
}

func (_c *MockRSAKeys_ParsePrivateKey_Call) Run(run func(s string)) *MockRSAKeys_ParsePrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRSAKeys_ParsePrivateKey_Call) Return(privateKey *rsa.PrivateKey, err error) *MockRSAKeys_ParsePrivateKey_Call {
	_c.Call.Return(privateKey, err)
	return _c
}

func (_c *MockRSAKeys_ParsePrivateKey_Call) RunAndReturn(run func(s string) (*rsa.PrivateKey, error)) *MockRSAKeys_ParsePrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

// ParsePublicKey provides a mock function for the type MockRSAKeys
func (_mock *MockRSAKeys) ParsePublicKey(s string) (*rsa.PublicKey, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for ParsePublicKey")
	}

	var r0 *rsa.PublicKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*rsa.PublicKey, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *rsa.PublicKey); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PublicKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRSAKeys_ParsePublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParsePublicKey'
type MockRSAKeys_ParsePublicKey_Call struct {
	*mock.Call
}

// ParsePublicKey is a helper method to define mock.On call
//   - s string
func (_e *MockRSAKeys_Expecter) ParsePublicKey(s interface{}) *MockRSAKeys_ParsePublicKey_Call {
	return &MockRSAKeys_ParsePublicKey_Call{Call: _e.mock.On("ParsePublicKey", s)}
}

func (_c *MockRSAKeys_ParsePublicKey_Call) Run(run func(s string)) *MockRSAKeys_ParsePublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRSAKeys_ParsePublicKey_Call) Return(publicKey *rsa.PublicKey, err error) *MockRSAKeys_ParsePublicKey_Call {
	_c.Call.Return(publicKey, err)
	return _c
}

func (_c *MockRSAKeys_ParsePublicKey_Call) RunAndReturn(run func(s string) (*rsa.PublicKey, error)) *MockRSAKeys_ParsePublicKey_Call {
	_c.Call.Return(run)
	return _c
}
