package main

import (
	"archive/zip"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

func main() {
	goRoot := runtime.GOROOT()
	if goRoot == "" {
		fmt.Println("Error: GOROOT is not set")
		os.Exit(1)
	}

	zipPath := filepath.Join(goRoot, "lib", "time", "zoneinfo.zip")
	zipBytes, err := os.ReadFile(zipPath)
	if err != nil {
		fmt.Printf("Error read zoneinfo.zip: %v\n", err)
		os.Exit(1)
	}

	reader, err := zip.NewReader(bytes.NewReader(zipBytes), int64(len(zipBytes)))
	if err != nil {
		fmt.Printf("Error parse zoneinfo: %v\n", err)
		os.Exit(1)
	}

	var zones []string
	for _, file := range reader.File {
		name := file.Name
		if file.FileInfo().IsDir() ||
			name == "zone.tab" ||
			name == "iso3166.tab" ||
			name == "security" ||
			strings.HasPrefix(name, "Etc/") ||
			strings.HasPrefix(name, "SystemV/") {
			continue
		}
		zones = append(zones, name)
	}
	sort.Strings(zones)

	// Формируем контент автогенерируемого файла
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen-tz; DO NOT EDIT.\n")
	buf.WriteString("package utils\n\n")
	buf.WriteString("func buildEmbeddedTimeZones() []string {\n")
	buf.WriteString("\treturn []string{\n")
	for _, z := range zones {
		buf.WriteString(fmt.Sprintf("\t\t%q,\n", z))
	}
	buf.WriteString("\t}\n")
	buf.WriteString("}\n")

	// Путь сохранения: теперь пишем относительно корня проекта в нужный пакет
	targetPath := filepath.Join("pkg", "utils", "time_zones_data.go")

	err = os.WriteFile(targetPath, buf.Bytes(), 0644)
	if err != nil {
		fmt.Printf("Error write file to %s: %v\n", targetPath, err)
		os.Exit(1)
	}
	fmt.Println("Successfully generated time_zones_data.go")
}
