// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCipher creates a new instance of MockCipher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCipher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCipher {
	mock := &MockCipher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCipher is an autogenerated mock type for the Cipher type
type MockCipher struct {
	mock.Mock
}

type MockCipher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCipher) EXPECT() *MockCipher_Expecter {
	return &MockCipher_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type MockCipher
func (_mock *MockCipher) Decrypt(bytes []byte) ([]byte, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(bytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCipher_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockCipher_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - bytes []byte
func (_e *MockCipher_Expecter) Decrypt(bytes interface{}) *MockCipher_Decrypt_Call {
	return &MockCipher_Decrypt_Call{Call: _e.mock.On("Decrypt", bytes)}
}

func (_c *MockCipher_Decrypt_Call) Run(run func(bytes []byte)) *MockCipher_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCipher_Decrypt_Call) Return(bytes1 []byte, err error) *MockCipher_Decrypt_Call {
	_c.Call.Return(bytes1, err)
	return _c
}

func (_c *MockCipher_Decrypt_Call) RunAndReturn(run func(bytes []byte) ([]byte, error)) *MockCipher_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// DecryptString provides a mock function for the type MockCipher
func (_mock *MockCipher) DecryptString(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for DecryptString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCipher_DecryptString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptString'
type MockCipher_DecryptString_Call struct {
	*mock.Call
}

// DecryptString is a helper method to define mock.On call
//   - s string
func (_e *MockCipher_Expecter) DecryptString(s interface{}) *MockCipher_DecryptString_Call {
	return &MockCipher_DecryptString_Call{Call: _e.mock.On("DecryptString", s)}
}

func (_c *MockCipher_DecryptString_Call) Run(run func(s string)) *MockCipher_DecryptString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCipher_DecryptString_Call) Return(s1 string, err error) *MockCipher_DecryptString_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockCipher_DecryptString_Call) RunAndReturn(run func(s string) (string, error)) *MockCipher_DecryptString_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockCipher
func (_mock *MockCipher) Encrypt(bytes []byte) ([]byte, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(bytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCipher_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockCipher_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - bytes []byte
func (_e *MockCipher_Expecter) Encrypt(bytes interface{}) *MockCipher_Encrypt_Call {
	return &MockCipher_Encrypt_Call{Call: _e.mock.On("Encrypt", bytes)}
}

func (_c *MockCipher_Encrypt_Call) Run(run func(bytes []byte)) *MockCipher_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCipher_Encrypt_Call) Return(bytes1 []byte, err error) *MockCipher_Encrypt_Call {
	_c.Call.Return(bytes1, err)
	return _c
}

func (_c *MockCipher_Encrypt_Call) RunAndReturn(run func(bytes []byte) ([]byte, error)) *MockCipher_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptString provides a mock function for the type MockCipher
func (_mock *MockCipher) EncryptString(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for EncryptString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCipher_EncryptString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptString'
type MockCipher_EncryptString_Call struct {
	*mock.Call
}

// EncryptString is a helper method to define mock.On call
//   - s string
func (_e *MockCipher_Expecter) EncryptString(s interface{}) *MockCipher_EncryptString_Call {
	return &MockCipher_EncryptString_Call{Call: _e.mock.On("EncryptString", s)}
}

func (_c *MockCipher_EncryptString_Call) Run(run func(s string)) *MockCipher_EncryptString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCipher_EncryptString_Call) Return(s1 string, err error) *MockCipher_EncryptString_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockCipher_EncryptString_Call) RunAndReturn(run func(s string) (string, error)) *MockCipher_EncryptString_Call {
	_c.Call.Return(run)
	return _c
}
