// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockObserver creates a new instance of MockObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObserver[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObserver[T] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockObserver[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockObserver is an autogenerated mock type for the Observer type
type MockObserver[T any] struct {
	mock.Mock
}

type MockObserver_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockObserver[T]) EXPECT() *MockObserver_Expecter[T] {
	return &MockObserver_Expecter[T]{mock: &_m.Mock}
}

// GetName provides a mock function for the type MockObserver
func (_mock *MockObserver[T]) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockObserver_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockObserver_GetName_Call[T any] struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockObserver_Expecter[T]) GetName() *MockObserver_GetName_Call[T] {
	return &MockObserver_GetName_Call[T]{Call: _e.mock.On("GetName")}
}

func (_c *MockObserver_GetName_Call[T]) Run(run func()) *MockObserver_GetName_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObserver_GetName_Call[T]) Return(s string) *MockObserver_GetName_Call[T] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockObserver_GetName_Call[T]) RunAndReturn(run func() string) *MockObserver_GetName_Call[T] {
	_c.Call.Return(run)
	return _c
}

// OnNotify provides a mock function for the type MockObserver
func (_mock *MockObserver[T]) OnNotify(ctx context.Context, event T) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for OnNotify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObserver_OnNotify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnNotify'
type MockObserver_OnNotify_Call[T any] struct {
	*mock.Call
}

// OnNotify is a helper method to define mock.On call
//   - ctx context.Context
//   - event T
func (_e *MockObserver_Expecter[T]) OnNotify(ctx any, event any) *MockObserver_OnNotify_Call[T] {
	return &MockObserver_OnNotify_Call[T]{Call: _e.mock.On("OnNotify", ctx, event)}
}

func (_c *MockObserver_OnNotify_Call[T]) Run(run func(ctx context.Context, event T)) *MockObserver_OnNotify_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObserver_OnNotify_Call[T]) Return(err error) *MockObserver_OnNotify_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObserver_OnNotify_Call[T]) RunAndReturn(run func(ctx context.Context, event T) error) *MockObserver_OnNotify_Call[T] {
	_c.Call.Return(run)
	return _c
}
