// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRouter creates a new instance of MockRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouter {
	mock := &MockRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRouter is an autogenerated mock type for the Router type
type MockRouter struct {
	mock.Mock
}

type MockRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRouter) EXPECT() *MockRouter_Expecter {
	return &MockRouter_Expecter{mock: &_m.Mock}
}

// GetRouter provides a mock function for the type MockRouter
func (_mock *MockRouter) GetRouter() http.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRouter")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func() http.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// MockRouter_GetRouter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRouter'
type MockRouter_GetRouter_Call struct {
	*mock.Call
}

// GetRouter is a helper method to define mock.On call
func (_e *MockRouter_Expecter) GetRouter() *MockRouter_GetRouter_Call {
	return &MockRouter_GetRouter_Call{Call: _e.mock.On("GetRouter")}
}

func (_c *MockRouter_GetRouter_Call) Run(run func()) *MockRouter_GetRouter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRouter_GetRouter_Call) Return(handler http.Handler) *MockRouter_GetRouter_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockRouter_GetRouter_Call) RunAndReturn(run func() http.Handler) *MockRouter_GetRouter_Call {
	_c.Call.Return(run)
	return _c
}
