// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/segmentio/kafka-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSenderLink creates a new instance of MockSenderLink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSenderLink(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSenderLink {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSenderLink{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSenderLink is an autogenerated mock type for the SenderLink type
type MockSenderLink struct {
	mock.Mock
}

type MockSenderLink_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSenderLink) EXPECT() *MockSenderLink_Expecter {
	return &MockSenderLink_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockSenderLink
func (_mock *MockSenderLink) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSenderLink_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSenderLink_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSenderLink_Expecter) Close() *MockSenderLink_Close_Call {
	return &MockSenderLink_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSenderLink_Close_Call) Run(run func()) *MockSenderLink_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSenderLink_Close_Call) Return(err error) *MockSenderLink_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSenderLink_Close_Call) RunAndReturn(run func() error) *MockSenderLink_Close_Call {
	_c.Call.Return(run)
	return _c
}

// WriteMessages provides a mock function for the type MockSenderLink
func (_mock *MockSenderLink) WriteMessages(ctx context.Context, msgs ...kafka.Message) error {
	var tmpRet mock.Arguments
	if len(msgs) > 0 {
		tmpRet = _mock.Called(ctx, msgs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WriteMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...kafka.Message) error); ok {
		r0 = returnFunc(ctx, msgs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSenderLink_WriteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMessages'
type MockSenderLink_WriteMessages_Call struct {
	*mock.Call
}

// WriteMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs ...kafka.Message
func (_e *MockSenderLink_Expecter) WriteMessages(ctx any, msgs ...any) *MockSenderLink_WriteMessages_Call {
	return &MockSenderLink_WriteMessages_Call{Call: _e.mock.On("WriteMessages",
		append([]any{ctx}, msgs...)...)}
}

func (_c *MockSenderLink_WriteMessages_Call) Run(run func(ctx context.Context, msgs ...kafka.Message)) *MockSenderLink_WriteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []kafka.Message
		var variadicArgs []kafka.Message
		if len(args) > 1 {
			variadicArgs = args[1].([]kafka.Message)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockSenderLink_WriteMessages_Call) Return(err error) *MockSenderLink_WriteMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSenderLink_WriteMessages_Call) RunAndReturn(run func(ctx context.Context, msgs ...kafka.Message) error) *MockSenderLink_WriteMessages_Call {
	_c.Call.Return(run)
	return _c
}
