// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/segmentio/kafka-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKafkaReceiverLink creates a new instance of MockKafkaReceiverLink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaReceiverLink(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaReceiverLink {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockKafkaReceiverLink{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockKafkaReceiverLink is an autogenerated mock type for the KafkaReceiverLink type
type MockKafkaReceiverLink struct {
	mock.Mock
}

type MockKafkaReceiverLink_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKafkaReceiverLink) EXPECT() *MockKafkaReceiverLink_Expecter {
	return &MockKafkaReceiverLink_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockKafkaReceiverLink
func (_mock *MockKafkaReceiverLink) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKafkaReceiverLink_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockKafkaReceiverLink_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockKafkaReceiverLink_Expecter) Close() *MockKafkaReceiverLink_Close_Call {
	return &MockKafkaReceiverLink_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockKafkaReceiverLink_Close_Call) Run(run func()) *MockKafkaReceiverLink_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKafkaReceiverLink_Close_Call) Return(err error) *MockKafkaReceiverLink_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKafkaReceiverLink_Close_Call) RunAndReturn(run func() error) *MockKafkaReceiverLink_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CommitMessages provides a mock function for the type MockKafkaReceiverLink
func (_mock *MockKafkaReceiverLink) CommitMessages(ctx context.Context, msgs ...kafka.Message) error {
	var tmpRet mock.Arguments
	if len(msgs) > 0 {
		tmpRet = _mock.Called(ctx, msgs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CommitMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...kafka.Message) error); ok {
		r0 = returnFunc(ctx, msgs...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKafkaReceiverLink_CommitMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitMessages'
type MockKafkaReceiverLink_CommitMessages_Call struct {
	*mock.Call
}

// CommitMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs ...kafka.Message
func (_e *MockKafkaReceiverLink_Expecter) CommitMessages(ctx any, msgs ...any) *MockKafkaReceiverLink_CommitMessages_Call {
	return &MockKafkaReceiverLink_CommitMessages_Call{Call: _e.mock.On("CommitMessages",
		append([]any{ctx}, msgs...)...)}
}

func (_c *MockKafkaReceiverLink_CommitMessages_Call) Run(run func(ctx context.Context, msgs ...kafka.Message)) *MockKafkaReceiverLink_CommitMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []kafka.Message
		var variadicArgs []kafka.Message
		if len(args) > 1 {
			variadicArgs = args[1].([]kafka.Message)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockKafkaReceiverLink_CommitMessages_Call) Return(err error) *MockKafkaReceiverLink_CommitMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKafkaReceiverLink_CommitMessages_Call) RunAndReturn(run func(ctx context.Context, msgs ...kafka.Message) error) *MockKafkaReceiverLink_CommitMessages_Call {
	_c.Call.Return(run)
	return _c
}

// FetchMessage provides a mock function for the type MockKafkaReceiverLink
func (_mock *MockKafkaReceiverLink) FetchMessage(ctx context.Context) (kafka.Message, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchMessage")
	}

	var r0 kafka.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (kafka.Message, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) kafka.Message); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(kafka.Message)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKafkaReceiverLink_FetchMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMessage'
type MockKafkaReceiverLink_FetchMessage_Call struct {
	*mock.Call
}

// FetchMessage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKafkaReceiverLink_Expecter) FetchMessage(ctx any) *MockKafkaReceiverLink_FetchMessage_Call {
	return &MockKafkaReceiverLink_FetchMessage_Call{Call: _e.mock.On("FetchMessage", ctx)}
}

func (_c *MockKafkaReceiverLink_FetchMessage_Call) Run(run func(ctx context.Context)) *MockKafkaReceiverLink_FetchMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKafkaReceiverLink_FetchMessage_Call) Return(message kafka.Message, err error) *MockKafkaReceiverLink_FetchMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockKafkaReceiverLink_FetchMessage_Call) RunAndReturn(run func(ctx context.Context) (kafka.Message, error)) *MockKafkaReceiverLink_FetchMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockKafkaReceiverLink
func (_mock *MockKafkaReceiverLink) Stats() kafka.ReaderStats {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 kafka.ReaderStats
	if returnFunc, ok := ret.Get(0).(func() kafka.ReaderStats); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(kafka.ReaderStats)
	}
	return r0
}

// MockKafkaReceiverLink_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockKafkaReceiverLink_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockKafkaReceiverLink_Expecter) Stats() *MockKafkaReceiverLink_Stats_Call {
	return &MockKafkaReceiverLink_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockKafkaReceiverLink_Stats_Call) Run(run func()) *MockKafkaReceiverLink_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKafkaReceiverLink_Stats_Call) Return(readerStats kafka.ReaderStats) *MockKafkaReceiverLink_Stats_Call {
	_c.Call.Return(readerStats)
	return _c
}

func (_c *MockKafkaReceiverLink_Stats_Call) RunAndReturn(run func() kafka.ReaderStats) *MockKafkaReceiverLink_Stats_Call {
	_c.Call.Return(run)
	return _c
}
