// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/container"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLazyContainer creates a new instance of MockLazyContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLazyContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLazyContainer {
	mock := &MockLazyContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLazyContainer is an autogenerated mock type for the LazyContainer type
type MockLazyContainer struct {
	mock.Mock
}

type MockLazyContainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLazyContainer) EXPECT() *MockLazyContainer_Expecter {
	return &MockLazyContainer_Expecter{mock: &_m.Mock}
}

// AllNames provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) AllNames() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllNames")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockLazyContainer_AllNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllNames'
type MockLazyContainer_AllNames_Call struct {
	*mock.Call
}

// AllNames is a helper method to define mock.On call
func (_e *MockLazyContainer_Expecter) AllNames() *MockLazyContainer_AllNames_Call {
	return &MockLazyContainer_AllNames_Call{Call: _e.mock.On("AllNames")}
}

func (_c *MockLazyContainer_AllNames_Call) Run(run func()) *MockLazyContainer_AllNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLazyContainer_AllNames_Call) Return(strings []string) *MockLazyContainer_AllNames_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockLazyContainer_AllNames_Call) RunAndReturn(run func() []string) *MockLazyContainer_AllNames_Call {
	_c.Call.Return(run)
	return _c
}

// AllProviders provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) AllProviders() map[string]container.Provider {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllProviders")
	}

	var r0 map[string]container.Provider
	if returnFunc, ok := ret.Get(0).(func() map[string]container.Provider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]container.Provider)
		}
	}
	return r0
}

// MockLazyContainer_AllProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllProviders'
type MockLazyContainer_AllProviders_Call struct {
	*mock.Call
}

// AllProviders is a helper method to define mock.On call
func (_e *MockLazyContainer_Expecter) AllProviders() *MockLazyContainer_AllProviders_Call {
	return &MockLazyContainer_AllProviders_Call{Call: _e.mock.On("AllProviders")}
}

func (_c *MockLazyContainer_AllProviders_Call) Run(run func()) *MockLazyContainer_AllProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLazyContainer_AllProviders_Call) Return(stringToProvider map[string]container.Provider) *MockLazyContainer_AllProviders_Call {
	_c.Call.Return(stringToProvider)
	return _c
}

func (_c *MockLazyContainer_AllProviders_Call) RunAndReturn(run func() map[string]container.Provider) *MockLazyContainer_AllProviders_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLazyContainer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockLazyContainer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLazyContainer_Expecter) Close(ctx interface{}) *MockLazyContainer_Close_Call {
	return &MockLazyContainer_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockLazyContainer_Close_Call) Run(run func(ctx context.Context)) *MockLazyContainer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLazyContainer_Close_Call) Return(err error) *MockLazyContainer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLazyContainer_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockLazyContainer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstance provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) GetInstance(name string) (any, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (any, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLazyContainer_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type MockLazyContainer_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
//   - name string
func (_e *MockLazyContainer_Expecter) GetInstance(name interface{}) *MockLazyContainer_GetInstance_Call {
	return &MockLazyContainer_GetInstance_Call{Call: _e.mock.On("GetInstance", name)}
}

func (_c *MockLazyContainer_GetInstance_Call) Run(run func(name string)) *MockLazyContainer_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLazyContainer_GetInstance_Call) Return(v any, err error) *MockLazyContainer_GetInstance_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockLazyContainer_GetInstance_Call) RunAndReturn(run func(name string) (any, error)) *MockLazyContainer_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockLazyContainer_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockLazyContainer_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockLazyContainer_Expecter) GetName() *MockLazyContainer_GetName_Call {
	return &MockLazyContainer_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockLazyContainer_GetName_Call) Run(run func()) *MockLazyContainer_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLazyContainer_GetName_Call) Return(s string) *MockLazyContainer_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockLazyContainer_GetName_Call) RunAndReturn(run func() string) *MockLazyContainer_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLazyContainer_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockLazyContainer_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLazyContainer_Expecter) Init(ctx interface{}) *MockLazyContainer_Init_Call {
	return &MockLazyContainer_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockLazyContainer_Init_Call) Run(run func(ctx context.Context)) *MockLazyContainer_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLazyContainer_Init_Call) Return(err error) *MockLazyContainer_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLazyContainer_Init_Call) RunAndReturn(run func(ctx context.Context) error) *MockLazyContainer_Init_Call {
	_c.Call.Return(run)
	return _c
}

// IsRegistered provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) IsRegistered(name string) bool {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for IsRegistered")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockLazyContainer_IsRegistered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRegistered'
type MockLazyContainer_IsRegistered_Call struct {
	*mock.Call
}

// IsRegistered is a helper method to define mock.On call
//   - name string
func (_e *MockLazyContainer_Expecter) IsRegistered(name interface{}) *MockLazyContainer_IsRegistered_Call {
	return &MockLazyContainer_IsRegistered_Call{Call: _e.mock.On("IsRegistered", name)}
}

func (_c *MockLazyContainer_IsRegistered_Call) Run(run func(name string)) *MockLazyContainer_IsRegistered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLazyContainer_IsRegistered_Call) Return(b bool) *MockLazyContainer_IsRegistered_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockLazyContainer_IsRegistered_Call) RunAndReturn(run func(name string) bool) *MockLazyContainer_IsRegistered_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterInstance provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) RegisterInstance(name string, instance any) error {
	ret := _mock.Called(name, instance)

	if len(ret) == 0 {
		panic("no return value specified for RegisterInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(name, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLazyContainer_RegisterInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterInstance'
type MockLazyContainer_RegisterInstance_Call struct {
	*mock.Call
}

// RegisterInstance is a helper method to define mock.On call
//   - name string
//   - instance any
func (_e *MockLazyContainer_Expecter) RegisterInstance(name interface{}, instance interface{}) *MockLazyContainer_RegisterInstance_Call {
	return &MockLazyContainer_RegisterInstance_Call{Call: _e.mock.On("RegisterInstance", name, instance)}
}

func (_c *MockLazyContainer_RegisterInstance_Call) Run(run func(name string, instance any)) *MockLazyContainer_RegisterInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLazyContainer_RegisterInstance_Call) Return(err error) *MockLazyContainer_RegisterInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLazyContainer_RegisterInstance_Call) RunAndReturn(run func(name string, instance any) error) *MockLazyContainer_RegisterInstance_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterProvider provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) RegisterProvider(name string, provider container.Provider) error {
	ret := _mock.Called(name, provider)

	if len(ret) == 0 {
		panic("no return value specified for RegisterProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, container.Provider) error); ok {
		r0 = returnFunc(name, provider)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLazyContainer_RegisterProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterProvider'
type MockLazyContainer_RegisterProvider_Call struct {
	*mock.Call
}

// RegisterProvider is a helper method to define mock.On call
//   - name string
//   - provider container.Provider
func (_e *MockLazyContainer_Expecter) RegisterProvider(name interface{}, provider interface{}) *MockLazyContainer_RegisterProvider_Call {
	return &MockLazyContainer_RegisterProvider_Call{Call: _e.mock.On("RegisterProvider", name, provider)}
}

func (_c *MockLazyContainer_RegisterProvider_Call) Run(run func(name string, provider container.Provider)) *MockLazyContainer_RegisterProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 container.Provider
		if args[1] != nil {
			arg1 = args[1].(container.Provider)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLazyContainer_RegisterProvider_Call) Return(err error) *MockLazyContainer_RegisterProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLazyContainer_RegisterProvider_Call) RunAndReturn(run func(name string, provider container.Provider) error) *MockLazyContainer_RegisterProvider_Call {
	_c.Call.Return(run)
	return _c
}

// Unregister provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) Unregister(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Unregister")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLazyContainer_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockLazyContainer_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - name string
func (_e *MockLazyContainer_Expecter) Unregister(name interface{}) *MockLazyContainer_Unregister_Call {
	return &MockLazyContainer_Unregister_Call{Call: _e.mock.On("Unregister", name)}
}

func (_c *MockLazyContainer_Unregister_Call) Run(run func(name string)) *MockLazyContainer_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLazyContainer_Unregister_Call) Return(err error) *MockLazyContainer_Unregister_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLazyContainer_Unregister_Call) RunAndReturn(run func(name string) error) *MockLazyContainer_Unregister_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterInstance provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) UnregisterInstance(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterInstance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLazyContainer_UnregisterInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterInstance'
type MockLazyContainer_UnregisterInstance_Call struct {
	*mock.Call
}

// UnregisterInstance is a helper method to define mock.On call
//   - name string
func (_e *MockLazyContainer_Expecter) UnregisterInstance(name interface{}) *MockLazyContainer_UnregisterInstance_Call {
	return &MockLazyContainer_UnregisterInstance_Call{Call: _e.mock.On("UnregisterInstance", name)}
}

func (_c *MockLazyContainer_UnregisterInstance_Call) Run(run func(name string)) *MockLazyContainer_UnregisterInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLazyContainer_UnregisterInstance_Call) Return(err error) *MockLazyContainer_UnregisterInstance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLazyContainer_UnregisterInstance_Call) RunAndReturn(run func(name string) error) *MockLazyContainer_UnregisterInstance_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterProvider provides a mock function for the type MockLazyContainer
func (_mock *MockLazyContainer) UnregisterProvider(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLazyContainer_UnregisterProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterProvider'
type MockLazyContainer_UnregisterProvider_Call struct {
	*mock.Call
}

// UnregisterProvider is a helper method to define mock.On call
//   - name string
func (_e *MockLazyContainer_Expecter) UnregisterProvider(name interface{}) *MockLazyContainer_UnregisterProvider_Call {
	return &MockLazyContainer_UnregisterProvider_Call{Call: _e.mock.On("UnregisterProvider", name)}
}

func (_c *MockLazyContainer_UnregisterProvider_Call) Run(run func(name string)) *MockLazyContainer_UnregisterProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLazyContainer_UnregisterProvider_Call) Return(err error) *MockLazyContainer_UnregisterProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLazyContainer_UnregisterProvider_Call) RunAndReturn(run func(name string) error) *MockLazyContainer_UnregisterProvider_Call {
	_c.Call.Return(run)
	return _c
}
