// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockContainer creates a new instance of MockContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainer {
	mock := &MockContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContainer is an autogenerated mock type for the Container type
type MockContainer struct {
	mock.Mock
}

type MockContainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContainer) EXPECT() *MockContainer_Expecter {
	return &MockContainer_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockContainer
func (_mock *MockContainer) Add(name string, instance any) error {
	ret := _mock.Called(name, instance)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(name, instance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainer_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockContainer_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - name string
//   - instance any
func (_e *MockContainer_Expecter) Add(name interface{}, instance interface{}) *MockContainer_Add_Call {
	return &MockContainer_Add_Call{Call: _e.mock.On("Add", name, instance)}
}

func (_c *MockContainer_Add_Call) Run(run func(name string, instance any)) *MockContainer_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainer_Add_Call) Return(err error) *MockContainer_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainer_Add_Call) RunAndReturn(run func(name string, instance any) error) *MockContainer_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AllInstances provides a mock function for the type MockContainer
func (_mock *MockContainer) AllInstances() map[string]any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllInstances")
	}

	var r0 map[string]any
	if returnFunc, ok := ret.Get(0).(func() map[string]any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	return r0
}

// MockContainer_AllInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllInstances'
type MockContainer_AllInstances_Call struct {
	*mock.Call
}

// AllInstances is a helper method to define mock.On call
func (_e *MockContainer_Expecter) AllInstances() *MockContainer_AllInstances_Call {
	return &MockContainer_AllInstances_Call{Call: _e.mock.On("AllInstances")}
}

func (_c *MockContainer_AllInstances_Call) Run(run func()) *MockContainer_AllInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContainer_AllInstances_Call) Return(stringToV map[string]any) *MockContainer_AllInstances_Call {
	_c.Call.Return(stringToV)
	return _c
}

func (_c *MockContainer_AllInstances_Call) RunAndReturn(run func() map[string]any) *MockContainer_AllInstances_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockContainer
func (_mock *MockContainer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockContainer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockContainer_Expecter) Close() *MockContainer_Close_Call {
	return &MockContainer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockContainer_Close_Call) Run(run func()) *MockContainer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContainer_Close_Call) Return(err error) *MockContainer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainer_Close_Call) RunAndReturn(run func() error) *MockContainer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstance provides a mock function for the type MockContainer
func (_mock *MockContainer) GetInstance(name string) (any, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetInstance")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (any, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContainer_GetInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstance'
type MockContainer_GetInstance_Call struct {
	*mock.Call
}

// GetInstance is a helper method to define mock.On call
//   - name string
func (_e *MockContainer_Expecter) GetInstance(name interface{}) *MockContainer_GetInstance_Call {
	return &MockContainer_GetInstance_Call{Call: _e.mock.On("GetInstance", name)}
}

func (_c *MockContainer_GetInstance_Call) Run(run func(name string)) *MockContainer_GetInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainer_GetInstance_Call) Return(v any, err error) *MockContainer_GetInstance_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockContainer_GetInstance_Call) RunAndReturn(run func(name string) (any, error)) *MockContainer_GetInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockContainer
func (_mock *MockContainer) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockContainer_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockContainer_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockContainer_Expecter) GetName() *MockContainer_GetName_Call {
	return &MockContainer_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockContainer_GetName_Call) Run(run func()) *MockContainer_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContainer_GetName_Call) Return(s string) *MockContainer_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockContainer_GetName_Call) RunAndReturn(run func() string) *MockContainer_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockContainer
func (_mock *MockContainer) Init() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainer_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockContainer_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *MockContainer_Expecter) Init() *MockContainer_Init_Call {
	return &MockContainer_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *MockContainer_Init_Call) Run(run func()) *MockContainer_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContainer_Init_Call) Return(err error) *MockContainer_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainer_Init_Call) RunAndReturn(run func() error) *MockContainer_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockContainer
func (_mock *MockContainer) Remove(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContainer_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockContainer_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - name string
func (_e *MockContainer_Expecter) Remove(name interface{}) *MockContainer_Remove_Call {
	return &MockContainer_Remove_Call{Call: _e.mock.On("Remove", name)}
}

func (_c *MockContainer_Remove_Call) Run(run func(name string)) *MockContainer_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainer_Remove_Call) Return(err error) *MockContainer_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContainer_Remove_Call) RunAndReturn(run func(name string) error) *MockContainer_Remove_Call {
	_c.Call.Return(run)
	return _c
}
