// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockContextCloser creates a new instance of MockContextCloser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContextCloser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContextCloser {
	mock := &MockContextCloser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContextCloser is an autogenerated mock type for the ContextCloser type
type MockContextCloser struct {
	mock.Mock
}

type MockContextCloser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContextCloser) EXPECT() *MockContextCloser_Expecter {
	return &MockContextCloser_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockContextCloser
func (_mock *MockContextCloser) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextCloser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockContextCloser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContextCloser_Expecter) Close(ctx any) *MockContextCloser_Close_Call {
	return &MockContextCloser_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockContextCloser_Close_Call) Run(run func(ctx context.Context)) *MockContextCloser_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContextCloser_Close_Call) Return(err error) *MockContextCloser_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextCloser_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockContextCloser_Close_Call {
	_c.Call.Return(run)
	return _c
}
