// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/transport/amqp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientSender creates a new instance of MockClientSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientSender[O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientSender[O] {
	mock := &MockClientSender[O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientSender is an autogenerated mock type for the ClientSender type
type MockClientSender[O any] struct {
	mock.Mock
}

type MockClientSender_Expecter[O any] struct {
	mock *mock.Mock
}

func (_m *MockClientSender[O]) EXPECT() *MockClientSender_Expecter[O] {
	return &MockClientSender_Expecter[O]{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClientSender
func (_mock *MockClientSender[O]) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientSender_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClientSender_Close_Call[O any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientSender_Expecter[O]) Close(ctx any) *MockClientSender_Close_Call[O] {
	return &MockClientSender_Close_Call[O]{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockClientSender_Close_Call[O]) Run(run func(ctx context.Context)) *MockClientSender_Close_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientSender_Close_Call[O]) Return(err error) *MockClientSender_Close_Call[O] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientSender_Close_Call[O]) RunAndReturn(run func(ctx context.Context) error) *MockClientSender_Close_Call[O] {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockClientSender
func (_mock *MockClientSender[O]) Publish(ctx context.Context, targetName string, msg *amqp.Message, sendOpts O) error {
	ret := _mock.Called(ctx, targetName, msg, sendOpts)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *amqp.Message, O) error); ok {
		r0 = returnFunc(ctx, targetName, msg, sendOpts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientSender_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockClientSender_Publish_Call[O any] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - targetName string
//   - msg *amqp.Message
//   - sendOpts O
func (_e *MockClientSender_Expecter[O]) Publish(ctx any, targetName any, msg any, sendOpts any) *MockClientSender_Publish_Call[O] {
	return &MockClientSender_Publish_Call[O]{Call: _e.mock.On("Publish", ctx, targetName, msg, sendOpts)}
}

func (_c *MockClientSender_Publish_Call[O]) Run(run func(ctx context.Context, targetName string, msg *amqp.Message, sendOpts O)) *MockClientSender_Publish_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *amqp.Message
		if args[2] != nil {
			arg2 = args[2].(*amqp.Message)
		}
		var arg3 O
		if args[3] != nil {
			arg3 = args[3].(O)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClientSender_Publish_Call[O]) Return(err error) *MockClientSender_Publish_Call[O] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientSender_Publish_Call[O]) RunAndReturn(run func(ctx context.Context, targetName string, msg *amqp.Message, sendOpts O) error) *MockClientSender_Publish_Call[O] {
	_c.Call.Return(run)
	return _c
}
