// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/transport/amqp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientSingleSender creates a new instance of MockClientSingleSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientSingleSender[SendOpts any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientSingleSender[SendOpts] {
	mock := &MockClientSingleSender[SendOpts]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientSingleSender is an autogenerated mock type for the ClientSingleSender type
type MockClientSingleSender[SendOpts any] struct {
	mock.Mock
}

type MockClientSingleSender_Expecter[SendOpts any] struct {
	mock *mock.Mock
}

func (_m *MockClientSingleSender[SendOpts]) EXPECT() *MockClientSingleSender_Expecter[SendOpts] {
	return &MockClientSingleSender_Expecter[SendOpts]{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClientSingleSender
func (_mock *MockClientSingleSender[SendOpts]) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientSingleSender_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClientSingleSender_Close_Call[SendOpts any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientSingleSender_Expecter[SendOpts]) Close(ctx any) *MockClientSingleSender_Close_Call[SendOpts] {
	return &MockClientSingleSender_Close_Call[SendOpts]{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockClientSingleSender_Close_Call[SendOpts]) Run(run func(ctx context.Context)) *MockClientSingleSender_Close_Call[SendOpts] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientSingleSender_Close_Call[SendOpts]) Return(err error) *MockClientSingleSender_Close_Call[SendOpts] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientSingleSender_Close_Call[SendOpts]) RunAndReturn(run func(ctx context.Context) error) *MockClientSingleSender_Close_Call[SendOpts] {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockClientSingleSender
func (_mock *MockClientSingleSender[SendOpts]) Publish(ctx context.Context, msg *amqp.Message, opts SendOpts) error {
	ret := _mock.Called(ctx, msg, opts)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.Message, SendOpts) error); ok {
		r0 = returnFunc(ctx, msg, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientSingleSender_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockClientSingleSender_Publish_Call[SendOpts any] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *amqp.Message
//   - opts SendOpts
func (_e *MockClientSingleSender_Expecter[SendOpts]) Publish(ctx any, msg any, opts any) *MockClientSingleSender_Publish_Call[SendOpts] {
	return &MockClientSingleSender_Publish_Call[SendOpts]{Call: _e.mock.On("Publish", ctx, msg, opts)}
}

func (_c *MockClientSingleSender_Publish_Call[SendOpts]) Run(run func(ctx context.Context, msg *amqp.Message, opts SendOpts)) *MockClientSingleSender_Publish_Call[SendOpts] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *amqp.Message
		if args[1] != nil {
			arg1 = args[1].(*amqp.Message)
		}
		var arg2 SendOpts
		if args[2] != nil {
			arg2 = args[2].(SendOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientSingleSender_Publish_Call[SendOpts]) Return(err error) *MockClientSingleSender_Publish_Call[SendOpts] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientSingleSender_Publish_Call[SendOpts]) RunAndReturn(run func(ctx context.Context, msg *amqp.Message, opts SendOpts) error) *MockClientSingleSender_Publish_Call[SendOpts] {
	_c.Call.Return(run)
	return _c
}
