// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/transport/amqp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReceiver creates a new instance of MockReceiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceiver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceiver {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReceiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReceiver is an autogenerated mock type for the Receiver type
type MockReceiver struct {
	mock.Mock
}

type MockReceiver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceiver) EXPECT() *MockReceiver_Expecter {
	return &MockReceiver_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockReceiver
func (_mock *MockReceiver) Accept(ctx context.Context, msg amqp.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, amqp.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceiver_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockReceiver_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - msg amqp.Message
func (_e *MockReceiver_Expecter) Accept(ctx any, msg any) *MockReceiver_Accept_Call {
	return &MockReceiver_Accept_Call{Call: _e.mock.On("Accept", ctx, msg)}
}

func (_c *MockReceiver_Accept_Call) Run(run func(ctx context.Context, msg amqp.Message)) *MockReceiver_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 amqp.Message
		if args[1] != nil {
			arg1 = args[1].(amqp.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceiver_Accept_Call) Return(err error) *MockReceiver_Accept_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceiver_Accept_Call) RunAndReturn(run func(ctx context.Context, msg amqp.Message) error) *MockReceiver_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockReceiver
func (_mock *MockReceiver) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceiver_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReceiver_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReceiver_Expecter) Close(ctx any) *MockReceiver_Close_Call {
	return &MockReceiver_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockReceiver_Close_Call) Run(run func(ctx context.Context)) *MockReceiver_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReceiver_Close_Call) Return(err error) *MockReceiver_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceiver_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockReceiver_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetTargetName provides a mock function for the type MockReceiver
func (_mock *MockReceiver) GetTargetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTargetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReceiver_GetTargetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTargetName'
type MockReceiver_GetTargetName_Call struct {
	*mock.Call
}

// GetTargetName is a helper method to define mock.On call
func (_e *MockReceiver_Expecter) GetTargetName() *MockReceiver_GetTargetName_Call {
	return &MockReceiver_GetTargetName_Call{Call: _e.mock.On("GetTargetName")}
}

func (_c *MockReceiver_GetTargetName_Call) Run(run func()) *MockReceiver_GetTargetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReceiver_GetTargetName_Call) Return(s string) *MockReceiver_GetTargetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReceiver_GetTargetName_Call) RunAndReturn(run func() string) *MockReceiver_GetTargetName_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type MockReceiver
func (_mock *MockReceiver) Receive(ctx context.Context) (amqp.Message, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 amqp.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (amqp.Message, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) amqp.Message); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(amqp.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceiver_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockReceiver_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReceiver_Expecter) Receive(ctx any) *MockReceiver_Receive_Call {
	return &MockReceiver_Receive_Call{Call: _e.mock.On("Receive", ctx)}
}

func (_c *MockReceiver_Receive_Call) Run(run func(ctx context.Context)) *MockReceiver_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReceiver_Receive_Call) Return(message amqp.Message, err error) *MockReceiver_Receive_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockReceiver_Receive_Call) RunAndReturn(run func(ctx context.Context) (amqp.Message, error)) *MockReceiver_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// Reject provides a mock function for the type MockReceiver
func (_mock *MockReceiver) Reject(ctx context.Context, msg amqp.Message, err error) error {
	ret := _mock.Called(ctx, msg, err)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, amqp.Message, error) error); ok {
		r0 = returnFunc(ctx, msg, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceiver_Reject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reject'
type MockReceiver_Reject_Call struct {
	*mock.Call
}

// Reject is a helper method to define mock.On call
//   - ctx context.Context
//   - msg amqp.Message
//   - err error
func (_e *MockReceiver_Expecter) Reject(ctx any, msg any, err any) *MockReceiver_Reject_Call {
	return &MockReceiver_Reject_Call{Call: _e.mock.On("Reject", ctx, msg, err)}
}

func (_c *MockReceiver_Reject_Call) Run(run func(ctx context.Context, msg amqp.Message, err error)) *MockReceiver_Reject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 amqp.Message
		if args[1] != nil {
			arg1 = args[1].(amqp.Message)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReceiver_Reject_Call) Return(err1 error) *MockReceiver_Reject_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockReceiver_Reject_Call) RunAndReturn(run func(ctx context.Context, msg amqp.Message, err error) error) *MockReceiver_Reject_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type MockReceiver
func (_mock *MockReceiver) Release(ctx context.Context, msg amqp.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, amqp.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceiver_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockReceiver_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - msg amqp.Message
func (_e *MockReceiver_Expecter) Release(ctx any, msg any) *MockReceiver_Release_Call {
	return &MockReceiver_Release_Call{Call: _e.mock.On("Release", ctx, msg)}
}

func (_c *MockReceiver_Release_Call) Run(run func(ctx context.Context, msg amqp.Message)) *MockReceiver_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 amqp.Message
		if args[1] != nil {
			arg1 = args[1].(amqp.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceiver_Release_Call) Return(err error) *MockReceiver_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceiver_Release_Call) RunAndReturn(run func(ctx context.Context, msg amqp.Message) error) *MockReceiver_Release_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockReceiver
func (_mock *MockReceiver) Stats() amqp.ReceiverStats {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 amqp.ReceiverStats
	if returnFunc, ok := ret.Get(0).(func() amqp.ReceiverStats); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(amqp.ReceiverStats)
	}
	return r0
}

// MockReceiver_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockReceiver_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockReceiver_Expecter) Stats() *MockReceiver_Stats_Call {
	return &MockReceiver_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockReceiver_Stats_Call) Run(run func()) *MockReceiver_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReceiver_Stats_Call) Return(receiverStats amqp.ReceiverStats) *MockReceiver_Stats_Call {
	_c.Call.Return(receiverStats)
	return _c
}

func (_c *MockReceiver_Stats_Call) RunAndReturn(run func() amqp.ReceiverStats) *MockReceiver_Stats_Call {
	_c.Call.Return(run)
	return _c
}
