// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/transport/amqp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender[SendOpts any, MsgHeader any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender[SendOpts, MsgHeader] {
	mock := &MockSender[SendOpts, MsgHeader]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender[SendOpts any, MsgHeader any] struct {
	mock.Mock
}

type MockSender_Expecter[SendOpts any, MsgHeader any] struct {
	mock *mock.Mock
}

func (_m *MockSender[SendOpts, MsgHeader]) EXPECT() *MockSender_Expecter[SendOpts, MsgHeader] {
	return &MockSender_Expecter[SendOpts, MsgHeader]{mock: &_m.Mock}
}

// Close provides a mock function for the type MockSender
func (_mock *MockSender[SendOpts, MsgHeader]) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSender_Close_Call[SendOpts any, MsgHeader any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSender_Expecter[SendOpts, MsgHeader]) Close(ctx any) *MockSender_Close_Call[SendOpts, MsgHeader] {
	return &MockSender_Close_Call[SendOpts, MsgHeader]{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockSender_Close_Call[SendOpts, MsgHeader]) Run(run func(ctx context.Context)) *MockSender_Close_Call[SendOpts, MsgHeader] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSender_Close_Call[SendOpts, MsgHeader]) Return(err error) *MockSender_Close_Call[SendOpts, MsgHeader] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_Close_Call[SendOpts, MsgHeader]) RunAndReturn(run func(ctx context.Context) error) *MockSender_Close_Call[SendOpts, MsgHeader] {
	_c.Call.Return(run)
	return _c
}

// GetTargetName provides a mock function for the type MockSender
func (_mock *MockSender[SendOpts, MsgHeader]) GetTargetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTargetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSender_GetTargetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTargetName'
type MockSender_GetTargetName_Call[SendOpts any, MsgHeader any] struct {
	*mock.Call
}

// GetTargetName is a helper method to define mock.On call
func (_e *MockSender_Expecter[SendOpts, MsgHeader]) GetTargetName() *MockSender_GetTargetName_Call[SendOpts, MsgHeader] {
	return &MockSender_GetTargetName_Call[SendOpts, MsgHeader]{Call: _e.mock.On("GetTargetName")}
}

func (_c *MockSender_GetTargetName_Call[SendOpts, MsgHeader]) Run(run func()) *MockSender_GetTargetName_Call[SendOpts, MsgHeader] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSender_GetTargetName_Call[SendOpts, MsgHeader]) Return(s string) *MockSender_GetTargetName_Call[SendOpts, MsgHeader] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSender_GetTargetName_Call[SendOpts, MsgHeader]) RunAndReturn(run func() string) *MockSender_GetTargetName_Call[SendOpts, MsgHeader] {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockSender
func (_mock *MockSender[SendOpts, MsgHeader]) Publish(ctx context.Context, msg *amqp.Message[MsgHeader], opts SendOpts) error {
	ret := _mock.Called(ctx, msg, opts)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.Message[MsgHeader], SendOpts) error); ok {
		r0 = returnFunc(ctx, msg, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockSender_Publish_Call[SendOpts any, MsgHeader any] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *amqp.Message[MsgHeader]
//   - opts SendOpts
func (_e *MockSender_Expecter[SendOpts, MsgHeader]) Publish(ctx any, msg any, opts any) *MockSender_Publish_Call[SendOpts, MsgHeader] {
	return &MockSender_Publish_Call[SendOpts, MsgHeader]{Call: _e.mock.On("Publish", ctx, msg, opts)}
}

func (_c *MockSender_Publish_Call[SendOpts, MsgHeader]) Run(run func(ctx context.Context, msg *amqp.Message[MsgHeader], opts SendOpts)) *MockSender_Publish_Call[SendOpts, MsgHeader] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *amqp.Message[MsgHeader]
		if args[1] != nil {
			arg1 = args[1].(*amqp.Message[MsgHeader])
		}
		var arg2 SendOpts
		if args[2] != nil {
			arg2 = args[2].(SendOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSender_Publish_Call[SendOpts, MsgHeader]) Return(err error) *MockSender_Publish_Call[SendOpts, MsgHeader] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_Publish_Call[SendOpts, MsgHeader]) RunAndReturn(run func(ctx context.Context, msg *amqp.Message[MsgHeader], opts SendOpts) error) *MockSender_Publish_Call[SendOpts, MsgHeader] {
	_c.Call.Return(run)
	return _c
}
