// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/transport/amqp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockSender
func (_mock *MockSender) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSender_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSender_Expecter) Close(ctx any) *MockSender_Close_Call {
	return &MockSender_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockSender_Close_Call) Run(run func(ctx context.Context)) *MockSender_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSender_Close_Call) Return(err error) *MockSender_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockSender_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetTargetName provides a mock function for the type MockSender
func (_mock *MockSender) GetTargetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTargetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSender_GetTargetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTargetName'
type MockSender_GetTargetName_Call struct {
	*mock.Call
}

// GetTargetName is a helper method to define mock.On call
func (_e *MockSender_Expecter) GetTargetName() *MockSender_GetTargetName_Call {
	return &MockSender_GetTargetName_Call{Call: _e.mock.On("GetTargetName")}
}

func (_c *MockSender_GetTargetName_Call) Run(run func()) *MockSender_GetTargetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSender_GetTargetName_Call) Return(s string) *MockSender_GetTargetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSender_GetTargetName_Call) RunAndReturn(run func() string) *MockSender_GetTargetName_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockSender
func (_mock *MockSender) Publish(ctx context.Context, msg amqp.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, amqp.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSender_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockSender_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - msg amqp.Message
func (_e *MockSender_Expecter) Publish(ctx any, msg any) *MockSender_Publish_Call {
	return &MockSender_Publish_Call{Call: _e.mock.On("Publish", ctx, msg)}
}

func (_c *MockSender_Publish_Call) Run(run func(ctx context.Context, msg amqp.Message)) *MockSender_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 amqp.Message
		if args[1] != nil {
			arg1 = args[1].(amqp.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSender_Publish_Call) Return(err error) *MockSender_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSender_Publish_Call) RunAndReturn(run func(ctx context.Context, msg amqp.Message) error) *MockSender_Publish_Call {
	_c.Call.Return(run)
	return _c
}
