// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/transport/amqp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientReceiver creates a new instance of MockClientReceiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientReceiver[ReceiveOpts any, MsgHeader any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientReceiver[ReceiveOpts, MsgHeader] {
	mock := &MockClientReceiver[ReceiveOpts, MsgHeader]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientReceiver is an autogenerated mock type for the ClientReceiver type
type MockClientReceiver[ReceiveOpts any, MsgHeader any] struct {
	mock.Mock
}

type MockClientReceiver_Expecter[ReceiveOpts any, MsgHeader any] struct {
	mock *mock.Mock
}

func (_m *MockClientReceiver[ReceiveOpts, MsgHeader]) EXPECT() *MockClientReceiver_Expecter[ReceiveOpts, MsgHeader] {
	return &MockClientReceiver_Expecter[ReceiveOpts, MsgHeader]{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockClientReceiver
func (_mock *MockClientReceiver[ReceiveOpts, MsgHeader]) Accept(ctx context.Context, msg *amqp.Message[MsgHeader]) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.Message[MsgHeader]) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientReceiver_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockClientReceiver_Accept_Call[ReceiveOpts any, MsgHeader any] struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *amqp.Message[MsgHeader]
func (_e *MockClientReceiver_Expecter[ReceiveOpts, MsgHeader]) Accept(ctx any, msg any) *MockClientReceiver_Accept_Call[ReceiveOpts, MsgHeader] {
	return &MockClientReceiver_Accept_Call[ReceiveOpts, MsgHeader]{Call: _e.mock.On("Accept", ctx, msg)}
}

func (_c *MockClientReceiver_Accept_Call[ReceiveOpts, MsgHeader]) Run(run func(ctx context.Context, msg *amqp.Message[MsgHeader])) *MockClientReceiver_Accept_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *amqp.Message[MsgHeader]
		if args[1] != nil {
			arg1 = args[1].(*amqp.Message[MsgHeader])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientReceiver_Accept_Call[ReceiveOpts, MsgHeader]) Return(err error) *MockClientReceiver_Accept_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientReceiver_Accept_Call[ReceiveOpts, MsgHeader]) RunAndReturn(run func(ctx context.Context, msg *amqp.Message[MsgHeader]) error) *MockClientReceiver_Accept_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockClientReceiver
func (_mock *MockClientReceiver[ReceiveOpts, MsgHeader]) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientReceiver_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClientReceiver_Close_Call[ReceiveOpts any, MsgHeader any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientReceiver_Expecter[ReceiveOpts, MsgHeader]) Close(ctx any) *MockClientReceiver_Close_Call[ReceiveOpts, MsgHeader] {
	return &MockClientReceiver_Close_Call[ReceiveOpts, MsgHeader]{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockClientReceiver_Close_Call[ReceiveOpts, MsgHeader]) Run(run func(ctx context.Context)) *MockClientReceiver_Close_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientReceiver_Close_Call[ReceiveOpts, MsgHeader]) Return(err error) *MockClientReceiver_Close_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientReceiver_Close_Call[ReceiveOpts, MsgHeader]) RunAndReturn(run func(ctx context.Context) error) *MockClientReceiver_Close_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type MockClientReceiver
func (_mock *MockClientReceiver[ReceiveOpts, MsgHeader]) Receive(ctx context.Context, targetName string, receiveOpts ReceiveOpts) (*amqp.Message[MsgHeader], error) {
	ret := _mock.Called(ctx, targetName, receiveOpts)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 *amqp.Message[MsgHeader]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ReceiveOpts) (*amqp.Message[MsgHeader], error)); ok {
		return returnFunc(ctx, targetName, receiveOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ReceiveOpts) *amqp.Message[MsgHeader]); ok {
		r0 = returnFunc(ctx, targetName, receiveOpts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp.Message[MsgHeader])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ReceiveOpts) error); ok {
		r1 = returnFunc(ctx, targetName, receiveOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientReceiver_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockClientReceiver_Receive_Call[ReceiveOpts any, MsgHeader any] struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
//   - targetName string
//   - receiveOpts ReceiveOpts
func (_e *MockClientReceiver_Expecter[ReceiveOpts, MsgHeader]) Receive(ctx any, targetName any, receiveOpts any) *MockClientReceiver_Receive_Call[ReceiveOpts, MsgHeader] {
	return &MockClientReceiver_Receive_Call[ReceiveOpts, MsgHeader]{Call: _e.mock.On("Receive", ctx, targetName, receiveOpts)}
}

func (_c *MockClientReceiver_Receive_Call[ReceiveOpts, MsgHeader]) Run(run func(ctx context.Context, targetName string, receiveOpts ReceiveOpts)) *MockClientReceiver_Receive_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ReceiveOpts
		if args[2] != nil {
			arg2 = args[2].(ReceiveOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientReceiver_Receive_Call[ReceiveOpts, MsgHeader]) Return(message *amqp.Message[MsgHeader], err error) *MockClientReceiver_Receive_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockClientReceiver_Receive_Call[ReceiveOpts, MsgHeader]) RunAndReturn(run func(ctx context.Context, targetName string, receiveOpts ReceiveOpts) (*amqp.Message[MsgHeader], error)) *MockClientReceiver_Receive_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Return(run)
	return _c
}

// Reject provides a mock function for the type MockClientReceiver
func (_mock *MockClientReceiver[ReceiveOpts, MsgHeader]) Reject(ctx context.Context, msg *amqp.Message[MsgHeader], err error) error {
	ret := _mock.Called(ctx, msg, err)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.Message[MsgHeader], error) error); ok {
		r0 = returnFunc(ctx, msg, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientReceiver_Reject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reject'
type MockClientReceiver_Reject_Call[ReceiveOpts any, MsgHeader any] struct {
	*mock.Call
}

// Reject is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *amqp.Message[MsgHeader]
//   - err error
func (_e *MockClientReceiver_Expecter[ReceiveOpts, MsgHeader]) Reject(ctx any, msg any, err any) *MockClientReceiver_Reject_Call[ReceiveOpts, MsgHeader] {
	return &MockClientReceiver_Reject_Call[ReceiveOpts, MsgHeader]{Call: _e.mock.On("Reject", ctx, msg, err)}
}

func (_c *MockClientReceiver_Reject_Call[ReceiveOpts, MsgHeader]) Run(run func(ctx context.Context, msg *amqp.Message[MsgHeader], err error)) *MockClientReceiver_Reject_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *amqp.Message[MsgHeader]
		if args[1] != nil {
			arg1 = args[1].(*amqp.Message[MsgHeader])
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientReceiver_Reject_Call[ReceiveOpts, MsgHeader]) Return(err1 error) *MockClientReceiver_Reject_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockClientReceiver_Reject_Call[ReceiveOpts, MsgHeader]) RunAndReturn(run func(ctx context.Context, msg *amqp.Message[MsgHeader], err error) error) *MockClientReceiver_Reject_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type MockClientReceiver
func (_mock *MockClientReceiver[ReceiveOpts, MsgHeader]) Release(ctx context.Context, msg *amqp.Message[MsgHeader]) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.Message[MsgHeader]) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientReceiver_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockClientReceiver_Release_Call[ReceiveOpts any, MsgHeader any] struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *amqp.Message[MsgHeader]
func (_e *MockClientReceiver_Expecter[ReceiveOpts, MsgHeader]) Release(ctx any, msg any) *MockClientReceiver_Release_Call[ReceiveOpts, MsgHeader] {
	return &MockClientReceiver_Release_Call[ReceiveOpts, MsgHeader]{Call: _e.mock.On("Release", ctx, msg)}
}

func (_c *MockClientReceiver_Release_Call[ReceiveOpts, MsgHeader]) Run(run func(ctx context.Context, msg *amqp.Message[MsgHeader])) *MockClientReceiver_Release_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *amqp.Message[MsgHeader]
		if args[1] != nil {
			arg1 = args[1].(*amqp.Message[MsgHeader])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientReceiver_Release_Call[ReceiveOpts, MsgHeader]) Return(err error) *MockClientReceiver_Release_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientReceiver_Release_Call[ReceiveOpts, MsgHeader]) RunAndReturn(run func(ctx context.Context, msg *amqp.Message[MsgHeader]) error) *MockClientReceiver_Release_Call[ReceiveOpts, MsgHeader] {
	_c.Call.Return(run)
	return _c
}
