// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/transport/amqp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReceiver creates a new instance of MockReceiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceiver[ReceiveOpts any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceiver[ReceiveOpts] {
	mock := &MockReceiver[ReceiveOpts]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReceiver is an autogenerated mock type for the Receiver type
type MockReceiver[ReceiveOpts any] struct {
	mock.Mock
}

type MockReceiver_Expecter[ReceiveOpts any] struct {
	mock *mock.Mock
}

func (_m *MockReceiver[ReceiveOpts]) EXPECT() *MockReceiver_Expecter[ReceiveOpts] {
	return &MockReceiver_Expecter[ReceiveOpts]{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockReceiver
func (_mock *MockReceiver[ReceiveOpts]) Accept(ctx context.Context, msg amqp.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, amqp.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceiver_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockReceiver_Accept_Call[ReceiveOpts any] struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - msg amqp.Message
func (_e *MockReceiver_Expecter[ReceiveOpts]) Accept(ctx any, msg any) *MockReceiver_Accept_Call[ReceiveOpts] {
	return &MockReceiver_Accept_Call[ReceiveOpts]{Call: _e.mock.On("Accept", ctx, msg)}
}

func (_c *MockReceiver_Accept_Call[ReceiveOpts]) Run(run func(ctx context.Context, msg amqp.Message)) *MockReceiver_Accept_Call[ReceiveOpts] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 amqp.Message
		if args[1] != nil {
			arg1 = args[1].(amqp.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceiver_Accept_Call[ReceiveOpts]) Return(err error) *MockReceiver_Accept_Call[ReceiveOpts] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceiver_Accept_Call[ReceiveOpts]) RunAndReturn(run func(ctx context.Context, msg amqp.Message) error) *MockReceiver_Accept_Call[ReceiveOpts] {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockReceiver
func (_mock *MockReceiver[ReceiveOpts]) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceiver_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReceiver_Close_Call[ReceiveOpts any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReceiver_Expecter[ReceiveOpts]) Close(ctx any) *MockReceiver_Close_Call[ReceiveOpts] {
	return &MockReceiver_Close_Call[ReceiveOpts]{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockReceiver_Close_Call[ReceiveOpts]) Run(run func(ctx context.Context)) *MockReceiver_Close_Call[ReceiveOpts] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReceiver_Close_Call[ReceiveOpts]) Return(err error) *MockReceiver_Close_Call[ReceiveOpts] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceiver_Close_Call[ReceiveOpts]) RunAndReturn(run func(ctx context.Context) error) *MockReceiver_Close_Call[ReceiveOpts] {
	_c.Call.Return(run)
	return _c
}

// GetTargetName provides a mock function for the type MockReceiver
func (_mock *MockReceiver[ReceiveOpts]) GetTargetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTargetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReceiver_GetTargetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTargetName'
type MockReceiver_GetTargetName_Call[ReceiveOpts any] struct {
	*mock.Call
}

// GetTargetName is a helper method to define mock.On call
func (_e *MockReceiver_Expecter[ReceiveOpts]) GetTargetName() *MockReceiver_GetTargetName_Call[ReceiveOpts] {
	return &MockReceiver_GetTargetName_Call[ReceiveOpts]{Call: _e.mock.On("GetTargetName")}
}

func (_c *MockReceiver_GetTargetName_Call[ReceiveOpts]) Run(run func()) *MockReceiver_GetTargetName_Call[ReceiveOpts] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReceiver_GetTargetName_Call[ReceiveOpts]) Return(s string) *MockReceiver_GetTargetName_Call[ReceiveOpts] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReceiver_GetTargetName_Call[ReceiveOpts]) RunAndReturn(run func() string) *MockReceiver_GetTargetName_Call[ReceiveOpts] {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type MockReceiver
func (_mock *MockReceiver[ReceiveOpts]) Receive(ctx context.Context, receiveOpts ReceiveOpts) (amqp.Message, error) {
	ret := _mock.Called(ctx, receiveOpts)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 amqp.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReceiveOpts) (amqp.Message, error)); ok {
		return returnFunc(ctx, receiveOpts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReceiveOpts) amqp.Message); ok {
		r0 = returnFunc(ctx, receiveOpts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(amqp.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ReceiveOpts) error); ok {
		r1 = returnFunc(ctx, receiveOpts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReceiver_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockReceiver_Receive_Call[ReceiveOpts any] struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
//   - receiveOpts ReceiveOpts
func (_e *MockReceiver_Expecter[ReceiveOpts]) Receive(ctx any, receiveOpts any) *MockReceiver_Receive_Call[ReceiveOpts] {
	return &MockReceiver_Receive_Call[ReceiveOpts]{Call: _e.mock.On("Receive", ctx, receiveOpts)}
}

func (_c *MockReceiver_Receive_Call[ReceiveOpts]) Run(run func(ctx context.Context, receiveOpts ReceiveOpts)) *MockReceiver_Receive_Call[ReceiveOpts] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ReceiveOpts
		if args[1] != nil {
			arg1 = args[1].(ReceiveOpts)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceiver_Receive_Call[ReceiveOpts]) Return(message amqp.Message, err error) *MockReceiver_Receive_Call[ReceiveOpts] {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockReceiver_Receive_Call[ReceiveOpts]) RunAndReturn(run func(ctx context.Context, receiveOpts ReceiveOpts) (amqp.Message, error)) *MockReceiver_Receive_Call[ReceiveOpts] {
	_c.Call.Return(run)
	return _c
}

// Reject provides a mock function for the type MockReceiver
func (_mock *MockReceiver[ReceiveOpts]) Reject(ctx context.Context, msg amqp.Message, err error) error {
	ret := _mock.Called(ctx, msg, err)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, amqp.Message, error) error); ok {
		r0 = returnFunc(ctx, msg, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceiver_Reject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reject'
type MockReceiver_Reject_Call[ReceiveOpts any] struct {
	*mock.Call
}

// Reject is a helper method to define mock.On call
//   - ctx context.Context
//   - msg amqp.Message
//   - err error
func (_e *MockReceiver_Expecter[ReceiveOpts]) Reject(ctx any, msg any, err any) *MockReceiver_Reject_Call[ReceiveOpts] {
	return &MockReceiver_Reject_Call[ReceiveOpts]{Call: _e.mock.On("Reject", ctx, msg, err)}
}

func (_c *MockReceiver_Reject_Call[ReceiveOpts]) Run(run func(ctx context.Context, msg amqp.Message, err error)) *MockReceiver_Reject_Call[ReceiveOpts] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 amqp.Message
		if args[1] != nil {
			arg1 = args[1].(amqp.Message)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReceiver_Reject_Call[ReceiveOpts]) Return(err1 error) *MockReceiver_Reject_Call[ReceiveOpts] {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockReceiver_Reject_Call[ReceiveOpts]) RunAndReturn(run func(ctx context.Context, msg amqp.Message, err error) error) *MockReceiver_Reject_Call[ReceiveOpts] {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type MockReceiver
func (_mock *MockReceiver[ReceiveOpts]) Release(ctx context.Context, msg amqp.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, amqp.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReceiver_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockReceiver_Release_Call[ReceiveOpts any] struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - msg amqp.Message
func (_e *MockReceiver_Expecter[ReceiveOpts]) Release(ctx any, msg any) *MockReceiver_Release_Call[ReceiveOpts] {
	return &MockReceiver_Release_Call[ReceiveOpts]{Call: _e.mock.On("Release", ctx, msg)}
}

func (_c *MockReceiver_Release_Call[ReceiveOpts]) Run(run func(ctx context.Context, msg amqp.Message)) *MockReceiver_Release_Call[ReceiveOpts] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 amqp.Message
		if args[1] != nil {
			arg1 = args[1].(amqp.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReceiver_Release_Call[ReceiveOpts]) Return(err error) *MockReceiver_Release_Call[ReceiveOpts] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReceiver_Release_Call[ReceiveOpts]) RunAndReturn(run func(ctx context.Context, msg amqp.Message) error) *MockReceiver_Release_Call[ReceiveOpts] {
	_c.Call.Return(run)
	return _c
}
