// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Azure/go-amqp"
	"github.com/ElfAstAhe/go-service-template/pkg/transport/broker"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAMQPReceiver creates a new instance of MockAMQPReceiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAMQPReceiver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAMQPReceiver {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAMQPReceiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAMQPReceiver is an autogenerated mock type for the AMQPReceiver type
type MockAMQPReceiver struct {
	mock.Mock
}

type MockAMQPReceiver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAMQPReceiver) EXPECT() *MockAMQPReceiver_Expecter {
	return &MockAMQPReceiver_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type MockAMQPReceiver
func (_mock *MockAMQPReceiver) Accept(ctx context.Context, msg broker.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAMQPReceiver_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockAMQPReceiver_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - ctx context.Context
//   - msg broker.Message
func (_e *MockAMQPReceiver_Expecter) Accept(ctx any, msg any) *MockAMQPReceiver_Accept_Call {
	return &MockAMQPReceiver_Accept_Call{Call: _e.mock.On("Accept", ctx, msg)}
}

func (_c *MockAMQPReceiver_Accept_Call) Run(run func(ctx context.Context, msg broker.Message)) *MockAMQPReceiver_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 broker.Message
		if args[1] != nil {
			arg1 = args[1].(broker.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAMQPReceiver_Accept_Call) Return(err error) *MockAMQPReceiver_Accept_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAMQPReceiver_Accept_Call) RunAndReturn(run func(ctx context.Context, msg broker.Message) error) *MockAMQPReceiver_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockAMQPReceiver
func (_mock *MockAMQPReceiver) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAMQPReceiver_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockAMQPReceiver_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAMQPReceiver_Expecter) Close(ctx any) *MockAMQPReceiver_Close_Call {
	return &MockAMQPReceiver_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockAMQPReceiver_Close_Call) Run(run func(ctx context.Context)) *MockAMQPReceiver_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAMQPReceiver_Close_Call) Return(err error) *MockAMQPReceiver_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAMQPReceiver_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockAMQPReceiver_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetTargetName provides a mock function for the type MockAMQPReceiver
func (_mock *MockAMQPReceiver) GetTargetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTargetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAMQPReceiver_GetTargetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTargetName'
type MockAMQPReceiver_GetTargetName_Call struct {
	*mock.Call
}

// GetTargetName is a helper method to define mock.On call
func (_e *MockAMQPReceiver_Expecter) GetTargetName() *MockAMQPReceiver_GetTargetName_Call {
	return &MockAMQPReceiver_GetTargetName_Call{Call: _e.mock.On("GetTargetName")}
}

func (_c *MockAMQPReceiver_GetTargetName_Call) Run(run func()) *MockAMQPReceiver_GetTargetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAMQPReceiver_GetTargetName_Call) Return(s string) *MockAMQPReceiver_GetTargetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAMQPReceiver_GetTargetName_Call) RunAndReturn(run func() string) *MockAMQPReceiver_GetTargetName_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type MockAMQPReceiver
func (_mock *MockAMQPReceiver) Receive(ctx context.Context) (broker.Message, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 broker.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (broker.Message, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) broker.Message); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(broker.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAMQPReceiver_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockAMQPReceiver_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAMQPReceiver_Expecter) Receive(ctx any) *MockAMQPReceiver_Receive_Call {
	return &MockAMQPReceiver_Receive_Call{Call: _e.mock.On("Receive", ctx)}
}

func (_c *MockAMQPReceiver_Receive_Call) Run(run func(ctx context.Context)) *MockAMQPReceiver_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAMQPReceiver_Receive_Call) Return(message broker.Message, err error) *MockAMQPReceiver_Receive_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockAMQPReceiver_Receive_Call) RunAndReturn(run func(ctx context.Context) (broker.Message, error)) *MockAMQPReceiver_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// ReceiveWithOpts provides a mock function for the type MockAMQPReceiver
func (_mock *MockAMQPReceiver) ReceiveWithOpts(ctx context.Context, opts *amqp.ReceiveOptions) (broker.Message, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveWithOpts")
	}

	var r0 broker.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.ReceiveOptions) (broker.Message, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.ReceiveOptions) broker.Message); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(broker.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *amqp.ReceiveOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAMQPReceiver_ReceiveWithOpts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceiveWithOpts'
type MockAMQPReceiver_ReceiveWithOpts_Call struct {
	*mock.Call
}

// ReceiveWithOpts is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *amqp.ReceiveOptions
func (_e *MockAMQPReceiver_Expecter) ReceiveWithOpts(ctx any, opts any) *MockAMQPReceiver_ReceiveWithOpts_Call {
	return &MockAMQPReceiver_ReceiveWithOpts_Call{Call: _e.mock.On("ReceiveWithOpts", ctx, opts)}
}

func (_c *MockAMQPReceiver_ReceiveWithOpts_Call) Run(run func(ctx context.Context, opts *amqp.ReceiveOptions)) *MockAMQPReceiver_ReceiveWithOpts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *amqp.ReceiveOptions
		if args[1] != nil {
			arg1 = args[1].(*amqp.ReceiveOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAMQPReceiver_ReceiveWithOpts_Call) Return(message broker.Message, err error) *MockAMQPReceiver_ReceiveWithOpts_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockAMQPReceiver_ReceiveWithOpts_Call) RunAndReturn(run func(ctx context.Context, opts *amqp.ReceiveOptions) (broker.Message, error)) *MockAMQPReceiver_ReceiveWithOpts_Call {
	_c.Call.Return(run)
	return _c
}

// Reject provides a mock function for the type MockAMQPReceiver
func (_mock *MockAMQPReceiver) Reject(ctx context.Context, msg broker.Message, err error) error {
	ret := _mock.Called(ctx, msg, err)

	if len(ret) == 0 {
		panic("no return value specified for Reject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.Message, error) error); ok {
		r0 = returnFunc(ctx, msg, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAMQPReceiver_Reject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reject'
type MockAMQPReceiver_Reject_Call struct {
	*mock.Call
}

// Reject is a helper method to define mock.On call
//   - ctx context.Context
//   - msg broker.Message
//   - err error
func (_e *MockAMQPReceiver_Expecter) Reject(ctx any, msg any, err any) *MockAMQPReceiver_Reject_Call {
	return &MockAMQPReceiver_Reject_Call{Call: _e.mock.On("Reject", ctx, msg, err)}
}

func (_c *MockAMQPReceiver_Reject_Call) Run(run func(ctx context.Context, msg broker.Message, err error)) *MockAMQPReceiver_Reject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 broker.Message
		if args[1] != nil {
			arg1 = args[1].(broker.Message)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAMQPReceiver_Reject_Call) Return(err1 error) *MockAMQPReceiver_Reject_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockAMQPReceiver_Reject_Call) RunAndReturn(run func(ctx context.Context, msg broker.Message, err error) error) *MockAMQPReceiver_Reject_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type MockAMQPReceiver
func (_mock *MockAMQPReceiver) Release(ctx context.Context, msg broker.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, broker.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAMQPReceiver_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockAMQPReceiver_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - msg broker.Message
func (_e *MockAMQPReceiver_Expecter) Release(ctx any, msg any) *MockAMQPReceiver_Release_Call {
	return &MockAMQPReceiver_Release_Call{Call: _e.mock.On("Release", ctx, msg)}
}

func (_c *MockAMQPReceiver_Release_Call) Run(run func(ctx context.Context, msg broker.Message)) *MockAMQPReceiver_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 broker.Message
		if args[1] != nil {
			arg1 = args[1].(broker.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAMQPReceiver_Release_Call) Return(err error) *MockAMQPReceiver_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAMQPReceiver_Release_Call) RunAndReturn(run func(ctx context.Context, msg broker.Message) error) *MockAMQPReceiver_Release_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockAMQPReceiver
func (_mock *MockAMQPReceiver) Stats() broker.ReceiverStats {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 broker.ReceiverStats
	if returnFunc, ok := ret.Get(0).(func() broker.ReceiverStats); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(broker.ReceiverStats)
	}
	return r0
}

// MockAMQPReceiver_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockAMQPReceiver_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockAMQPReceiver_Expecter) Stats() *MockAMQPReceiver_Stats_Call {
	return &MockAMQPReceiver_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockAMQPReceiver_Stats_Call) Run(run func()) *MockAMQPReceiver_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAMQPReceiver_Stats_Call) Return(receiverStats broker.ReceiverStats) *MockAMQPReceiver_Stats_Call {
	_c.Call.Return(receiverStats)
	return _c
}

func (_c *MockAMQPReceiver_Stats_Call) RunAndReturn(run func() broker.ReceiverStats) *MockAMQPReceiver_Stats_Call {
	_c.Call.Return(run)
	return _c
}
