// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Azure/go-amqp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSenderLink creates a new instance of MockSenderLink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSenderLink(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSenderLink {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSenderLink{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSenderLink is an autogenerated mock type for the SenderLink type
type MockSenderLink struct {
	mock.Mock
}

type MockSenderLink_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSenderLink) EXPECT() *MockSenderLink_Expecter {
	return &MockSenderLink_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockSenderLink
func (_mock *MockSenderLink) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSenderLink_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSenderLink_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSenderLink_Expecter) Close(ctx any) *MockSenderLink_Close_Call {
	return &MockSenderLink_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockSenderLink_Close_Call) Run(run func(ctx context.Context)) *MockSenderLink_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSenderLink_Close_Call) Return(err error) *MockSenderLink_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSenderLink_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockSenderLink_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockSenderLink
func (_mock *MockSenderLink) Send(ctx context.Context, msg *amqp.Message, opts *amqp.SendOptions) error {
	ret := _mock.Called(ctx, msg, opts)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.Message, *amqp.SendOptions) error); ok {
		r0 = returnFunc(ctx, msg, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSenderLink_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSenderLink_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *amqp.Message
//   - opts *amqp.SendOptions
func (_e *MockSenderLink_Expecter) Send(ctx any, msg any, opts any) *MockSenderLink_Send_Call {
	return &MockSenderLink_Send_Call{Call: _e.mock.On("Send", ctx, msg, opts)}
}

func (_c *MockSenderLink_Send_Call) Run(run func(ctx context.Context, msg *amqp.Message, opts *amqp.SendOptions)) *MockSenderLink_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *amqp.Message
		if args[1] != nil {
			arg1 = args[1].(*amqp.Message)
		}
		var arg2 *amqp.SendOptions
		if args[2] != nil {
			arg2 = args[2].(*amqp.SendOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSenderLink_Send_Call) Return(err error) *MockSenderLink_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSenderLink_Send_Call) RunAndReturn(run func(ctx context.Context, msg *amqp.Message, opts *amqp.SendOptions) error) *MockSenderLink_Send_Call {
	_c.Call.Return(run)
	return _c
}
