// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage[K comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage[K] {
	mock := &MockStorage[K]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage[K comparable] struct {
	mock.Mock
}

type MockStorage_Expecter[K comparable] struct {
	mock *mock.Mock
}

func (_m *MockStorage[K]) EXPECT() *MockStorage_Expecter[K] {
	return &MockStorage_Expecter[K]{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockStorage
func (_mock *MockStorage[K]) Clear() {
	_mock.Called()
	return
}

// MockStorage_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockStorage_Clear_Call[K comparable] struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockStorage_Expecter[K]) Clear() *MockStorage_Clear_Call[K] {
	return &MockStorage_Clear_Call[K]{Call: _e.mock.On("Clear")}
}

func (_c *MockStorage_Clear_Call[K]) Run(run func()) *MockStorage_Clear_Call[K] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Clear_Call[K]) Return() *MockStorage_Clear_Call[K] {
	_c.Call.Return()
	return _c
}

func (_c *MockStorage_Clear_Call[K]) RunAndReturn(run func()) *MockStorage_Clear_Call[K] {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type MockStorage
func (_mock *MockStorage[K]) Delete(key K) {
	_mock.Called(key)
	return
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call[K comparable] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key K
func (_e *MockStorage_Expecter[K]) Delete(key interface{}) *MockStorage_Delete_Call[K] {
	return &MockStorage_Delete_Call[K]{Call: _e.mock.On("Delete", key)}
}

func (_c *MockStorage_Delete_Call[K]) Run(run func(key K)) *MockStorage_Delete_Call[K] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Delete_Call[K]) Return() *MockStorage_Delete_Call[K] {
	_c.Call.Return()
	return _c
}

func (_c *MockStorage_Delete_Call[K]) RunAndReturn(run func(key K)) *MockStorage_Delete_Call[K] {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockStorage
func (_mock *MockStorage[K]) Get(key K) ([]byte, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(K) ([]byte, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(K) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(K) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call[K comparable] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key K
func (_e *MockStorage_Expecter[K]) Get(key interface{}) *MockStorage_Get_Call[K] {
	return &MockStorage_Get_Call[K]{Call: _e.mock.On("Get", key)}
}

func (_c *MockStorage_Get_Call[K]) Run(run func(key K)) *MockStorage_Get_Call[K] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Get_Call[K]) Return(bytes []byte, b bool) *MockStorage_Get_Call[K] {
	_c.Call.Return(bytes, b)
	return _c
}

func (_c *MockStorage_Get_Call[K]) RunAndReturn(run func(key K) ([]byte, bool)) *MockStorage_Get_Call[K] {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type MockStorage
func (_mock *MockStorage[K]) Has(key K) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(K) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockStorage_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockStorage_Has_Call[K comparable] struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - key K
func (_e *MockStorage_Expecter[K]) Has(key interface{}) *MockStorage_Has_Call[K] {
	return &MockStorage_Has_Call[K]{Call: _e.mock.On("Has", key)}
}

func (_c *MockStorage_Has_Call[K]) Run(run func(key K)) *MockStorage_Has_Call[K] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Has_Call[K]) Return(b bool) *MockStorage_Has_Call[K] {
	_c.Call.Return(b)
	return _c
}

func (_c *MockStorage_Has_Call[K]) RunAndReturn(run func(key K) bool) *MockStorage_Has_Call[K] {
	_c.Call.Return(run)
	return _c
}

// Len provides a mock function for the type MockStorage
func (_mock *MockStorage[K]) Len() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockStorage_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockStorage_Len_Call[K comparable] struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockStorage_Expecter[K]) Len() *MockStorage_Len_Call[K] {
	return &MockStorage_Len_Call[K]{Call: _e.mock.On("Len")}
}

func (_c *MockStorage_Len_Call[K]) Run(run func()) *MockStorage_Len_Call[K] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Len_Call[K]) Return(n int) *MockStorage_Len_Call[K] {
	_c.Call.Return(n)
	return _c
}

func (_c *MockStorage_Len_Call[K]) RunAndReturn(run func() int) *MockStorage_Len_Call[K] {
	_c.Call.Return(run)
	return _c
}

// Range provides a mock function for the type MockStorage
func (_mock *MockStorage[K]) Range(fn func(key K, value []byte) bool) {
	_mock.Called(fn)
	return
}

// MockStorage_Range_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Range'
type MockStorage_Range_Call[K comparable] struct {
	*mock.Call
}

// Range is a helper method to define mock.On call
//   - fn func(key K, value []byte) bool
func (_e *MockStorage_Expecter[K]) Range(fn interface{}) *MockStorage_Range_Call[K] {
	return &MockStorage_Range_Call[K]{Call: _e.mock.On("Range", fn)}
}

func (_c *MockStorage_Range_Call[K]) Run(run func(fn func(key K, value []byte) bool)) *MockStorage_Range_Call[K] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(key K, value []byte) bool
		if args[0] != nil {
			arg0 = args[0].(func(key K, value []byte) bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Range_Call[K]) Return() *MockStorage_Range_Call[K] {
	_c.Call.Return()
	return _c
}

func (_c *MockStorage_Range_Call[K]) RunAndReturn(run func(fn func(key K, value []byte) bool)) *MockStorage_Range_Call[K] {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type MockStorage
func (_mock *MockStorage[K]) Set(key K, b []byte) {
	_mock.Called(key, b)
	return
}

// MockStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStorage_Set_Call[K comparable] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key K
//   - b []byte
func (_e *MockStorage_Expecter[K]) Set(key interface{}, b interface{}) *MockStorage_Set_Call[K] {
	return &MockStorage_Set_Call[K]{Call: _e.mock.On("Set", key, b)}
}

func (_c *MockStorage_Set_Call[K]) Run(run func(key K, b []byte)) *MockStorage_Set_Call[K] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_Set_Call[K]) Return() *MockStorage_Set_Call[K] {
	_c.Call.Return()
	return _c
}

func (_c *MockStorage_Set_Call[K]) RunAndReturn(run func(key K, b []byte)) *MockStorage_Set_Call[K] {
	_c.Run(run)
	return _c
}
