// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache[K comparable, V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache[K, V] {
	mock := &MockCache[K, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache[K comparable, V any] struct {
	mock.Mock
}

type MockCache_Expecter[K comparable, V any] struct {
	mock *mock.Mock
}

func (_m *MockCache[K, V]) EXPECT() *MockCache_Expecter[K, V] {
	return &MockCache_Expecter[K, V]{mock: &_m.Mock}
}

// CacheJanitor provides a mock function for the type MockCache
func (_mock *MockCache[K, V]) CacheJanitor(ctx context.Context, eventTime time.Time) error {
	ret := _mock.Called(ctx, eventTime)

	if len(ret) == 0 {
		panic("no return value specified for CacheJanitor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = returnFunc(ctx, eventTime)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_CacheJanitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheJanitor'
type MockCache_CacheJanitor_Call[K comparable, V any] struct {
	*mock.Call
}

// CacheJanitor is a helper method to define mock.On call
//   - ctx context.Context
//   - eventTime time.Time
func (_e *MockCache_Expecter[K, V]) CacheJanitor(ctx interface{}, eventTime interface{}) *MockCache_CacheJanitor_Call[K, V] {
	return &MockCache_CacheJanitor_Call[K, V]{Call: _e.mock.On("CacheJanitor", ctx, eventTime)}
}

func (_c *MockCache_CacheJanitor_Call[K, V]) Run(run func(ctx context.Context, eventTime time.Time)) *MockCache_CacheJanitor_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_CacheJanitor_Call[K, V]) Return(err error) *MockCache_CacheJanitor_Call[K, V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_CacheJanitor_Call[K, V]) RunAndReturn(run func(ctx context.Context, eventTime time.Time) error) *MockCache_CacheJanitor_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// Clear provides a mock function for the type MockCache
func (_mock *MockCache[K, V]) Clear() {
	_mock.Called()
	return
}

// MockCache_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockCache_Clear_Call[K comparable, V any] struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockCache_Expecter[K, V]) Clear() *MockCache_Clear_Call[K, V] {
	return &MockCache_Clear_Call[K, V]{Call: _e.mock.On("Clear")}
}

func (_c *MockCache_Clear_Call[K, V]) Run(run func()) *MockCache_Clear_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Clear_Call[K, V]) Return() *MockCache_Clear_Call[K, V] {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Clear_Call[K, V]) RunAndReturn(run func()) *MockCache_Clear_Call[K, V] {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type MockCache
func (_mock *MockCache[K, V]) Delete(key K) {
	_mock.Called(key)
	return
}

// MockCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCache_Delete_Call[K comparable, V any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key K
func (_e *MockCache_Expecter[K, V]) Delete(key interface{}) *MockCache_Delete_Call[K, V] {
	return &MockCache_Delete_Call[K, V]{Call: _e.mock.On("Delete", key)}
}

func (_c *MockCache_Delete_Call[K, V]) Run(run func(key K)) *MockCache_Delete_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCache_Delete_Call[K, V]) Return() *MockCache_Delete_Call[K, V] {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Delete_Call[K, V]) RunAndReturn(run func(key K)) *MockCache_Delete_Call[K, V] {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockCache
func (_mock *MockCache[K, V]) Get(key K) (V, bool, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(K) (V, bool, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(K) V); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(K) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(K) error); ok {
		r2 = returnFunc(key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call[K comparable, V any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key K
func (_e *MockCache_Expecter[K, V]) Get(key interface{}) *MockCache_Get_Call[K, V] {
	return &MockCache_Get_Call[K, V]{Call: _e.mock.On("Get", key)}
}

func (_c *MockCache_Get_Call[K, V]) Run(run func(key K)) *MockCache_Get_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCache_Get_Call[K, V]) Return(v V, b bool, err error) *MockCache_Get_Call[K, V] {
	_c.Call.Return(v, b, err)
	return _c
}

func (_c *MockCache_Get_Call[K, V]) RunAndReturn(run func(key K) (V, bool, error)) *MockCache_Get_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCache
func (_mock *MockCache[K, V]) Set(key K, value V, ttl time.Duration) error {
	ret := _mock.Called(key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(K, V, time.Duration) error); ok {
		r0 = returnFunc(key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call[K comparable, V any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key K
//   - value V
//   - ttl time.Duration
func (_e *MockCache_Expecter[K, V]) Set(key interface{}, value interface{}, ttl interface{}) *MockCache_Set_Call[K, V] {
	return &MockCache_Set_Call[K, V]{Call: _e.mock.On("Set", key, value, ttl)}
}

func (_c *MockCache_Set_Call[K, V]) Run(run func(key K, value V, ttl time.Duration)) *MockCache_Set_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		var arg1 V
		if args[1] != nil {
			arg1 = args[1].(V)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_Set_Call[K, V]) Return(err error) *MockCache_Set_Call[K, V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Set_Call[K, V]) RunAndReturn(run func(key K, value V, ttl time.Duration) error) *MockCache_Set_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockCache
func (_mock *MockCache[K, V]) Size() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockCache_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockCache_Size_Call[K comparable, V any] struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockCache_Expecter[K, V]) Size() *MockCache_Size_Call[K, V] {
	return &MockCache_Size_Call[K, V]{Call: _e.mock.On("Size")}
}

func (_c *MockCache_Size_Call[K, V]) Run(run func()) *MockCache_Size_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Size_Call[K, V]) Return(n int) *MockCache_Size_Call[K, V] {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCache_Size_Call[K, V]) RunAndReturn(run func() int) *MockCache_Size_Call[K, V] {
	_c.Call.Return(run)
	return _c
}
