// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// GetQuerier provides a mock function for the type MockExecutor
func (_mock *MockExecutor) GetQuerier(ctx context.Context) db.Querier {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetQuerier")
	}

	var r0 db.Querier
	if returnFunc, ok := ret.Get(0).(func(context.Context) db.Querier); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(db.Querier)
		}
	}
	return r0
}

// MockExecutor_GetQuerier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuerier'
type MockExecutor_GetQuerier_Call struct {
	*mock.Call
}

// GetQuerier is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockExecutor_Expecter) GetQuerier(ctx interface{}) *MockExecutor_GetQuerier_Call {
	return &MockExecutor_GetQuerier_Call{Call: _e.mock.On("GetQuerier", ctx)}
}

func (_c *MockExecutor_GetQuerier_Call) Run(run func(ctx context.Context)) *MockExecutor_GetQuerier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExecutor_GetQuerier_Call) Return(querier db.Querier) *MockExecutor_GetQuerier_Call {
	_c.Call.Return(querier)
	return _c
}

func (_c *MockExecutor_GetQuerier_Call) RunAndReturn(run func(ctx context.Context) db.Querier) *MockExecutor_GetQuerier_Call {
	_c.Call.Return(run)
	return _c
}
