// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockErrorDecipher creates a new instance of MockErrorDecipher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorDecipher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorDecipher {
	mock := &MockErrorDecipher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockErrorDecipher is an autogenerated mock type for the ErrorDecipher type
type MockErrorDecipher struct {
	mock.Mock
}

type MockErrorDecipher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorDecipher) EXPECT() *MockErrorDecipher_Expecter {
	return &MockErrorDecipher_Expecter{mock: &_m.Mock}
}

// IsUniqueViolation provides a mock function for the type MockErrorDecipher
func (_mock *MockErrorDecipher) IsUniqueViolation(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsUniqueViolation")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockErrorDecipher_IsUniqueViolation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUniqueViolation'
type MockErrorDecipher_IsUniqueViolation_Call struct {
	*mock.Call
}

// IsUniqueViolation is a helper method to define mock.On call
//   - err error
func (_e *MockErrorDecipher_Expecter) IsUniqueViolation(err interface{}) *MockErrorDecipher_IsUniqueViolation_Call {
	return &MockErrorDecipher_IsUniqueViolation_Call{Call: _e.mock.On("IsUniqueViolation", err)}
}

func (_c *MockErrorDecipher_IsUniqueViolation_Call) Run(run func(err error)) *MockErrorDecipher_IsUniqueViolation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockErrorDecipher_IsUniqueViolation_Call) Return(b bool) *MockErrorDecipher_IsUniqueViolation_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockErrorDecipher_IsUniqueViolation_Call) RunAndReturn(run func(err error) bool) *MockErrorDecipher_IsUniqueViolation_Call {
	_c.Call.Return(run)
	return _c
}
