// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/go-service-template/pkg/api/http/example/v1/models"
)

// DeleteAPITestIDReader is a Reader for the DeleteAPITestID structure.
type DeleteAPITestIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPITestIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPITestIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteAPITestIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAPITestIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/test/{id}] DeleteAPITestID", response, response.Code())
	}
}

// NewDeleteAPITestIDNoContent creates a DeleteAPITestIDNoContent with default headers values
func NewDeleteAPITestIDNoContent() *DeleteAPITestIDNoContent {
	return &DeleteAPITestIDNoContent{}
}

/*
DeleteAPITestIDNoContent describes a response with status code 204, with default header values.

Запись успешно удалена, тело ответа отсутствует
*/
type DeleteAPITestIDNoContent struct {
}

// IsSuccess returns true when this delete Api test Id no content response has a 2xx status code
func (o *DeleteAPITestIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api test Id no content response has a 3xx status code
func (o *DeleteAPITestIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api test Id no content response has a 4xx status code
func (o *DeleteAPITestIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api test Id no content response has a 5xx status code
func (o *DeleteAPITestIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api test Id no content response a status code equal to that given
func (o *DeleteAPITestIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete Api test Id no content response
func (o *DeleteAPITestIDNoContent) Code() int {
	return 204
}

func (o *DeleteAPITestIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/test/{id}][%d] deleteApiTestIdNoContent", 204)
}

func (o *DeleteAPITestIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/test/{id}][%d] deleteApiTestIdNoContent", 204)
}

func (o *DeleteAPITestIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPITestIDNotFound creates a DeleteAPITestIDNotFound with default headers values
func NewDeleteAPITestIDNotFound() *DeleteAPITestIDNotFound {
	return &DeleteAPITestIDNotFound{}
}

/*
DeleteAPITestIDNotFound describes a response with status code 404, with default header values.

Запись не найдена
*/
type DeleteAPITestIDNotFound struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this delete Api test Id not found response has a 2xx status code
func (o *DeleteAPITestIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api test Id not found response has a 3xx status code
func (o *DeleteAPITestIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api test Id not found response has a 4xx status code
func (o *DeleteAPITestIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api test Id not found response has a 5xx status code
func (o *DeleteAPITestIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api test Id not found response a status code equal to that given
func (o *DeleteAPITestIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete Api test Id not found response
func (o *DeleteAPITestIDNotFound) Code() int {
	return 404
}

func (o *DeleteAPITestIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/test/{id}][%d] deleteApiTestIdNotFound %s", 404, payload)
}

func (o *DeleteAPITestIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/test/{id}][%d] deleteApiTestIdNotFound %s", 404, payload)
}

func (o *DeleteAPITestIDNotFound) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *DeleteAPITestIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAPITestIDInternalServerError creates a DeleteAPITestIDInternalServerError with default headers values
func NewDeleteAPITestIDInternalServerError() *DeleteAPITestIDInternalServerError {
	return &DeleteAPITestIDInternalServerError{}
}

/*
DeleteAPITestIDInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type DeleteAPITestIDInternalServerError struct {
}

// IsSuccess returns true when this delete Api test Id internal server error response has a 2xx status code
func (o *DeleteAPITestIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api test Id internal server error response has a 3xx status code
func (o *DeleteAPITestIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api test Id internal server error response has a 4xx status code
func (o *DeleteAPITestIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api test Id internal server error response has a 5xx status code
func (o *DeleteAPITestIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete Api test Id internal server error response a status code equal to that given
func (o *DeleteAPITestIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete Api test Id internal server error response
func (o *DeleteAPITestIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteAPITestIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api/test/{id}][%d] deleteApiTestIdInternalServerError", 500)
}

func (o *DeleteAPITestIDInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /api/test/{id}][%d] deleteApiTestIdInternalServerError", 500)
}

func (o *DeleteAPITestIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
