// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPITestIDParams creates a new DeleteAPITestIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPITestIDParams() *DeleteAPITestIDParams {
	return &DeleteAPITestIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPITestIDParamsWithTimeout creates a new DeleteAPITestIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPITestIDParamsWithTimeout(timeout time.Duration) *DeleteAPITestIDParams {
	return &DeleteAPITestIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPITestIDParamsWithContext creates a new DeleteAPITestIDParams object
// with the ability to set a context for a request.
func NewDeleteAPITestIDParamsWithContext(ctx context.Context) *DeleteAPITestIDParams {
	return &DeleteAPITestIDParams{
		Context: ctx,
	}
}

// NewDeleteAPITestIDParamsWithHTTPClient creates a new DeleteAPITestIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPITestIDParamsWithHTTPClient(client *http.Client) *DeleteAPITestIDParams {
	return &DeleteAPITestIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPITestIDParams contains all the parameters to send to the API endpoint

	for the delete API test ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPITestIDParams struct {

	/* ID.

	   ID записи

	   Format: string
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API test ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPITestIDParams) WithDefaults() *DeleteAPITestIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API test ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPITestIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API test ID params
func (o *DeleteAPITestIDParams) WithTimeout(timeout time.Duration) *DeleteAPITestIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API test ID params
func (o *DeleteAPITestIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API test ID params
func (o *DeleteAPITestIDParams) WithContext(ctx context.Context) *DeleteAPITestIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API test ID params
func (o *DeleteAPITestIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API test ID params
func (o *DeleteAPITestIDParams) WithHTTPClient(client *http.Client) *DeleteAPITestIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API test ID params
func (o *DeleteAPITestIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API test ID params
func (o *DeleteAPITestIDParams) WithID(id string) *DeleteAPITestIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API test ID params
func (o *DeleteAPITestIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPITestIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
