// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/go-service-template/pkg/api/http/example/v1/models"
)

// GetAPITestIDReader is a Reader for the GetAPITestID structure.
type GetAPITestIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPITestIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPITestIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetAPITestIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPITestIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/test/{id}] GetAPITestID", response, response.Code())
	}
}

// NewGetAPITestIDOK creates a GetAPITestIDOK with default headers values
func NewGetAPITestIDOK() *GetAPITestIDOK {
	return &GetAPITestIDOK{}
}

/*
GetAPITestIDOK describes a response with status code 200, with default header values.

Тестовые данные
*/
type GetAPITestIDOK struct {
	Payload *models.TestDTO
}

// IsSuccess returns true when this get Api test Id o k response has a 2xx status code
func (o *GetAPITestIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api test Id o k response has a 3xx status code
func (o *GetAPITestIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api test Id o k response has a 4xx status code
func (o *GetAPITestIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api test Id o k response has a 5xx status code
func (o *GetAPITestIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api test Id o k response a status code equal to that given
func (o *GetAPITestIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api test Id o k response
func (o *GetAPITestIDOK) Code() int {
	return 200
}

func (o *GetAPITestIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test/{id}][%d] getApiTestIdOK %s", 200, payload)
}

func (o *GetAPITestIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test/{id}][%d] getApiTestIdOK %s", 200, payload)
}

func (o *GetAPITestIDOK) GetPayload() *models.TestDTO {
	return o.Payload
}

func (o *GetAPITestIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TestDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPITestIDNotFound creates a GetAPITestIDNotFound with default headers values
func NewGetAPITestIDNotFound() *GetAPITestIDNotFound {
	return &GetAPITestIDNotFound{}
}

/*
GetAPITestIDNotFound describes a response with status code 404, with default header values.

Запись не найдена
*/
type GetAPITestIDNotFound struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this get Api test Id not found response has a 2xx status code
func (o *GetAPITestIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api test Id not found response has a 3xx status code
func (o *GetAPITestIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api test Id not found response has a 4xx status code
func (o *GetAPITestIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api test Id not found response has a 5xx status code
func (o *GetAPITestIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api test Id not found response a status code equal to that given
func (o *GetAPITestIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api test Id not found response
func (o *GetAPITestIDNotFound) Code() int {
	return 404
}

func (o *GetAPITestIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test/{id}][%d] getApiTestIdNotFound %s", 404, payload)
}

func (o *GetAPITestIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test/{id}][%d] getApiTestIdNotFound %s", 404, payload)
}

func (o *GetAPITestIDNotFound) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *GetAPITestIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPITestIDInternalServerError creates a GetAPITestIDInternalServerError with default headers values
func NewGetAPITestIDInternalServerError() *GetAPITestIDInternalServerError {
	return &GetAPITestIDInternalServerError{}
}

/*
GetAPITestIDInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type GetAPITestIDInternalServerError struct {
}

// IsSuccess returns true when this get Api test Id internal server error response has a 2xx status code
func (o *GetAPITestIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api test Id internal server error response has a 3xx status code
func (o *GetAPITestIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api test Id internal server error response has a 4xx status code
func (o *GetAPITestIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api test Id internal server error response has a 5xx status code
func (o *GetAPITestIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api test Id internal server error response a status code equal to that given
func (o *GetAPITestIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api test Id internal server error response
func (o *GetAPITestIDInternalServerError) Code() int {
	return 500
}

func (o *GetAPITestIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/test/{id}][%d] getApiTestIdInternalServerError", 500)
}

func (o *GetAPITestIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/test/{id}][%d] getApiTestIdInternalServerError", 500)
}

func (o *GetAPITestIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
