// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/go-service-template/pkg/api/http/example/v1/models"
)

// GetAPITestReader is a Reader for the GetAPITest structure.
type GetAPITestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPITestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPITestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPITestBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPITestInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/test] GetAPITest", response, response.Code())
	}
}

// NewGetAPITestOK creates a GetAPITestOK with default headers values
func NewGetAPITestOK() *GetAPITestOK {
	return &GetAPITestOK{}
}

/*
GetAPITestOK describes a response with status code 200, with default header values.

Набор тестовых данных
*/
type GetAPITestOK struct {
	Payload []*models.TestDTO
}

// IsSuccess returns true when this get Api test o k response has a 2xx status code
func (o *GetAPITestOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api test o k response has a 3xx status code
func (o *GetAPITestOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api test o k response has a 4xx status code
func (o *GetAPITestOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api test o k response has a 5xx status code
func (o *GetAPITestOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api test o k response a status code equal to that given
func (o *GetAPITestOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api test o k response
func (o *GetAPITestOK) Code() int {
	return 200
}

func (o *GetAPITestOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test][%d] getApiTestOK %s", 200, payload)
}

func (o *GetAPITestOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test][%d] getApiTestOK %s", 200, payload)
}

func (o *GetAPITestOK) GetPayload() []*models.TestDTO {
	return o.Payload
}

func (o *GetAPITestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPITestBadRequest creates a GetAPITestBadRequest with default headers values
func NewGetAPITestBadRequest() *GetAPITestBadRequest {
	return &GetAPITestBadRequest{}
}

/*
GetAPITestBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAPITestBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this get Api test bad request response has a 2xx status code
func (o *GetAPITestBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api test bad request response has a 3xx status code
func (o *GetAPITestBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api test bad request response has a 4xx status code
func (o *GetAPITestBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api test bad request response has a 5xx status code
func (o *GetAPITestBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api test bad request response a status code equal to that given
func (o *GetAPITestBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api test bad request response
func (o *GetAPITestBadRequest) Code() int {
	return 400
}

func (o *GetAPITestBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test][%d] getApiTestBadRequest %s", 400, payload)
}

func (o *GetAPITestBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test][%d] getApiTestBadRequest %s", 400, payload)
}

func (o *GetAPITestBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *GetAPITestBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPITestInternalServerError creates a GetAPITestInternalServerError with default headers values
func NewGetAPITestInternalServerError() *GetAPITestInternalServerError {
	return &GetAPITestInternalServerError{}
}

/*
GetAPITestInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type GetAPITestInternalServerError struct {
}

// IsSuccess returns true when this get Api test internal server error response has a 2xx status code
func (o *GetAPITestInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api test internal server error response has a 3xx status code
func (o *GetAPITestInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api test internal server error response has a 4xx status code
func (o *GetAPITestInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api test internal server error response has a 5xx status code
func (o *GetAPITestInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api test internal server error response a status code equal to that given
func (o *GetAPITestInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api test internal server error response
func (o *GetAPITestInternalServerError) Code() int {
	return 500
}

func (o *GetAPITestInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/test][%d] getApiTestInternalServerError", 500)
}

func (o *GetAPITestInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/test][%d] getApiTestInternalServerError", 500)
}

func (o *GetAPITestInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
