// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/go-service-template/pkg/api/http/example/v1/models"
)

// GetAPITestSearchReader is a Reader for the GetAPITestSearch structure.
type GetAPITestSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPITestSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPITestSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetAPITestSearchNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPITestSearchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/test/search] GetAPITestSearch", response, response.Code())
	}
}

// NewGetAPITestSearchOK creates a GetAPITestSearchOK with default headers values
func NewGetAPITestSearchOK() *GetAPITestSearchOK {
	return &GetAPITestSearchOK{}
}

/*
GetAPITestSearchOK describes a response with status code 200, with default header values.

Тестовые данные
*/
type GetAPITestSearchOK struct {
	Payload *models.TestDTO
}

// IsSuccess returns true when this get Api test search o k response has a 2xx status code
func (o *GetAPITestSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api test search o k response has a 3xx status code
func (o *GetAPITestSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api test search o k response has a 4xx status code
func (o *GetAPITestSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api test search o k response has a 5xx status code
func (o *GetAPITestSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api test search o k response a status code equal to that given
func (o *GetAPITestSearchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api test search o k response
func (o *GetAPITestSearchOK) Code() int {
	return 200
}

func (o *GetAPITestSearchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test/search][%d] getApiTestSearchOK %s", 200, payload)
}

func (o *GetAPITestSearchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test/search][%d] getApiTestSearchOK %s", 200, payload)
}

func (o *GetAPITestSearchOK) GetPayload() *models.TestDTO {
	return o.Payload
}

func (o *GetAPITestSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TestDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPITestSearchNotFound creates a GetAPITestSearchNotFound with default headers values
func NewGetAPITestSearchNotFound() *GetAPITestSearchNotFound {
	return &GetAPITestSearchNotFound{}
}

/*
GetAPITestSearchNotFound describes a response with status code 404, with default header values.

Запись не найдена
*/
type GetAPITestSearchNotFound struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this get Api test search not found response has a 2xx status code
func (o *GetAPITestSearchNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api test search not found response has a 3xx status code
func (o *GetAPITestSearchNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api test search not found response has a 4xx status code
func (o *GetAPITestSearchNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api test search not found response has a 5xx status code
func (o *GetAPITestSearchNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api test search not found response a status code equal to that given
func (o *GetAPITestSearchNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get Api test search not found response
func (o *GetAPITestSearchNotFound) Code() int {
	return 404
}

func (o *GetAPITestSearchNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test/search][%d] getApiTestSearchNotFound %s", 404, payload)
}

func (o *GetAPITestSearchNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/test/search][%d] getApiTestSearchNotFound %s", 404, payload)
}

func (o *GetAPITestSearchNotFound) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *GetAPITestSearchNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPITestSearchInternalServerError creates a GetAPITestSearchInternalServerError with default headers values
func NewGetAPITestSearchInternalServerError() *GetAPITestSearchInternalServerError {
	return &GetAPITestSearchInternalServerError{}
}

/*
GetAPITestSearchInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type GetAPITestSearchInternalServerError struct {
}

// IsSuccess returns true when this get Api test search internal server error response has a 2xx status code
func (o *GetAPITestSearchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api test search internal server error response has a 3xx status code
func (o *GetAPITestSearchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api test search internal server error response has a 4xx status code
func (o *GetAPITestSearchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api test search internal server error response has a 5xx status code
func (o *GetAPITestSearchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api test search internal server error response a status code equal to that given
func (o *GetAPITestSearchInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api test search internal server error response
func (o *GetAPITestSearchInternalServerError) Code() int {
	return 500
}

func (o *GetAPITestSearchInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/test/search][%d] getApiTestSearchInternalServerError", 500)
}

func (o *GetAPITestSearchInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/test/search][%d] getApiTestSearchInternalServerError", 500)
}

func (o *GetAPITestSearchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
