// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/go-service-template/pkg/api/http/example/v1/models"
)

// PutAPITestIDReader is a Reader for the PutAPITestID structure.
type PutAPITestIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPITestIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPITestIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAPITestIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAPITestIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewPutAPITestIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutAPITestIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /api/test/{id}] PutAPITestID", response, response.Code())
	}
}

// NewPutAPITestIDOK creates a PutAPITestIDOK with default headers values
func NewPutAPITestIDOK() *PutAPITestIDOK {
	return &PutAPITestIDOK{}
}

/*
PutAPITestIDOK describes a response with status code 200, with default header values.

OK
*/
type PutAPITestIDOK struct {
	Payload *models.TestDTO
}

// IsSuccess returns true when this put Api test Id o k response has a 2xx status code
func (o *PutAPITestIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put Api test Id o k response has a 3xx status code
func (o *PutAPITestIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api test Id o k response has a 4xx status code
func (o *PutAPITestIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api test Id o k response has a 5xx status code
func (o *PutAPITestIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api test Id o k response a status code equal to that given
func (o *PutAPITestIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put Api test Id o k response
func (o *PutAPITestIDOK) Code() int {
	return 200
}

func (o *PutAPITestIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/test/{id}][%d] putApiTestIdOK %s", 200, payload)
}

func (o *PutAPITestIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/test/{id}][%d] putApiTestIdOK %s", 200, payload)
}

func (o *PutAPITestIDOK) GetPayload() *models.TestDTO {
	return o.Payload
}

func (o *PutAPITestIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TestDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPITestIDBadRequest creates a PutAPITestIDBadRequest with default headers values
func NewPutAPITestIDBadRequest() *PutAPITestIDBadRequest {
	return &PutAPITestIDBadRequest{}
}

/*
PutAPITestIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutAPITestIDBadRequest struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this put Api test Id bad request response has a 2xx status code
func (o *PutAPITestIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api test Id bad request response has a 3xx status code
func (o *PutAPITestIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api test Id bad request response has a 4xx status code
func (o *PutAPITestIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put Api test Id bad request response has a 5xx status code
func (o *PutAPITestIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api test Id bad request response a status code equal to that given
func (o *PutAPITestIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put Api test Id bad request response
func (o *PutAPITestIDBadRequest) Code() int {
	return 400
}

func (o *PutAPITestIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/test/{id}][%d] putApiTestIdBadRequest %s", 400, payload)
}

func (o *PutAPITestIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/test/{id}][%d] putApiTestIdBadRequest %s", 400, payload)
}

func (o *PutAPITestIDBadRequest) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PutAPITestIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPITestIDNotFound creates a PutAPITestIDNotFound with default headers values
func NewPutAPITestIDNotFound() *PutAPITestIDNotFound {
	return &PutAPITestIDNotFound{}
}

/*
PutAPITestIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutAPITestIDNotFound struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this put Api test Id not found response has a 2xx status code
func (o *PutAPITestIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api test Id not found response has a 3xx status code
func (o *PutAPITestIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api test Id not found response has a 4xx status code
func (o *PutAPITestIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put Api test Id not found response has a 5xx status code
func (o *PutAPITestIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api test Id not found response a status code equal to that given
func (o *PutAPITestIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put Api test Id not found response
func (o *PutAPITestIDNotFound) Code() int {
	return 404
}

func (o *PutAPITestIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/test/{id}][%d] putApiTestIdNotFound %s", 404, payload)
}

func (o *PutAPITestIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/test/{id}][%d] putApiTestIdNotFound %s", 404, payload)
}

func (o *PutAPITestIDNotFound) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PutAPITestIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPITestIDConflict creates a PutAPITestIDConflict with default headers values
func NewPutAPITestIDConflict() *PutAPITestIDConflict {
	return &PutAPITestIDConflict{}
}

/*
PutAPITestIDConflict describes a response with status code 409, with default header values.

Conflict
*/
type PutAPITestIDConflict struct {
	Payload *models.ErrorDTO
}

// IsSuccess returns true when this put Api test Id conflict response has a 2xx status code
func (o *PutAPITestIDConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api test Id conflict response has a 3xx status code
func (o *PutAPITestIDConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api test Id conflict response has a 4xx status code
func (o *PutAPITestIDConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this put Api test Id conflict response has a 5xx status code
func (o *PutAPITestIDConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this put Api test Id conflict response a status code equal to that given
func (o *PutAPITestIDConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the put Api test Id conflict response
func (o *PutAPITestIDConflict) Code() int {
	return 409
}

func (o *PutAPITestIDConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/test/{id}][%d] putApiTestIdConflict %s", 409, payload)
}

func (o *PutAPITestIDConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /api/test/{id}][%d] putApiTestIdConflict %s", 409, payload)
}

func (o *PutAPITestIDConflict) GetPayload() *models.ErrorDTO {
	return o.Payload
}

func (o *PutAPITestIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPutAPITestIDInternalServerError creates a PutAPITestIDInternalServerError with default headers values
func NewPutAPITestIDInternalServerError() *PutAPITestIDInternalServerError {
	return &PutAPITestIDInternalServerError{}
}

/*
PutAPITestIDInternalServerError describes a response with status code 500, with default header values.

Внутренняя ошибка сервера (пустое тело)
*/
type PutAPITestIDInternalServerError struct {
}

// IsSuccess returns true when this put Api test Id internal server error response has a 2xx status code
func (o *PutAPITestIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put Api test Id internal server error response has a 3xx status code
func (o *PutAPITestIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put Api test Id internal server error response has a 4xx status code
func (o *PutAPITestIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put Api test Id internal server error response has a 5xx status code
func (o *PutAPITestIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put Api test Id internal server error response a status code equal to that given
func (o *PutAPITestIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put Api test Id internal server error response
func (o *PutAPITestIDInternalServerError) Code() int {
	return 500
}

func (o *PutAPITestIDInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /api/test/{id}][%d] putApiTestIdInternalServerError", 500)
}

func (o *PutAPITestIDInternalServerError) String() string {
	return fmt.Sprintf("[PUT /api/test/{id}][%d] putApiTestIdInternalServerError", 500)
}

func (o *PutAPITestIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
