// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ElfAstAhe/go-service-template/pkg/api/http/example/v1/models"
)

// NewPutAPITestIDParams creates a new PutAPITestIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPITestIDParams() *PutAPITestIDParams {
	return &PutAPITestIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPITestIDParamsWithTimeout creates a new PutAPITestIDParams object
// with the ability to set a timeout on a request.
func NewPutAPITestIDParamsWithTimeout(timeout time.Duration) *PutAPITestIDParams {
	return &PutAPITestIDParams{
		timeout: timeout,
	}
}

// NewPutAPITestIDParamsWithContext creates a new PutAPITestIDParams object
// with the ability to set a context for a request.
func NewPutAPITestIDParamsWithContext(ctx context.Context) *PutAPITestIDParams {
	return &PutAPITestIDParams{
		Context: ctx,
	}
}

// NewPutAPITestIDParamsWithHTTPClient creates a new PutAPITestIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPITestIDParamsWithHTTPClient(client *http.Client) *PutAPITestIDParams {
	return &PutAPITestIDParams{
		HTTPClient: client,
	}
}

/*
PutAPITestIDParams contains all the parameters to send to the API endpoint

	for the put API test ID operation.

	Typically these are written to a http.Request.
*/
type PutAPITestIDParams struct {

	/* ID.

	   ID записи

	   Format: string
	*/
	ID string

	/* Input.

	   Тестовые данные
	*/
	Input *models.TestDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API test ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPITestIDParams) WithDefaults() *PutAPITestIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API test ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPITestIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API test ID params
func (o *PutAPITestIDParams) WithTimeout(timeout time.Duration) *PutAPITestIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API test ID params
func (o *PutAPITestIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API test ID params
func (o *PutAPITestIDParams) WithContext(ctx context.Context) *PutAPITestIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API test ID params
func (o *PutAPITestIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API test ID params
func (o *PutAPITestIDParams) WithHTTPClient(client *http.Client) *PutAPITestIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API test ID params
func (o *PutAPITestIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put API test ID params
func (o *PutAPITestIDParams) WithID(id string) *PutAPITestIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put API test ID params
func (o *PutAPITestIDParams) SetID(id string) {
	o.ID = id
}

// WithInput adds the input to the put API test ID params
func (o *PutAPITestIDParams) WithInput(input *models.TestDTO) *PutAPITestIDParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the put API test ID params
func (o *PutAPITestIDParams) SetInput(input *models.TestDTO) {
	o.Input = input
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPITestIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
