// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new test API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new test API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new test API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for test API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteAPITestID(params *DeleteAPITestIDParams, opts ...ClientOption) (*DeleteAPITestIDNoContent, error)

	GetAPITest(params *GetAPITestParams, opts ...ClientOption) (*GetAPITestOK, error)

	GetAPITestID(params *GetAPITestIDParams, opts ...ClientOption) (*GetAPITestIDOK, error)

	GetAPITestSearch(params *GetAPITestSearchParams, opts ...ClientOption) (*GetAPITestSearchOK, error)

	PostAPITest(params *PostAPITestParams, opts ...ClientOption) (*PostAPITestCreated, error)

	PutAPITestID(params *PutAPITestIDParams, opts ...ClientOption) (*PutAPITestIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteAPITestID удалениеs тестовых данных

Удаляет запись по её ID
*/
func (a *Client) DeleteAPITestID(params *DeleteAPITestIDParams, opts ...ClientOption) (*DeleteAPITestIDNoContent, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewDeleteAPITestIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteAPITestID",
		Method:             "DELETE",
		PathPattern:        "/api/test/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteAPITestIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*DeleteAPITestIDNoContent)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteAPITestID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPITest получитьs

Удаляет запись по её ID (Soft Delete)
*/
func (a *Client) GetAPITest(params *GetAPITestParams, opts ...ClientOption) (*GetAPITestOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPITestParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPITest",
		Method:             "GET",
		PathPattern:        "/api/test",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPITestReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPITestOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPITest: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPITestID получитьs

Удаляет запись по её ID (Soft Delete)
*/
func (a *Client) GetAPITestID(params *GetAPITestIDParams, opts ...ClientOption) (*GetAPITestIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPITestIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPITestID",
		Method:             "GET",
		PathPattern:        "/api/test/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPITestIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPITestIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPITestID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetAPITestSearch получитьs

Удаляет запись по её ID (Soft Delete)
*/
func (a *Client) GetAPITestSearch(params *GetAPITestSearchParams, opts ...ClientOption) (*GetAPITestSearchOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewGetAPITestSearchParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetAPITestSearch",
		Method:             "GET",
		PathPattern:        "/api/test/search",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPITestSearchReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*GetAPITestSearchOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetAPITestSearch: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PostAPITest созданиеs новых тестовых данных

Сохраняет новые тестовые данные
*/
func (a *Client) PostAPITest(params *PostAPITestParams, opts ...ClientOption) (*PostAPITestCreated, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPostAPITestParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostAPITest",
		Method:             "POST",
		PathPattern:        "/api/test",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostAPITestReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PostAPITestCreated)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostAPITest: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
PutAPITestID изменениеs тестовых данных

Изменяет тестовые данные
*/
func (a *Client) PutAPITestID(params *PutAPITestIDParams, opts ...ClientOption) (*PutAPITestIDOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewPutAPITestIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PutAPITestID",
		Method:             "PUT",
		PathPattern:        "/api/test/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PutAPITestIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*PutAPITestIDOK)
	if ok {
		return success, nil
	}

	// unexpected success response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PutAPITestID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
