// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ElfAstAhe/go-service-template/pkg/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockLogger
func (_mock *MockLogger) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLogger_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockLogger_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockLogger_Expecter) Close() *MockLogger_Close_Call {
	return &MockLogger_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockLogger_Close_Call) Run(run func()) *MockLogger_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogger_Close_Call) Return(err error) *MockLogger_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLogger_Close_Call) RunAndReturn(run func() error) *MockLogger_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(args ...any) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - args ...any
func (_e *MockLogger_Expecter) Debug(args ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(args ...any)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(args ...any)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// DebugW provides a mock function for the type MockLogger
func (_mock *MockLogger) DebugW(msg string, keysAndValues ...any) {
	if len(keysAndValues) > 0 {
		_mock.Called(msg, keysAndValues)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_DebugW_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugW'
type MockLogger_DebugW_Call struct {
	*mock.Call
}

// DebugW is a helper method to define mock.On call
//   - msg string
//   - keysAndValues ...any
func (_e *MockLogger_Expecter) DebugW(msg interface{}, keysAndValues ...interface{}) *MockLogger_DebugW_Call {
	return &MockLogger_DebugW_Call{Call: _e.mock.On("DebugW",
		append([]interface{}{msg}, keysAndValues...)...)}
}

func (_c *MockLogger_DebugW_Call) Run(run func(msg string, keysAndValues ...any)) *MockLogger_DebugW_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_DebugW_Call) Return() *MockLogger_DebugW_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_DebugW_Call) RunAndReturn(run func(msg string, keysAndValues ...any)) *MockLogger_DebugW_Call {
	_c.Run(run)
	return _c
}

// Debugf provides a mock function for the type MockLogger
func (_mock *MockLogger) Debugf(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type MockLogger_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Debugf(format interface{}, args ...interface{}) *MockLogger_Debugf_Call {
	return &MockLogger_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Debugf_Call) Run(run func(format string, args ...any)) *MockLogger_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Debugf_Call) Return() *MockLogger_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debugf_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Debugf_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(args ...any) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - args ...any
func (_e *MockLogger_Expecter) Error(args ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(args ...any)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(args ...any)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// ErrorW provides a mock function for the type MockLogger
func (_mock *MockLogger) ErrorW(msg string, keysAndValues ...any) {
	if len(keysAndValues) > 0 {
		_mock.Called(msg, keysAndValues)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_ErrorW_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorW'
type MockLogger_ErrorW_Call struct {
	*mock.Call
}

// ErrorW is a helper method to define mock.On call
//   - msg string
//   - keysAndValues ...any
func (_e *MockLogger_Expecter) ErrorW(msg interface{}, keysAndValues ...interface{}) *MockLogger_ErrorW_Call {
	return &MockLogger_ErrorW_Call{Call: _e.mock.On("ErrorW",
		append([]interface{}{msg}, keysAndValues...)...)}
}

func (_c *MockLogger_ErrorW_Call) Run(run func(msg string, keysAndValues ...any)) *MockLogger_ErrorW_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_ErrorW_Call) Return() *MockLogger_ErrorW_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_ErrorW_Call) RunAndReturn(run func(msg string, keysAndValues ...any)) *MockLogger_ErrorW_Call {
	_c.Run(run)
	return _c
}

// Errorf provides a mock function for the type MockLogger
func (_mock *MockLogger) Errorf(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type MockLogger_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Errorf(format interface{}, args ...interface{}) *MockLogger_Errorf_Call {
	return &MockLogger_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Errorf_Call) Run(run func(format string, args ...any)) *MockLogger_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Errorf_Call) Return() *MockLogger_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Errorf_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Errorf_Call {
	_c.Run(run)
	return _c
}

// GetLogger provides a mock function for the type MockLogger
func (_mock *MockLogger) GetLogger(logicEntry string) logger.Logger {
	ret := _mock.Called(logicEntry)

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func(string) logger.Logger); ok {
		r0 = returnFunc(logicEntry)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// MockLogger_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type MockLogger_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
//   - logicEntry string
func (_e *MockLogger_Expecter) GetLogger(logicEntry interface{}) *MockLogger_GetLogger_Call {
	return &MockLogger_GetLogger_Call{Call: _e.mock.On("GetLogger", logicEntry)}
}

func (_c *MockLogger_GetLogger_Call) Run(run func(logicEntry string)) *MockLogger_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_GetLogger_Call) Return(logger1 logger.Logger) *MockLogger_GetLogger_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockLogger_GetLogger_Call) RunAndReturn(run func(logicEntry string) logger.Logger) *MockLogger_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(args ...any) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - args ...any
func (_e *MockLogger_Expecter) Info(args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(args ...any)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(args ...any)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// InfoW provides a mock function for the type MockLogger
func (_mock *MockLogger) InfoW(msg string, keysAndValues ...any) {
	if len(keysAndValues) > 0 {
		_mock.Called(msg, keysAndValues)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_InfoW_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoW'
type MockLogger_InfoW_Call struct {
	*mock.Call
}

// InfoW is a helper method to define mock.On call
//   - msg string
//   - keysAndValues ...any
func (_e *MockLogger_Expecter) InfoW(msg interface{}, keysAndValues ...interface{}) *MockLogger_InfoW_Call {
	return &MockLogger_InfoW_Call{Call: _e.mock.On("InfoW",
		append([]interface{}{msg}, keysAndValues...)...)}
}

func (_c *MockLogger_InfoW_Call) Run(run func(msg string, keysAndValues ...any)) *MockLogger_InfoW_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_InfoW_Call) Return() *MockLogger_InfoW_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_InfoW_Call) RunAndReturn(run func(msg string, keysAndValues ...any)) *MockLogger_InfoW_Call {
	_c.Run(run)
	return _c
}

// Infof provides a mock function for the type MockLogger
func (_mock *MockLogger) Infof(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type MockLogger_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Infof(format interface{}, args ...interface{}) *MockLogger_Infof_Call {
	return &MockLogger_Infof_Call{Call: _e.mock.On("Infof",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Infof_Call) Run(run func(format string, args ...any)) *MockLogger_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Infof_Call) Return() *MockLogger_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Infof_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Infof_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLogger
func (_mock *MockLogger) Warn(args ...any) {
	if len(args) > 0 {
		_mock.Called(args)
	} else {
		_mock.Called()
	}

	return
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - args ...any
func (_e *MockLogger_Expecter) Warn(args ...interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(args ...any)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(args ...any)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// WarnW provides a mock function for the type MockLogger
func (_mock *MockLogger) WarnW(msg string, keysAndValues ...any) {
	if len(keysAndValues) > 0 {
		_mock.Called(msg, keysAndValues)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_WarnW_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnW'
type MockLogger_WarnW_Call struct {
	*mock.Call
}

// WarnW is a helper method to define mock.On call
//   - msg string
//   - keysAndValues ...any
func (_e *MockLogger_Expecter) WarnW(msg interface{}, keysAndValues ...interface{}) *MockLogger_WarnW_Call {
	return &MockLogger_WarnW_Call{Call: _e.mock.On("WarnW",
		append([]interface{}{msg}, keysAndValues...)...)}
}

func (_c *MockLogger_WarnW_Call) Run(run func(msg string, keysAndValues ...any)) *MockLogger_WarnW_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_WarnW_Call) Return() *MockLogger_WarnW_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_WarnW_Call) RunAndReturn(run func(msg string, keysAndValues ...any)) *MockLogger_WarnW_Call {
	_c.Run(run)
	return _c
}

// Warnf provides a mock function for the type MockLogger
func (_mock *MockLogger) Warnf(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Warnf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnf'
type MockLogger_Warnf_Call struct {
	*mock.Call
}

// Warnf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Warnf(format interface{}, args ...interface{}) *MockLogger_Warnf_Call {
	return &MockLogger_Warnf_Call{Call: _e.mock.On("Warnf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Warnf_Call) Run(run func(format string, args ...any)) *MockLogger_Warnf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Warnf_Call) Return() *MockLogger_Warnf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warnf_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Warnf_Call {
	_c.Run(run)
	return _c
}
