// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSoftDeleteEntity creates a new instance of MockSoftDeleteEntity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSoftDeleteEntity[DEL any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSoftDeleteEntity[DEL] {
	mock := &MockSoftDeleteEntity[DEL]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSoftDeleteEntity is an autogenerated mock type for the SoftDeleteEntity type
type MockSoftDeleteEntity[DEL any] struct {
	mock.Mock
}

type MockSoftDeleteEntity_Expecter[DEL any] struct {
	mock *mock.Mock
}

func (_m *MockSoftDeleteEntity[DEL]) EXPECT() *MockSoftDeleteEntity_Expecter[DEL] {
	return &MockSoftDeleteEntity_Expecter[DEL]{mock: &_m.Mock}
}

// GetDeleted provides a mock function for the type MockSoftDeleteEntity
func (_mock *MockSoftDeleteEntity[DEL]) GetDeleted() DEL {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDeleted")
	}

	var r0 DEL
	if returnFunc, ok := ret.Get(0).(func() DEL); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(DEL)
		}
	}
	return r0
}

// MockSoftDeleteEntity_GetDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeleted'
type MockSoftDeleteEntity_GetDeleted_Call[DEL any] struct {
	*mock.Call
}

// GetDeleted is a helper method to define mock.On call
func (_e *MockSoftDeleteEntity_Expecter[DEL]) GetDeleted() *MockSoftDeleteEntity_GetDeleted_Call[DEL] {
	return &MockSoftDeleteEntity_GetDeleted_Call[DEL]{Call: _e.mock.On("GetDeleted")}
}

func (_c *MockSoftDeleteEntity_GetDeleted_Call[DEL]) Run(run func()) *MockSoftDeleteEntity_GetDeleted_Call[DEL] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSoftDeleteEntity_GetDeleted_Call[DEL]) Return(v DEL) *MockSoftDeleteEntity_GetDeleted_Call[DEL] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockSoftDeleteEntity_GetDeleted_Call[DEL]) RunAndReturn(run func() DEL) *MockSoftDeleteEntity_GetDeleted_Call[DEL] {
	_c.Call.Return(run)
	return _c
}

// IsDeleted provides a mock function for the type MockSoftDeleteEntity
func (_mock *MockSoftDeleteEntity[DEL]) IsDeleted() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDeleted")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSoftDeleteEntity_IsDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDeleted'
type MockSoftDeleteEntity_IsDeleted_Call[DEL any] struct {
	*mock.Call
}

// IsDeleted is a helper method to define mock.On call
func (_e *MockSoftDeleteEntity_Expecter[DEL]) IsDeleted() *MockSoftDeleteEntity_IsDeleted_Call[DEL] {
	return &MockSoftDeleteEntity_IsDeleted_Call[DEL]{Call: _e.mock.On("IsDeleted")}
}

func (_c *MockSoftDeleteEntity_IsDeleted_Call[DEL]) Run(run func()) *MockSoftDeleteEntity_IsDeleted_Call[DEL] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSoftDeleteEntity_IsDeleted_Call[DEL]) Return(b bool) *MockSoftDeleteEntity_IsDeleted_Call[DEL] {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSoftDeleteEntity_IsDeleted_Call[DEL]) RunAndReturn(run func() bool) *MockSoftDeleteEntity_IsDeleted_Call[DEL] {
	_c.Call.Return(run)
	return _c
}

// SetDeleted provides a mock function for the type MockSoftDeleteEntity
func (_mock *MockSoftDeleteEntity[DEL]) SetDeleted(deleted DEL) {
	_mock.Called(deleted)
	return
}

// MockSoftDeleteEntity_SetDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeleted'
type MockSoftDeleteEntity_SetDeleted_Call[DEL any] struct {
	*mock.Call
}

// SetDeleted is a helper method to define mock.On call
//   - deleted DEL
func (_e *MockSoftDeleteEntity_Expecter[DEL]) SetDeleted(deleted interface{}) *MockSoftDeleteEntity_SetDeleted_Call[DEL] {
	return &MockSoftDeleteEntity_SetDeleted_Call[DEL]{Call: _e.mock.On("SetDeleted", deleted)}
}

func (_c *MockSoftDeleteEntity_SetDeleted_Call[DEL]) Run(run func(deleted DEL)) *MockSoftDeleteEntity_SetDeleted_Call[DEL] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 DEL
		if args[0] != nil {
			arg0 = args[0].(DEL)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSoftDeleteEntity_SetDeleted_Call[DEL]) Return() *MockSoftDeleteEntity_SetDeleted_Call[DEL] {
	_c.Call.Return()
	return _c
}

func (_c *MockSoftDeleteEntity_SetDeleted_Call[DEL]) RunAndReturn(run func(deleted DEL)) *MockSoftDeleteEntity_SetDeleted_Call[DEL] {
	_c.Run(run)
	return _c
}
