// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOwnedRepository creates a new instance of MockOwnedRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOwnedRepository[T domain.Entity[ID], ID comparable, OwnerID comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOwnedRepository[T, ID, OwnerID] {
	mock := &MockOwnedRepository[T, ID, OwnerID]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOwnedRepository is an autogenerated mock type for the OwnedRepository type
type MockOwnedRepository[T domain.Entity[ID], ID comparable, OwnerID comparable] struct {
	mock.Mock
}

type MockOwnedRepository_Expecter[T domain.Entity[ID], ID comparable, OwnerID comparable] struct {
	mock *mock.Mock
}

func (_m *MockOwnedRepository[T, ID, OwnerID]) EXPECT() *MockOwnedRepository_Expecter[T, ID, OwnerID] {
	return &MockOwnedRepository_Expecter[T, ID, OwnerID]{mock: &_m.Mock}
}

// Change provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) Change(ctx context.Context, ownerID OwnerID, entity T) (T, error) {
	ret := _mock.Called(ctx, ownerID, entity)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, T) (T, error)); ok {
		return returnFunc(ctx, ownerID, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, T) T); ok {
		r0 = returnFunc(ctx, ownerID, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OwnerID, T) error); ok {
		r1 = returnFunc(ctx, ownerID, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockOwnedRepository_Change_Call[T domain.Entity[ID], ID comparable, OwnerID comparable] struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
//   - entity T
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) Change(ctx interface{}, ownerID interface{}, entity interface{}) *MockOwnedRepository_Change_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_Change_Call[T, ID, OwnerID]{Call: _e.mock.On("Change", ctx, ownerID, entity)}
}

func (_c *MockOwnedRepository_Change_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID, entity T)) *MockOwnedRepository_Change_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		var arg2 T
		if args[2] != nil {
			arg2 = args[2].(T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_Change_Call[T, ID, OwnerID]) Return(v T, err error) *MockOwnedRepository_Change_Call[T, ID, OwnerID] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockOwnedRepository_Change_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID, entity T) (T, error)) *MockOwnedRepository_Change_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) Create(ctx context.Context, ownerID OwnerID, entity T) (T, error) {
	ret := _mock.Called(ctx, ownerID, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, T) (T, error)); ok {
		return returnFunc(ctx, ownerID, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, T) T); ok {
		r0 = returnFunc(ctx, ownerID, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OwnerID, T) error); ok {
		r1 = returnFunc(ctx, ownerID, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOwnedRepository_Create_Call[T domain.Entity[ID], ID comparable, OwnerID comparable] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
//   - entity T
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) Create(ctx interface{}, ownerID interface{}, entity interface{}) *MockOwnedRepository_Create_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_Create_Call[T, ID, OwnerID]{Call: _e.mock.On("Create", ctx, ownerID, entity)}
}

func (_c *MockOwnedRepository_Create_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID, entity T)) *MockOwnedRepository_Create_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		var arg2 T
		if args[2] != nil {
			arg2 = args[2].(T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_Create_Call[T, ID, OwnerID]) Return(v T, err error) *MockOwnedRepository_Create_Call[T, ID, OwnerID] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockOwnedRepository_Create_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID, entity T) (T, error)) *MockOwnedRepository_Create_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) Delete(ctx context.Context, ownerID OwnerID, id ID) error {
	ret := _mock.Called(ctx, ownerID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, ID) error); ok {
		r0 = returnFunc(ctx, ownerID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOwnedRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOwnedRepository_Delete_Call[T domain.Entity[ID], ID comparable, OwnerID comparable] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
//   - id ID
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) Delete(ctx interface{}, ownerID interface{}, id interface{}) *MockOwnedRepository_Delete_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_Delete_Call[T, ID, OwnerID]{Call: _e.mock.On("Delete", ctx, ownerID, id)}
}

func (_c *MockOwnedRepository_Delete_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID, id ID)) *MockOwnedRepository_Delete_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		var arg2 ID
		if args[2] != nil {
			arg2 = args[2].(ID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_Delete_Call[T, ID, OwnerID]) Return(err error) *MockOwnedRepository_Delete_Call[T, ID, OwnerID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOwnedRepository_Delete_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID, id ID) error) *MockOwnedRepository_Delete_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) DeleteAll(ctx context.Context, ownerID OwnerID) error {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID) error); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOwnedRepository_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockOwnedRepository_DeleteAll_Call[T domain.Entity[ID], ID comparable, OwnerID comparable] struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) DeleteAll(ctx interface{}, ownerID interface{}) *MockOwnedRepository_DeleteAll_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_DeleteAll_Call[T, ID, OwnerID]{Call: _e.mock.On("DeleteAll", ctx, ownerID)}
}

func (_c *MockOwnedRepository_DeleteAll_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID)) *MockOwnedRepository_DeleteAll_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_DeleteAll_Call[T, ID, OwnerID]) Return(err error) *MockOwnedRepository_DeleteAll_Call[T, ID, OwnerID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOwnedRepository_DeleteAll_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID) error) *MockOwnedRepository_DeleteAll_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) Find(ctx context.Context, ownerID OwnerID, id ID) (T, error) {
	ret := _mock.Called(ctx, ownerID, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, ID) (T, error)); ok {
		return returnFunc(ctx, ownerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, ID) T); ok {
		r0 = returnFunc(ctx, ownerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OwnerID, ID) error); ok {
		r1 = returnFunc(ctx, ownerID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockOwnedRepository_Find_Call[T domain.Entity[ID], ID comparable, OwnerID comparable] struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
//   - id ID
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) Find(ctx interface{}, ownerID interface{}, id interface{}) *MockOwnedRepository_Find_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_Find_Call[T, ID, OwnerID]{Call: _e.mock.On("Find", ctx, ownerID, id)}
}

func (_c *MockOwnedRepository_Find_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID, id ID)) *MockOwnedRepository_Find_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		var arg2 ID
		if args[2] != nil {
			arg2 = args[2].(ID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_Find_Call[T, ID, OwnerID]) Return(v T, err error) *MockOwnedRepository_Find_Call[T, ID, OwnerID] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockOwnedRepository_Find_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID, id ID) (T, error)) *MockOwnedRepository_Find_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) List(ctx context.Context, ownerID OwnerID, limit int, offset int) ([]T, error) {
	ret := _mock.Called(ctx, ownerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, int, int) ([]T, error)); ok {
		return returnFunc(ctx, ownerID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, int, int) []T); ok {
		r0 = returnFunc(ctx, ownerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OwnerID, int, int) error); ok {
		r1 = returnFunc(ctx, ownerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOwnedRepository_List_Call[T domain.Entity[ID], ID comparable, OwnerID comparable] struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
//   - limit int
//   - offset int
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) List(ctx interface{}, ownerID interface{}, limit interface{}, offset interface{}) *MockOwnedRepository_List_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_List_Call[T, ID, OwnerID]{Call: _e.mock.On("List", ctx, ownerID, limit, offset)}
}

func (_c *MockOwnedRepository_List_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID, limit int, offset int)) *MockOwnedRepository_List_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_List_Call[T, ID, OwnerID]) Return(vs []T, err error) *MockOwnedRepository_List_Call[T, ID, OwnerID] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockOwnedRepository_List_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID, limit int, offset int) ([]T, error)) *MockOwnedRepository_List_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) ListAll(ctx context.Context, ownerID OwnerID) ([]T, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID) ([]T, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID) []T); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OwnerID) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockOwnedRepository_ListAll_Call[T domain.Entity[ID], ID comparable, OwnerID comparable] struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) ListAll(ctx interface{}, ownerID interface{}) *MockOwnedRepository_ListAll_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_ListAll_Call[T, ID, OwnerID]{Call: _e.mock.On("ListAll", ctx, ownerID)}
}

func (_c *MockOwnedRepository_ListAll_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID)) *MockOwnedRepository_ListAll_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_ListAll_Call[T, ID, OwnerID]) Return(vs []T, err error) *MockOwnedRepository_ListAll_Call[T, ID, OwnerID] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockOwnedRepository_ListAll_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID) ([]T, error)) *MockOwnedRepository_ListAll_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// ListAllByOwners provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) ListAllByOwners(ctx context.Context, ownerIDs ...OwnerID) (map[OwnerID][]T, error) {
	var tmpRet mock.Arguments
	if len(ownerIDs) > 0 {
		tmpRet = _mock.Called(ctx, ownerIDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListAllByOwners")
	}

	var r0 map[OwnerID][]T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...OwnerID) (map[OwnerID][]T, error)); ok {
		return returnFunc(ctx, ownerIDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...OwnerID) map[OwnerID][]T); ok {
		r0 = returnFunc(ctx, ownerIDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[OwnerID][]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...OwnerID) error); ok {
		r1 = returnFunc(ctx, ownerIDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_ListAllByOwners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllByOwners'
type MockOwnedRepository_ListAllByOwners_Call[T domain.Entity[ID], ID comparable, OwnerID comparable] struct {
	*mock.Call
}

// ListAllByOwners is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerIDs ...OwnerID
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) ListAllByOwners(ctx interface{}, ownerIDs ...interface{}) *MockOwnedRepository_ListAllByOwners_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_ListAllByOwners_Call[T, ID, OwnerID]{Call: _e.mock.On("ListAllByOwners",
		append([]interface{}{ctx}, ownerIDs...)...)}
}

func (_c *MockOwnedRepository_ListAllByOwners_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerIDs ...OwnerID)) *MockOwnedRepository_ListAllByOwners_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []OwnerID
		var variadicArgs []OwnerID
		if len(args) > 1 {
			variadicArgs = args[1].([]OwnerID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_ListAllByOwners_Call[T, ID, OwnerID]) Return(vToVs map[OwnerID][]T, err error) *MockOwnedRepository_ListAllByOwners_Call[T, ID, OwnerID] {
	_c.Call.Return(vToVs, err)
	return _c
}

func (_c *MockOwnedRepository_ListAllByOwners_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerIDs ...OwnerID) (map[OwnerID][]T, error)) *MockOwnedRepository_ListAllByOwners_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) Save(ctx context.Context, ownerID OwnerID, owned []T) ([]T, error) {
	ret := _mock.Called(ctx, ownerID, owned)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, []T) ([]T, error)); ok {
		return returnFunc(ctx, ownerID, owned)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, []T) []T); ok {
		r0 = returnFunc(ctx, ownerID, owned)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OwnerID, []T) error); ok {
		r1 = returnFunc(ctx, ownerID, owned)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOwnedRepository_Save_Call[T domain.Entity[ID], ID comparable, OwnerID comparable] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
//   - owned []T
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) Save(ctx interface{}, ownerID interface{}, owned interface{}) *MockOwnedRepository_Save_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_Save_Call[T, ID, OwnerID]{Call: _e.mock.On("Save", ctx, ownerID, owned)}
}

func (_c *MockOwnedRepository_Save_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID, owned []T)) *MockOwnedRepository_Save_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		var arg2 []T
		if args[2] != nil {
			arg2 = args[2].([]T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_Save_Call[T, ID, OwnerID]) Return(vs []T, err error) *MockOwnedRepository_Save_Call[T, ID, OwnerID] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockOwnedRepository_Save_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID, owned []T) ([]T, error)) *MockOwnedRepository_Save_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}
