// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository[T domain.Entity[ID], ID any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository[T, ID] {
	mock := &MockRepository[T, ID]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository[T domain.Entity[ID], ID any] struct {
	mock.Mock
}

type MockRepository_Expecter[T domain.Entity[ID], ID any] struct {
	mock *mock.Mock
}

func (_m *MockRepository[T, ID]) EXPECT() *MockRepository_Expecter[T, ID] {
	return &MockRepository_Expecter[T, ID]{mock: &_m.Mock}
}

// Change provides a mock function for the type MockRepository
func (_mock *MockRepository[T, ID]) Change(ctx context.Context, entity T) (T, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) (T, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) T); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockRepository_Change_Call[T domain.Entity[ID], ID any] struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx context.Context
//   - entity T
func (_e *MockRepository_Expecter[T, ID]) Change(ctx interface{}, entity interface{}) *MockRepository_Change_Call[T, ID] {
	return &MockRepository_Change_Call[T, ID]{Call: _e.mock.On("Change", ctx, entity)}
}

func (_c *MockRepository_Change_Call[T, ID]) Run(run func(ctx context.Context, entity T)) *MockRepository_Change_Call[T, ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Change_Call[T, ID]) Return(v T, err error) *MockRepository_Change_Call[T, ID] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_Change_Call[T, ID]) RunAndReturn(run func(ctx context.Context, entity T) (T, error)) *MockRepository_Change_Call[T, ID] {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockRepository
func (_mock *MockRepository[T, ID]) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRepository_Close_Call[T domain.Entity[ID], ID any] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRepository_Expecter[T, ID]) Close() *MockRepository_Close_Call[T, ID] {
	return &MockRepository_Close_Call[T, ID]{Call: _e.mock.On("Close")}
}

func (_c *MockRepository_Close_Call[T, ID]) Run(run func()) *MockRepository_Close_Call[T, ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Close_Call[T, ID]) Return(err error) *MockRepository_Close_Call[T, ID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Close_Call[T, ID]) RunAndReturn(run func() error) *MockRepository_Close_Call[T, ID] {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository[T, ID]) Create(ctx context.Context, entity T) (T, error) {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) (T, error)); ok {
		return returnFunc(ctx, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) T); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = returnFunc(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call[T domain.Entity[ID], ID any] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity T
func (_e *MockRepository_Expecter[T, ID]) Create(ctx interface{}, entity interface{}) *MockRepository_Create_Call[T, ID] {
	return &MockRepository_Create_Call[T, ID]{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockRepository_Create_Call[T, ID]) Run(run func(ctx context.Context, entity T)) *MockRepository_Create_Call[T, ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call[T, ID]) Return(v T, err error) *MockRepository_Create_Call[T, ID] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_Create_Call[T, ID]) RunAndReturn(run func(ctx context.Context, entity T) (T, error)) *MockRepository_Create_Call[T, ID] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository[T, ID]) Delete(ctx context.Context, id ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call[T domain.Entity[ID], ID any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id ID
func (_e *MockRepository_Expecter[T, ID]) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call[T, ID] {
	return &MockRepository_Delete_Call[T, ID]{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call[T, ID]) Run(run func(ctx context.Context, id ID)) *MockRepository_Delete_Call[T, ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ID
		if args[1] != nil {
			arg1 = args[1].(ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call[T, ID]) Return(err error) *MockRepository_Delete_Call[T, ID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call[T, ID]) RunAndReturn(run func(ctx context.Context, id ID) error) *MockRepository_Delete_Call[T, ID] {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockRepository
func (_mock *MockRepository[T, ID]) Find(ctx context.Context, id ID) (T, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ID) (T, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ID) T); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockRepository_Find_Call[T domain.Entity[ID], ID any] struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id ID
func (_e *MockRepository_Expecter[T, ID]) Find(ctx interface{}, id interface{}) *MockRepository_Find_Call[T, ID] {
	return &MockRepository_Find_Call[T, ID]{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockRepository_Find_Call[T, ID]) Run(run func(ctx context.Context, id ID)) *MockRepository_Find_Call[T, ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ID
		if args[1] != nil {
			arg1 = args[1].(ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Find_Call[T, ID]) Return(v T, err error) *MockRepository_Find_Call[T, ID] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_Find_Call[T, ID]) RunAndReturn(run func(ctx context.Context, id ID) (T, error)) *MockRepository_Find_Call[T, ID] {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository[T, ID]) List(ctx context.Context, limit int, offset int) ([]T, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]T, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []T); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call[T domain.Entity[ID], ID any] struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter[T, ID]) List(ctx interface{}, limit interface{}, offset interface{}) *MockRepository_List_Call[T, ID] {
	return &MockRepository_List_Call[T, ID]{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockRepository_List_Call[T, ID]) Run(run func(ctx context.Context, limit int, offset int)) *MockRepository_List_Call[T, ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call[T, ID]) Return(vs []T, err error) *MockRepository_List_Call[T, ID] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockRepository_List_Call[T, ID]) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]T, error)) *MockRepository_List_Call[T, ID] {
	_c.Call.Return(run)
	return _c
}
