// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEntity creates a new instance of MockEntity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEntity[ID any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEntity[ID] {
	mock := &MockEntity[ID]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEntity is an autogenerated mock type for the Entity type
type MockEntity[ID any] struct {
	mock.Mock
}

type MockEntity_Expecter[ID any] struct {
	mock *mock.Mock
}

func (_m *MockEntity[ID]) EXPECT() *MockEntity_Expecter[ID] {
	return &MockEntity_Expecter[ID]{mock: &_m.Mock}
}

// BeforeChange provides a mock function for the type MockEntity
func (_mock *MockEntity[ID]) BeforeChange() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeforeChange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntity_BeforeChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeforeChange'
type MockEntity_BeforeChange_Call[ID any] struct {
	*mock.Call
}

// BeforeChange is a helper method to define mock.On call
func (_e *MockEntity_Expecter[ID]) BeforeChange() *MockEntity_BeforeChange_Call[ID] {
	return &MockEntity_BeforeChange_Call[ID]{Call: _e.mock.On("BeforeChange")}
}

func (_c *MockEntity_BeforeChange_Call[ID]) Run(run func()) *MockEntity_BeforeChange_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEntity_BeforeChange_Call[ID]) Return(err error) *MockEntity_BeforeChange_Call[ID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntity_BeforeChange_Call[ID]) RunAndReturn(run func() error) *MockEntity_BeforeChange_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// BeforeCreate provides a mock function for the type MockEntity
func (_mock *MockEntity[ID]) BeforeCreate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeforeCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntity_BeforeCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeforeCreate'
type MockEntity_BeforeCreate_Call[ID any] struct {
	*mock.Call
}

// BeforeCreate is a helper method to define mock.On call
func (_e *MockEntity_Expecter[ID]) BeforeCreate() *MockEntity_BeforeCreate_Call[ID] {
	return &MockEntity_BeforeCreate_Call[ID]{Call: _e.mock.On("BeforeCreate")}
}

func (_c *MockEntity_BeforeCreate_Call[ID]) Run(run func()) *MockEntity_BeforeCreate_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEntity_BeforeCreate_Call[ID]) Return(err error) *MockEntity_BeforeCreate_Call[ID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntity_BeforeCreate_Call[ID]) RunAndReturn(run func() error) *MockEntity_BeforeCreate_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type MockEntity
func (_mock *MockEntity[ID]) GetID() ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 ID
	if returnFunc, ok := ret.Get(0).(func() ID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ID)
		}
	}
	return r0
}

// MockEntity_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockEntity_GetID_Call[ID any] struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockEntity_Expecter[ID]) GetID() *MockEntity_GetID_Call[ID] {
	return &MockEntity_GetID_Call[ID]{Call: _e.mock.On("GetID")}
}

func (_c *MockEntity_GetID_Call[ID]) Run(run func()) *MockEntity_GetID_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEntity_GetID_Call[ID]) Return(v ID) *MockEntity_GetID_Call[ID] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockEntity_GetID_Call[ID]) RunAndReturn(run func() ID) *MockEntity_GetID_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// IsExists provides a mock function for the type MockEntity
func (_mock *MockEntity[ID]) IsExists() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEntity_IsExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExists'
type MockEntity_IsExists_Call[ID any] struct {
	*mock.Call
}

// IsExists is a helper method to define mock.On call
func (_e *MockEntity_Expecter[ID]) IsExists() *MockEntity_IsExists_Call[ID] {
	return &MockEntity_IsExists_Call[ID]{Call: _e.mock.On("IsExists")}
}

func (_c *MockEntity_IsExists_Call[ID]) Run(run func()) *MockEntity_IsExists_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEntity_IsExists_Call[ID]) Return(b bool) *MockEntity_IsExists_Call[ID] {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEntity_IsExists_Call[ID]) RunAndReturn(run func() bool) *MockEntity_IsExists_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// SetID provides a mock function for the type MockEntity
func (_mock *MockEntity[ID]) SetID(id ID) {
	_mock.Called(id)
	return
}

// MockEntity_SetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetID'
type MockEntity_SetID_Call[ID any] struct {
	*mock.Call
}

// SetID is a helper method to define mock.On call
//   - id ID
func (_e *MockEntity_Expecter[ID]) SetID(id interface{}) *MockEntity_SetID_Call[ID] {
	return &MockEntity_SetID_Call[ID]{Call: _e.mock.On("SetID", id)}
}

func (_c *MockEntity_SetID_Call[ID]) Run(run func(id ID)) *MockEntity_SetID_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ID
		if args[0] != nil {
			arg0 = args[0].(ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntity_SetID_Call[ID]) Return() *MockEntity_SetID_Call[ID] {
	_c.Call.Return()
	return _c
}

func (_c *MockEntity_SetID_Call[ID]) RunAndReturn(run func(id ID)) *MockEntity_SetID_Call[ID] {
	_c.Run(run)
	return _c
}

// ValidateChange provides a mock function for the type MockEntity
func (_mock *MockEntity[ID]) ValidateChange() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValidateChange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntity_ValidateChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateChange'
type MockEntity_ValidateChange_Call[ID any] struct {
	*mock.Call
}

// ValidateChange is a helper method to define mock.On call
func (_e *MockEntity_Expecter[ID]) ValidateChange() *MockEntity_ValidateChange_Call[ID] {
	return &MockEntity_ValidateChange_Call[ID]{Call: _e.mock.On("ValidateChange")}
}

func (_c *MockEntity_ValidateChange_Call[ID]) Run(run func()) *MockEntity_ValidateChange_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEntity_ValidateChange_Call[ID]) Return(err error) *MockEntity_ValidateChange_Call[ID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntity_ValidateChange_Call[ID]) RunAndReturn(run func() error) *MockEntity_ValidateChange_Call[ID] {
	_c.Call.Return(run)
	return _c
}

// ValidateCreate provides a mock function for the type MockEntity
func (_mock *MockEntity[ID]) ValidateCreate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValidateCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntity_ValidateCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCreate'
type MockEntity_ValidateCreate_Call[ID any] struct {
	*mock.Call
}

// ValidateCreate is a helper method to define mock.On call
func (_e *MockEntity_Expecter[ID]) ValidateCreate() *MockEntity_ValidateCreate_Call[ID] {
	return &MockEntity_ValidateCreate_Call[ID]{Call: _e.mock.On("ValidateCreate")}
}

func (_c *MockEntity_ValidateCreate_Call[ID]) Run(run func()) *MockEntity_ValidateCreate_Call[ID] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEntity_ValidateCreate_Call[ID]) Return(err error) *MockEntity_ValidateCreate_Call[ID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntity_ValidateCreate_Call[ID]) RunAndReturn(run func() error) *MockEntity_ValidateCreate_Call[ID] {
	_c.Call.Return(run)
	return _c
}
