// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ElfAstAhe/go-service-template/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOwnedRepository creates a new instance of MockOwnedRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOwnedRepository[T domain.Entity[T], ID any, OwnerID comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOwnedRepository[T, ID, OwnerID] {
	mock := &MockOwnedRepository[T, ID, OwnerID]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOwnedRepository is an autogenerated mock type for the OwnedRepository type
type MockOwnedRepository[T domain.Entity[T], ID any, OwnerID comparable] struct {
	mock.Mock
}

type MockOwnedRepository_Expecter[T domain.Entity[T], ID any, OwnerID comparable] struct {
	mock *mock.Mock
}

func (_m *MockOwnedRepository[T, ID, OwnerID]) EXPECT() *MockOwnedRepository_Expecter[T, ID, OwnerID] {
	return &MockOwnedRepository_Expecter[T, ID, OwnerID]{mock: &_m.Mock}
}

// Change provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) Change(ctx context.Context, ownerID OwnerID, entity T) (T, error) {
	ret := _mock.Called(ctx, ownerID, entity)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, T) (T, error)); ok {
		return returnFunc(ctx, ownerID, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, T) T); ok {
		r0 = returnFunc(ctx, ownerID, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OwnerID, T) error); ok {
		r1 = returnFunc(ctx, ownerID, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockOwnedRepository_Change_Call[T domain.Entity[T], ID any, OwnerID comparable] struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
//   - entity T
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) Change(ctx interface{}, ownerID interface{}, entity interface{}) *MockOwnedRepository_Change_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_Change_Call[T, ID, OwnerID]{Call: _e.mock.On("Change", ctx, ownerID, entity)}
}

func (_c *MockOwnedRepository_Change_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID, entity T)) *MockOwnedRepository_Change_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		var arg2 T
		if args[2] != nil {
			arg2 = args[2].(T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_Change_Call[T, ID, OwnerID]) Return(v T, err error) *MockOwnedRepository_Change_Call[T, ID, OwnerID] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockOwnedRepository_Change_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID, entity T) (T, error)) *MockOwnedRepository_Change_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) Create(ctx context.Context, ownerID OwnerID, entity T) (T, error) {
	ret := _mock.Called(ctx, ownerID, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, T) (T, error)); ok {
		return returnFunc(ctx, ownerID, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, T) T); ok {
		r0 = returnFunc(ctx, ownerID, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OwnerID, T) error); ok {
		r1 = returnFunc(ctx, ownerID, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOwnedRepository_Create_Call[T domain.Entity[T], ID any, OwnerID comparable] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
//   - entity T
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) Create(ctx interface{}, ownerID interface{}, entity interface{}) *MockOwnedRepository_Create_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_Create_Call[T, ID, OwnerID]{Call: _e.mock.On("Create", ctx, ownerID, entity)}
}

func (_c *MockOwnedRepository_Create_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID, entity T)) *MockOwnedRepository_Create_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		var arg2 T
		if args[2] != nil {
			arg2 = args[2].(T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_Create_Call[T, ID, OwnerID]) Return(v T, err error) *MockOwnedRepository_Create_Call[T, ID, OwnerID] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockOwnedRepository_Create_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID, entity T) (T, error)) *MockOwnedRepository_Create_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) Delete(ctx context.Context, id ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOwnedRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOwnedRepository_Delete_Call[T domain.Entity[T], ID any, OwnerID comparable] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id ID
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) Delete(ctx interface{}, id interface{}) *MockOwnedRepository_Delete_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_Delete_Call[T, ID, OwnerID]{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockOwnedRepository_Delete_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, id ID)) *MockOwnedRepository_Delete_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ID
		if args[1] != nil {
			arg1 = args[1].(ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_Delete_Call[T, ID, OwnerID]) Return(err error) *MockOwnedRepository_Delete_Call[T, ID, OwnerID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOwnedRepository_Delete_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, id ID) error) *MockOwnedRepository_Delete_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// DeleteByOwner provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) DeleteByOwner(ctx context.Context, ownerID OwnerID) error {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByOwner")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID) error); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOwnedRepository_DeleteByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByOwner'
type MockOwnedRepository_DeleteByOwner_Call[T domain.Entity[T], ID any, OwnerID comparable] struct {
	*mock.Call
}

// DeleteByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) DeleteByOwner(ctx interface{}, ownerID interface{}) *MockOwnedRepository_DeleteByOwner_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_DeleteByOwner_Call[T, ID, OwnerID]{Call: _e.mock.On("DeleteByOwner", ctx, ownerID)}
}

func (_c *MockOwnedRepository_DeleteByOwner_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID)) *MockOwnedRepository_DeleteByOwner_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_DeleteByOwner_Call[T, ID, OwnerID]) Return(err error) *MockOwnedRepository_DeleteByOwner_Call[T, ID, OwnerID] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOwnedRepository_DeleteByOwner_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID) error) *MockOwnedRepository_DeleteByOwner_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) Find(ctx context.Context, id ID) (T, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ID) (T, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ID) T); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockOwnedRepository_Find_Call[T domain.Entity[T], ID any, OwnerID comparable] struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id ID
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) Find(ctx interface{}, id interface{}) *MockOwnedRepository_Find_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_Find_Call[T, ID, OwnerID]{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockOwnedRepository_Find_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, id ID)) *MockOwnedRepository_Find_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ID
		if args[1] != nil {
			arg1 = args[1].(ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_Find_Call[T, ID, OwnerID]) Return(v T, err error) *MockOwnedRepository_Find_Call[T, ID, OwnerID] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockOwnedRepository_Find_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, id ID) (T, error)) *MockOwnedRepository_Find_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// ListByOwner provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) ListByOwner(ctx context.Context, ownerID OwnerID) ([]T, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOwner")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID) ([]T, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID) []T); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OwnerID) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_ListByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOwner'
type MockOwnedRepository_ListByOwner_Call[T domain.Entity[T], ID any, OwnerID comparable] struct {
	*mock.Call
}

// ListByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) ListByOwner(ctx interface{}, ownerID interface{}) *MockOwnedRepository_ListByOwner_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_ListByOwner_Call[T, ID, OwnerID]{Call: _e.mock.On("ListByOwner", ctx, ownerID)}
}

func (_c *MockOwnedRepository_ListByOwner_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID)) *MockOwnedRepository_ListByOwner_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_ListByOwner_Call[T, ID, OwnerID]) Return(vs []T, err error) *MockOwnedRepository_ListByOwner_Call[T, ID, OwnerID] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockOwnedRepository_ListByOwner_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID) ([]T, error)) *MockOwnedRepository_ListByOwner_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// ListByOwners provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) ListByOwners(ctx context.Context, ownerIDs ...OwnerID) (map[OwnerID]T, error) {
	var tmpRet mock.Arguments
	if len(ownerIDs) > 0 {
		tmpRet = _mock.Called(ctx, ownerIDs)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListByOwners")
	}

	var r0 map[OwnerID]T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...OwnerID) (map[OwnerID]T, error)); ok {
		return returnFunc(ctx, ownerIDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...OwnerID) map[OwnerID]T); ok {
		r0 = returnFunc(ctx, ownerIDs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[OwnerID]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...OwnerID) error); ok {
		r1 = returnFunc(ctx, ownerIDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_ListByOwners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOwners'
type MockOwnedRepository_ListByOwners_Call[T domain.Entity[T], ID any, OwnerID comparable] struct {
	*mock.Call
}

// ListByOwners is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerIDs ...OwnerID
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) ListByOwners(ctx interface{}, ownerIDs ...interface{}) *MockOwnedRepository_ListByOwners_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_ListByOwners_Call[T, ID, OwnerID]{Call: _e.mock.On("ListByOwners",
		append([]interface{}{ctx}, ownerIDs...)...)}
}

func (_c *MockOwnedRepository_ListByOwners_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerIDs ...OwnerID)) *MockOwnedRepository_ListByOwners_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []OwnerID
		var variadicArgs []OwnerID
		if len(args) > 1 {
			variadicArgs = args[1].([]OwnerID)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_ListByOwners_Call[T, ID, OwnerID]) Return(vToV map[OwnerID]T, err error) *MockOwnedRepository_ListByOwners_Call[T, ID, OwnerID] {
	_c.Call.Return(vToV, err)
	return _c
}

func (_c *MockOwnedRepository_ListByOwners_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerIDs ...OwnerID) (map[OwnerID]T, error)) *MockOwnedRepository_ListByOwners_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}

// SaveByOwner provides a mock function for the type MockOwnedRepository
func (_mock *MockOwnedRepository[T, ID, OwnerID]) SaveByOwner(ctx context.Context, ownerID OwnerID, owned []T) ([]T, error) {
	ret := _mock.Called(ctx, ownerID, owned)

	if len(ret) == 0 {
		panic("no return value specified for SaveByOwner")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, []T) ([]T, error)); ok {
		return returnFunc(ctx, ownerID, owned)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, OwnerID, []T) []T); ok {
		r0 = returnFunc(ctx, ownerID, owned)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, OwnerID, []T) error); ok {
		r1 = returnFunc(ctx, ownerID, owned)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOwnedRepository_SaveByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveByOwner'
type MockOwnedRepository_SaveByOwner_Call[T domain.Entity[T], ID any, OwnerID comparable] struct {
	*mock.Call
}

// SaveByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID OwnerID
//   - owned []T
func (_e *MockOwnedRepository_Expecter[T, ID, OwnerID]) SaveByOwner(ctx interface{}, ownerID interface{}, owned interface{}) *MockOwnedRepository_SaveByOwner_Call[T, ID, OwnerID] {
	return &MockOwnedRepository_SaveByOwner_Call[T, ID, OwnerID]{Call: _e.mock.On("SaveByOwner", ctx, ownerID, owned)}
}

func (_c *MockOwnedRepository_SaveByOwner_Call[T, ID, OwnerID]) Run(run func(ctx context.Context, ownerID OwnerID, owned []T)) *MockOwnedRepository_SaveByOwner_Call[T, ID, OwnerID] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 OwnerID
		if args[1] != nil {
			arg1 = args[1].(OwnerID)
		}
		var arg2 []T
		if args[2] != nil {
			arg2 = args[2].([]T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOwnedRepository_SaveByOwner_Call[T, ID, OwnerID]) Return(vs []T, err error) *MockOwnedRepository_SaveByOwner_Call[T, ID, OwnerID] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockOwnedRepository_SaveByOwner_Call[T, ID, OwnerID]) RunAndReturn(run func(ctx context.Context, ownerID OwnerID, owned []T) ([]T, error)) *MockOwnedRepository_SaveByOwner_Call[T, ID, OwnerID] {
	_c.Call.Return(run)
	return _c
}
