// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Azure/go-amqp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAmqpReceiverLink creates a new instance of MockAmqpReceiverLink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAmqpReceiverLink(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAmqpReceiverLink {
	mock := &MockAmqpReceiverLink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAmqpReceiverLink is an autogenerated mock type for the AmqpReceiverLink type
type MockAmqpReceiverLink struct {
	mock.Mock
}

type MockAmqpReceiverLink_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAmqpReceiverLink) EXPECT() *MockAmqpReceiverLink_Expecter {
	return &MockAmqpReceiverLink_Expecter{mock: &_m.Mock}
}

// AcceptMessage provides a mock function for the type MockAmqpReceiverLink
func (_mock *MockAmqpReceiverLink) AcceptMessage(ctx context.Context, msg *amqp.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for AcceptMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAmqpReceiverLink_AcceptMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptMessage'
type MockAmqpReceiverLink_AcceptMessage_Call struct {
	*mock.Call
}

// AcceptMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *amqp.Message
func (_e *MockAmqpReceiverLink_Expecter) AcceptMessage(ctx any, msg any) *MockAmqpReceiverLink_AcceptMessage_Call {
	return &MockAmqpReceiverLink_AcceptMessage_Call{Call: _e.mock.On("AcceptMessage", ctx, msg)}
}

func (_c *MockAmqpReceiverLink_AcceptMessage_Call) Run(run func(ctx context.Context, msg *amqp.Message)) *MockAmqpReceiverLink_AcceptMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *amqp.Message
		if args[1] != nil {
			arg1 = args[1].(*amqp.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAmqpReceiverLink_AcceptMessage_Call) Return(err error) *MockAmqpReceiverLink_AcceptMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAmqpReceiverLink_AcceptMessage_Call) RunAndReturn(run func(ctx context.Context, msg *amqp.Message) error) *MockAmqpReceiverLink_AcceptMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockAmqpReceiverLink
func (_mock *MockAmqpReceiverLink) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAmqpReceiverLink_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockAmqpReceiverLink_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAmqpReceiverLink_Expecter) Close(ctx any) *MockAmqpReceiverLink_Close_Call {
	return &MockAmqpReceiverLink_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockAmqpReceiverLink_Close_Call) Run(run func(ctx context.Context)) *MockAmqpReceiverLink_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAmqpReceiverLink_Close_Call) Return(err error) *MockAmqpReceiverLink_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAmqpReceiverLink_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockAmqpReceiverLink_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type MockAmqpReceiverLink
func (_mock *MockAmqpReceiverLink) Receive(ctx context.Context, opts *amqp.ReceiveOptions) (*amqp.Message, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 *amqp.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.ReceiveOptions) (*amqp.Message, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.ReceiveOptions) *amqp.Message); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *amqp.ReceiveOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAmqpReceiverLink_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockAmqpReceiverLink_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *amqp.ReceiveOptions
func (_e *MockAmqpReceiverLink_Expecter) Receive(ctx any, opts any) *MockAmqpReceiverLink_Receive_Call {
	return &MockAmqpReceiverLink_Receive_Call{Call: _e.mock.On("Receive", ctx, opts)}
}

func (_c *MockAmqpReceiverLink_Receive_Call) Run(run func(ctx context.Context, opts *amqp.ReceiveOptions)) *MockAmqpReceiverLink_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *amqp.ReceiveOptions
		if args[1] != nil {
			arg1 = args[1].(*amqp.ReceiveOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAmqpReceiverLink_Receive_Call) Return(message *amqp.Message, err error) *MockAmqpReceiverLink_Receive_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockAmqpReceiverLink_Receive_Call) RunAndReturn(run func(ctx context.Context, opts *amqp.ReceiveOptions) (*amqp.Message, error)) *MockAmqpReceiverLink_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// RejectMessage provides a mock function for the type MockAmqpReceiverLink
func (_mock *MockAmqpReceiverLink) RejectMessage(ctx context.Context, msg *amqp.Message, err *amqp.Error) error {
	ret := _mock.Called(ctx, msg, err)

	if len(ret) == 0 {
		panic("no return value specified for RejectMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.Message, *amqp.Error) error); ok {
		r0 = returnFunc(ctx, msg, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAmqpReceiverLink_RejectMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectMessage'
type MockAmqpReceiverLink_RejectMessage_Call struct {
	*mock.Call
}

// RejectMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *amqp.Message
//   - err *amqp.Error
func (_e *MockAmqpReceiverLink_Expecter) RejectMessage(ctx any, msg any, err any) *MockAmqpReceiverLink_RejectMessage_Call {
	return &MockAmqpReceiverLink_RejectMessage_Call{Call: _e.mock.On("RejectMessage", ctx, msg, err)}
}

func (_c *MockAmqpReceiverLink_RejectMessage_Call) Run(run func(ctx context.Context, msg *amqp.Message, err *amqp.Error)) *MockAmqpReceiverLink_RejectMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *amqp.Message
		if args[1] != nil {
			arg1 = args[1].(*amqp.Message)
		}
		var arg2 *amqp.Error
		if args[2] != nil {
			arg2 = args[2].(*amqp.Error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAmqpReceiverLink_RejectMessage_Call) Return(err1 error) *MockAmqpReceiverLink_RejectMessage_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockAmqpReceiverLink_RejectMessage_Call) RunAndReturn(run func(ctx context.Context, msg *amqp.Message, err *amqp.Error) error) *MockAmqpReceiverLink_RejectMessage_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseMessage provides a mock function for the type MockAmqpReceiverLink
func (_mock *MockAmqpReceiverLink) ReleaseMessage(ctx context.Context, msg *amqp.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *amqp.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAmqpReceiverLink_ReleaseMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseMessage'
type MockAmqpReceiverLink_ReleaseMessage_Call struct {
	*mock.Call
}

// ReleaseMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *amqp.Message
func (_e *MockAmqpReceiverLink_Expecter) ReleaseMessage(ctx any, msg any) *MockAmqpReceiverLink_ReleaseMessage_Call {
	return &MockAmqpReceiverLink_ReleaseMessage_Call{Call: _e.mock.On("ReleaseMessage", ctx, msg)}
}

func (_c *MockAmqpReceiverLink_ReleaseMessage_Call) Run(run func(ctx context.Context, msg *amqp.Message)) *MockAmqpReceiverLink_ReleaseMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *amqp.Message
		if args[1] != nil {
			arg1 = args[1].(*amqp.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAmqpReceiverLink_ReleaseMessage_Call) Return(err error) *MockAmqpReceiverLink_ReleaseMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAmqpReceiverLink_ReleaseMessage_Call) RunAndReturn(run func(ctx context.Context, msg *amqp.Message) error) *MockAmqpReceiverLink_ReleaseMessage_Call {
	_c.Call.Return(run)
	return _c
}
